-- PLEASE / CAL — STEP 18.10 Verification
-- READ ONLY. Run after STEP18_10_ACCOUNTANT_COMPLIANCE_CENTER.sql.
-- Expected: every row = PASS. Informational counts are included in detail.
with checks as (
select 1 n,'tables_created' name,
 case when (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in (
 'accounting_compliance_settings','accounting_gifi_codes','accounting_gifi_account_mappings','accounting_gifi_working_papers','accounting_gifi_working_paper_lines','accounting_compliance_obligations','accounting_compliance_approvals','accounting_filing_evidence','accounting_accountant_packages'))=9 then 'PASS' else 'FAIL' end status,
 '9 STEP 18.10 tables required' detail
union all select 2,'gifi_catalog_seeded',case when (select count(*) from public.accounting_gifi_codes where active)>=45 then 'PASS' else 'FAIL' end,(select count(*)||' active GIFI reference codes' from public.accounting_gifi_codes where active)
union all select 3,'critical_gifi_codes',case when (select count(*) from public.accounting_gifi_codes where code in ('1000','1002','1060','1066','1120','1484','1740','1741','2621','2624','2627','2628','2680','2700','3600','8000','8210','8360','8518','8670','9060','9999'))=22 then 'PASS' else 'FAIL' end,'verified current-COA reference codes present'
union all select 4,'current_cal_default_mappings',case when (select count(*) from public.accounting_accounts a join public.accounting_gifi_account_mappings m on m.account_id=a.id where a.code in ('1000','1090','1100','1200','1210','1300','1400','1500','1510','1600','2000','2010','2020','2030','2040','2050','2060','2070','2100','2110','2200','3000','4000','4050','5000','5100','5200','5300','5400','5500','5600','5700','6000','6100','6200','6300','7000','7010','7020'))=(select count(*) from public.accounting_accounts where code in ('1000','1090','1100','1200','1210','1300','1400','1500','1510','1600','2000','2010','2020','2030','2040','2050','2060','2070','2100','2110','2200','3000','4000','4050','5000','5100','5200','5300','5400','5500','5600','5700','6000','6100','6200','6300','7000','7010','7020')) then 'PASS' else 'FAIL' end,'all installed standard CAL accounts mapped'
union all select 5,'contra_asset_gifi_sign',case when exists(select 1 from public.accounting_accounts a join public.accounting_gifi_account_mappings m on m.account_id=a.id where a.code='1510' and m.gifi_code='1741' and m.sign_multiplier=1) then 'PASS' else 'FAIL' end,'1510 keeps natural negative debit-credit balance for GIFI 1741'
union all select 6,'gifi_mapping_unique',case when not exists(select account_id from public.accounting_gifi_account_mappings group by account_id having count(*)>1) then 'PASS' else 'FAIL' end,'one active mapping row per GL account'
union all select 7,'functions_installed',case when 
 to_regprocedure('public.accounting_generate_gifi_working_paper(integer,text)') is not null and
 to_regprocedure('public.accounting_generate_compliance_calendar(integer,text)') is not null and
 to_regprocedure('public.accounting_record_filing_evidence(uuid,text,text,timestamp with time zone,text,text,numeric,uuid,text,text,uuid,text)') is not null and
 to_regprocedure('public.accounting_generate_accountant_package(integer,text)') is not null and
 to_regprocedure('public.accounting_approve_accountant_package(uuid,text,text)') is not null
 then 'PASS' else 'FAIL' end,'core GIFI, calendar, evidence and package RPCs installed'
union all select 8,'fiscal_year_helper',case when to_regprocedure('public.accounting_compliance_fiscal_year_bounds(integer)') is not null then 'PASS' else 'FAIL' end,'company fiscal-year helper installed'
union all select 9,'working_paper_immutability',case when exists(select 1 from pg_trigger where tgrelid='public.accounting_gifi_working_paper_lines'::regclass and tgname='trg_accounting_gifi_lines_immutable' and not tgisinternal) then 'PASS' else 'FAIL' end,'generated GIFI lines are append-only by revision'
union all select 10,'approval_immutability',case when exists(select 1 from pg_trigger where tgrelid='public.accounting_compliance_approvals'::regclass and tgname='trg_accounting_compliance_approvals_immutable' and not tgisinternal) then 'PASS' else 'FAIL' end,'approval history immutable'
union all select 11,'evidence_immutability',case when exists(select 1 from pg_trigger where tgrelid='public.accounting_filing_evidence'::regclass and tgname='trg_accounting_filing_evidence_immutable' and not tgisinternal) then 'PASS' else 'FAIL' end,'filing/payment evidence immutable'
union all select 12,'package_snapshot_protected',case when exists(select 1 from pg_trigger where tgrelid='public.accounting_accountant_packages'::regclass and tgname='trg_accounting_package_snapshot_protect' and not tgisinternal) and exists(select 1 from pg_trigger where tgrelid='public.accounting_accountant_packages'::regclass and tgname='trg_accounting_package_delete_protect' and not tgisinternal) then 'PASS' else 'FAIL' end,'package snapshot cannot be rewritten or deleted'
union all select 13,'rls_enabled',case when (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('accounting_compliance_settings','accounting_gifi_codes','accounting_gifi_account_mappings','accounting_gifi_working_papers','accounting_gifi_working_paper_lines','accounting_compliance_obligations','accounting_compliance_approvals','accounting_filing_evidence','accounting_accountant_packages') and c.relrowsecurity)=9 then 'PASS' else 'FAIL' end,'RLS enabled on all STEP 18.10 tables'
union all select 14,'service_role_table_access',case when has_table_privilege('service_role','public.accounting_compliance_settings','SELECT') and has_table_privilege('service_role','public.accounting_accountant_packages','SELECT') and has_table_privilege('service_role','public.accounting_filing_evidence','INSERT') then 'PASS' else 'FAIL' end,'server-side service role has required access'
union all select 15,'no_anon_table_access',case when not has_table_privilege('anon','public.accounting_compliance_settings','SELECT') and not has_table_privilege('authenticated','public.accounting_accountant_packages','SELECT') then 'PASS' else 'FAIL' end,'browser roles cannot bypass CAL admin server API'
union all select 16,'compliance_settings_singleton',case when (select count(*) from public.accounting_compliance_settings)>=1 then 'PASS' else 'FAIL' end,(select count(*)||' compliance settings row(s)' from public.accounting_compliance_settings)
union all select 17,'three_month_basis_guard',case when not exists(select 1 from public.accounting_compliance_settings where (federal_balance_due_months=3 or alberta_balance_due_months=3) and length(btrim(coalesce(three_month_balance_due_basis,'')))<10) then 'PASS' else 'FAIL' end,'three-month corporate balance dates have documented eligibility basis'
union all select 18,'gst_frequency_conservative',case when not exists(select 1 from public.accounting_compliance_settings where gst_reporting_frequency not in ('UNCONFIGURED','MONTHLY','QUARTERLY','ANNUAL')) then 'PASS' else 'FAIL' end,'GST/HST calendar never guesses outside configured values'
union all select 19,'obligation_keys_unique',case when not exists(select obligation_key from public.accounting_compliance_obligations group by obligation_key having count(*)>1) then 'PASS' else 'FAIL' end,'compliance calendar generation idempotent by obligation_key'
union all select 20,'obligation_final_state_matches_kind',case when not exists(select 1 from public.accounting_compliance_obligations where (status='FILED' and action_kind<>'FILE') or (status='PAID' and action_kind not in ('PAY','REMIT'))) then 'PASS' else 'FAIL' end,'FILED/PAYMENT statuses align to obligation action kind'
union all select 21,'evidence_status_matches_obligation',case when not exists(select 1 from public.accounting_filing_evidence e join public.accounting_compliance_obligations o on o.id=e.obligation_id where (e.final_status='FILED' and o.action_kind<>'FILE') or (e.final_status='PAID' and o.action_kind not in ('PAY','REMIT'))) then 'PASS' else 'FAIL' end,'recorded evidence matches filing/payment/remittance type'
union all select 22,'evidence_supersession_same_obligation',case when not exists(select 1 from public.accounting_filing_evidence e join public.accounting_filing_evidence p on p.id=e.supersedes_evidence_id where e.obligation_id<>p.obligation_id) then 'PASS' else 'FAIL' end,'superseding evidence cannot cross obligations'
union all select 23,'evidence_single_superseder',case when not exists(select supersedes_evidence_id from public.accounting_filing_evidence where supersedes_evidence_id is not null group by supersedes_evidence_id having count(*)>1) then 'PASS' else 'FAIL' end,'one correction chain step per evidence row'
union all select 24,'approved_gifi_integrity',case when not exists(select 1 from public.accounting_gifi_working_papers where status='APPROVED' and (unmapped_nonzero_count<>0 or abs(source_trial_balance_difference)>0.01 or closed_coverage_days<>required_coverage_days)) then 'PASS' else 'FAIL' end,'approved GIFI papers are mapped, balanced and fully period-closed'
union all select 25,'package_hashes_valid',case when not exists(select 1 from public.accounting_accountant_packages where length(snapshot_sha256)<>64 or snapshot_json is null) then 'PASS' else 'FAIL' end,'all package revisions retain SHA-256 snapshot evidence'
union all select 26,'approved_package_gifi',case when not exists(select 1 from public.accounting_accountant_packages p left join public.accounting_gifi_working_papers g on g.id=p.gifi_working_paper_id where p.status='APPROVED' and coalesce(g.status,'')<>'APPROVED') then 'PASS' else 'FAIL' end,'approved packages reference approved GIFI paper'
union all select 27,'approved_package_closed_coverage',case when not exists(select 1 from public.accounting_accountant_packages p where p.status='APPROVED' and public.accounting_closed_coverage_days(p.period_start,p.period_end)<>(p.period_end-p.period_start)+1) then 'PASS' else 'FAIL' end,'approved package fiscal year is fully closed'
union all select 28,'approved_package_trial_balance',case when not exists(select 1 from public.accounting_accountant_packages where status='APPROVED' and abs(coalesce((snapshot_json->>'trial_balance_difference')::numeric,0))>0.01) then 'PASS' else 'FAIL' end,'approved package Trial Balance balanced'
union all select 29,'approved_package_inventory',case when not exists(select 1 from public.accounting_accountant_packages where status='APPROVED' and abs(coalesce((snapshot_json#>>'{inventory_reconciliation,difference}')::numeric,0))>0.02) then 'PASS' else 'FAIL' end,'approved package inventory reconciles to GL 1600'
union all select 30,'approved_package_fixed_assets',case when not exists(select 1 from public.accounting_accountant_packages where status='APPROVED' and (abs(coalesce((snapshot_json#>>'{fixed_assets_reconciliation,gross_difference}')::numeric,0))>0.02 or abs(coalesce((snapshot_json#>>'{fixed_assets_reconciliation,accum_difference}')::numeric,0))>0.02)) then 'PASS' else 'FAIL' end,'approved package fixed assets reconcile to GL 1500/1510'
union all select 31,'no_compliance_journal_events',case when not exists(select 1 from public.please_accounting_outbox where event_type like 'COMPLIANCE%' or event_type like 'GIFI%' or event_type like 'ACCOUNTANT_PACKAGE%') then 'PASS' else 'FAIL' end,'STEP 18.10 compliance actions create no accounting events or journals'
union all select 32,'period_boundaries_still_nonoverlapping',case when not exists(select 1 from public.accounting_fiscal_periods a join public.accounting_fiscal_periods b on a.id<b.id and a.period_start<=b.period_end and a.period_end>=b.period_start) then 'PASS' else 'FAIL' end,'STEP 18.9.1 period-boundary guardrail remains intact'
union all select 33,'package_snapshot_sections',case when not exists(select 1 from public.accounting_accountant_packages where not (snapshot_json ?& array['trial_balance','balance_sheet','income_statement','general_ledger','gifi_lines','accounts_receivable_open','accounts_payable_open','inventory_detail_as_of','fixed_asset_register','payroll_runs','compliance_obligations','filing_payment_evidence'])) then 'PASS' else 'FAIL' end,'generated accountant packages contain all required working-paper sections'
union all select 34,'gifi_revision_unique',case when not exists(select tax_year_end_year,revision from public.accounting_gifi_working_papers group by tax_year_end_year,revision having count(*)>1) then 'PASS' else 'FAIL' end,'GIFI revisions unique per fiscal year'
union all select 35,'package_revision_unique',case when not exists(select tax_year_end_year,revision from public.accounting_accountant_packages group by tax_year_end_year,revision having count(*)>1) then 'PASS' else 'FAIL' end,'accountant-package revisions unique per fiscal year'
union all select 36,'compliance_center_ready',case when to_regclass('public.accounting_compliance_obligations') is not null and to_regprocedure('public.accounting_build_accountant_package_snapshot(integer,uuid)') is not null then 'PASS' else 'FAIL' end,'STEP 18.10 database layer ready'
)
select lpad(n::text,2,'0') as check_no,name as check_name,status,detail from checks order by n;
