begin;

-- STEP 13.2 — Security & Production Hardening
-- Application-controlled rate limiting, tracking-token lifecycle, and removal
-- of the legacy Supabase Auth admin-note permission path.

create table if not exists public.portal_rate_limit_events (
  id bigint generated by default as identity primary key,
  bucket_hash text not null,
  endpoint text not null,
  occurred_at timestamptz not null default now()
);
create index if not exists portal_rate_limit_events_bucket_idx
  on public.portal_rate_limit_events(bucket_hash,endpoint,occurred_at desc);
alter table public.portal_rate_limit_events enable row level security;

create or replace function public.please_rate_limit_check(
  p_bucket_hash text,
  p_endpoint text,
  p_window_seconds integer,
  p_limit integer
)
returns table(allowed boolean,current_count integer,retry_after_seconds integer)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_window integer:=greatest(60,least(coalesce(p_window_seconds,900),86400));
  v_limit integer:=greatest(1,least(coalesce(p_limit,20),10000));
  v_count integer;
  v_oldest timestamptz;
begin
  if coalesce(length(p_bucket_hash),0)<32 or coalesce(length(p_endpoint),0)=0 then
    raise exception 'Invalid rate limit bucket';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_bucket_hash||'|'||p_endpoint,0));

  delete from public.portal_rate_limit_events
   where bucket_hash=p_bucket_hash
     and endpoint=p_endpoint
     and occurred_at < now() - interval '2 days';

  insert into public.portal_rate_limit_events(bucket_hash,endpoint)
  values(p_bucket_hash,left(p_endpoint,120));

  select count(*)::integer,min(occurred_at)
    into v_count,v_oldest
    from public.portal_rate_limit_events
   where bucket_hash=p_bucket_hash
     and endpoint=p_endpoint
     and occurred_at >= now() - make_interval(secs=>v_window);

  allowed := v_count <= v_limit;
  current_count := v_count;
  retry_after_seconds := case when allowed then 0 else greatest(1,ceil(extract(epoch from ((v_oldest + make_interval(secs=>v_window))-now())))::integer) end;
  return next;
end;
$$;
revoke all on function public.please_rate_limit_check(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.please_rate_limit_check(text,text,integer,integer) to service_role;

-- Issue secure tracking tokens server-side. The INITIAL link is preserved.
-- Recovery/admin links expire after 180 days and only the newest 5 non-initial
-- active tokens are retained for each request.
create or replace function public.please_issue_tracking_token(
  p_service_request_id uuid,
  p_token_hash text,
  p_source text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_source text:=upper(trim(coalesce(p_source,'')));
begin
  if v_source not in ('INITIAL','CUSTOMER_RECOVERY','ADMIN_GENERATED') then
    raise exception 'Invalid tracking token source';
  end if;
  if coalesce(length(p_token_hash),0)<32 then raise exception 'Invalid token hash'; end if;
  if not exists(select 1 from public.service_requests where id=p_service_request_id) then raise exception 'Service request not found'; end if;

  insert into public.service_request_tracking_tokens(service_request_id,token_hash,source,expires_at)
  values(
    p_service_request_id,
    p_token_hash,
    v_source,
    case when v_source='INITIAL' then null else now()+interval '180 days' end
  );

  if v_source<>'INITIAL' then
    update public.service_request_tracking_tokens t
       set revoked_at=coalesce(t.revoked_at,now())
     where t.service_request_id=p_service_request_id
       and t.source<>'INITIAL'
       and t.revoked_at is null
       and t.id in (
         select id from public.service_request_tracking_tokens
          where service_request_id=p_service_request_id
            and source<>'INITIAL'
            and revoked_at is null
          order by created_at desc
          offset 5
       );
  end if;
end;
$$;
revoke all on function public.please_issue_tracking_token(uuid,text,text) from public,anon,authenticated;
grant execute on function public.please_issue_tracking_token(uuid,text,text) to service_role;

-- Legacy Supabase Auth path is no longer used by PLEASE Administration.
revoke update (internal_notes) on public.provider_applications from authenticated;
revoke execute on function public.please_update_application_notes(uuid,text) from authenticated;
grant execute on function public.please_update_application_notes(uuid,text) to service_role;

commit;
