begin;

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Custom provider sessions. Provider Portal does NOT depend on Supabase Auth.
-- -----------------------------------------------------------------------------
create table if not exists public.provider_portal_sessions (
  id uuid primary key default gen_random_uuid(),
  provider_user_id uuid not null references public.provider_portal_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ip_address text,
  user_agent text
);
create index if not exists provider_portal_sessions_user_idx
  on public.provider_portal_sessions(provider_user_id, expires_at desc);
create index if not exists provider_portal_sessions_active_idx
  on public.provider_portal_sessions(token_hash, expires_at)
  where revoked_at is null;

create table if not exists public.provider_portal_login_audit (
  id bigint generated by default as identity primary key,
  email text not null,
  success boolean not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.provider_portal_sessions enable row level security;
alter table public.provider_portal_login_audit enable row level security;
revoke all on public.provider_portal_sessions from anon, authenticated;
revoke all on public.provider_portal_login_audit from anon, authenticated;

-- Track responses performed from the custom Provider Portal.
alter table public.assignment_status_history
  add column if not exists changed_by_provider_user uuid references public.provider_portal_users(id) on delete set null;

-- Authenticate custom provider credentials with bcrypt in PostgreSQL.
create or replace function public.provider_portal_authenticate(
  p_email text,
  p_password text
)
returns table (
  id uuid,
  provider_id uuid,
  email text,
  display_name text,
  provider_reference text,
  provider_status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if nullif(trim(p_email),'') is null or coalesce(p_password,'')='' then return; end if;

  return query
  update public.provider_portal_users u
     set last_login_at=now(), updated_at=now()
    from public.providers p
   where u.provider_id=p.id
     and lower(u.email)=lower(trim(p_email))
     and u.active=true
     and p.status='ACTIVE'
     and u.password_hash=crypt(p_password,u.password_hash)
  returning u.id,u.provider_id,u.email,u.display_name,p.reference,p.status;
end;
$$;
revoke all on function public.provider_portal_authenticate(text,text) from public,anon,authenticated;
grant execute on function public.provider_portal_authenticate(text,text) to service_role;

create or replace function public.provider_portal_change_password(
  p_actor uuid,
  p_current_password text,
  p_new_password text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if length(coalesce(p_new_password,'')) < 10 then
    raise exception 'New password must be at least 10 characters';
  end if;

  update public.provider_portal_users u
     set password_hash=crypt(p_new_password,gen_salt('bf',12)),
         password_changed_at=now(),updated_at=now()
   where u.id=p_actor and u.active=true
     and u.password_hash=crypt(p_current_password,u.password_hash);

  if not found then raise exception 'Current password is incorrect'; end if;

  update public.provider_portal_sessions
     set revoked_at=now()
   where provider_user_id=p_actor and revoked_at is null;
end;
$$;
revoke all on function public.provider_portal_change_password(uuid,text,text) from public,anon,authenticated;
grant execute on function public.provider_portal_change_password(uuid,text,text) to service_role;

-- Provider-controlled recurring availability and exceptions.
create or replace function public.provider_portal_availability_action(
  p_actor uuid,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_provider_id uuid;
  v_action text := upper(trim(coalesce(p_action,'')));
  v_item jsonb;
  v_exception_id bigint;
begin
  select u.provider_id into v_provider_id
    from public.provider_portal_users u
    join public.providers p on p.id=u.provider_id
   where u.id=p_actor and u.active=true and p.status='ACTIVE';
  if v_provider_id is null then raise exception 'Unauthorized'; end if;

  if v_action='SAVE_WEEKLY' then
    delete from public.provider_availability where provider_id=v_provider_id;
    for v_item in select value from jsonb_array_elements(coalesce(p_payload->'availability','[]'::jsonb)) loop
      if coalesce((v_item->>'active')::boolean,true) then
        if (v_item->>'weekday')::int not between 1 and 7 then raise exception 'Invalid weekday'; end if;
        if (v_item->>'start_time')::time >= (v_item->>'end_time')::time then raise exception 'Availability end time must be after start time'; end if;
        insert into public.provider_availability(provider_id,weekday,start_time,end_time,active)
        values(v_provider_id,(v_item->>'weekday')::smallint,(v_item->>'start_time')::time,(v_item->>'end_time')::time,true);
      end if;
    end loop;
    return jsonb_build_object('ok',true);

  elsif v_action='ADD_EXCEPTION' then
    if nullif(p_payload->>'exception_date','') is null then raise exception 'Date is required'; end if;
    if coalesce(p_payload->>'exception_type','') not in ('AVAILABLE','UNAVAILABLE') then raise exception 'Invalid exception type'; end if;
    insert into public.provider_availability_exceptions(provider_id,exception_date,start_time,end_time,exception_type,reason)
    values(
      v_provider_id,
      (p_payload->>'exception_date')::date,
      nullif(p_payload->>'start_time','')::time,
      nullif(p_payload->>'end_time','')::time,
      p_payload->>'exception_type',
      nullif(trim(p_payload->>'reason'),'')
    ) returning id into v_exception_id;
    return jsonb_build_object('ok',true,'exception_id',v_exception_id);

  elsif v_action='DELETE_EXCEPTION' then
    v_exception_id := nullif(p_payload->>'exception_id','')::bigint;
    if v_exception_id is null then raise exception 'Exception ID is required'; end if;
    delete from public.provider_availability_exceptions
     where id=v_exception_id and provider_id=v_provider_id;
    if not found then raise exception 'Availability exception not found'; end if;
    return jsonb_build_object('ok',true);
  end if;

  raise exception 'Unsupported availability action';
end;
$$;
revoke all on function public.provider_portal_availability_action(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.provider_portal_availability_action(uuid,text,jsonb) to service_role;

-- Provider response to an assignment. Provider cannot alter job, time or address.
create or replace function public.provider_portal_assignment_action(
  p_actor uuid,
  p_assignment_id uuid,
  p_action text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_provider_id uuid;
  v_job_id uuid;
  v_status text;
  v_action text := upper(trim(coalesce(p_action,'')));
begin
  select u.provider_id into v_provider_id
    from public.provider_portal_users u
    join public.providers p on p.id=u.provider_id
   where u.id=p_actor and u.active=true and p.status='ACTIVE';
  if v_provider_id is null then raise exception 'Unauthorized'; end if;

  select job_id,status into v_job_id,v_status
    from public.job_assignments
   where id=p_assignment_id and provider_id=v_provider_id
   for update;
  if not found then raise exception 'Assignment not found'; end if;
  if v_status<>'PENDING' then raise exception 'Only pending assignments can be answered'; end if;

  if v_action='CONFIRM' then
    update public.job_assignments
       set status='CONFIRMED',provider_response_note=nullif(trim(p_note),''),responded_at=now(),updated_at=now()
     where id=p_assignment_id;
    update public.jobs set status='CONFIRMED',updated_at=now() where id=v_job_id and status='PENDING_PROVIDER';
    insert into public.assignment_status_history(assignment_id,old_status,new_status,changed_by_provider_user,note)
    values(p_assignment_id,'PENDING','CONFIRMED',p_actor,nullif(trim(p_note),''));
    return jsonb_build_object('ok',true,'status','CONFIRMED');

  elsif v_action='DECLINE' then
    update public.job_assignments
       set status='DECLINED',provider_response_note=nullif(trim(p_note),''),responded_at=now(),updated_at=now()
     where id=p_assignment_id;
    update public.jobs set status='NEEDS_ASSIGNMENT',updated_at=now() where id=v_job_id and status='PENDING_PROVIDER';
    insert into public.assignment_status_history(assignment_id,old_status,new_status,changed_by_provider_user,note)
    values(p_assignment_id,'PENDING','DECLINED',p_actor,nullif(trim(p_note),''));
    return jsonb_build_object('ok',true,'status','DECLINED');
  end if;

  raise exception 'Unsupported assignment action';
end;
$$;
revoke all on function public.provider_portal_assignment_action(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.provider_portal_assignment_action(uuid,uuid,text,text) to service_role;

commit;
