-- PLEASE Portal — STEP 8: Invoices + Payments
-- Safe/idempotent extension of the invoice foundation created in STEP 1.

create extension if not exists pgcrypto;

alter table public.invoices add column if not exists currency text not null default 'CAD';
alter table public.invoices add column if not exists amount_paid numeric(10,2) not null default 0 check (amount_paid >= 0);
alter table public.invoices add column if not exists payment_method text;
alter table public.invoices add column if not exists payment_reference text;
alter table public.invoices add column if not exists sent_at timestamptz;
alter table public.invoices add column if not exists voided_at timestamptz;
alter table public.invoices add column if not exists void_reason text;
alter table public.invoices add column if not exists checkout_created_at timestamptz;

create table if not exists public.invoice_status_history (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  old_status text,
  new_status text not null,
  old_payment_status text,
  new_payment_status text,
  note text,
  changed_by_admin_portal_user uuid references public.admin_portal_users(id) on delete set null,
  source text not null default 'ADMIN' check (source in ('ADMIN','STRIPE','SYSTEM')),
  changed_at timestamptz not null default now()
);
create index if not exists invoice_status_history_invoice_idx on public.invoice_status_history(invoice_id, changed_at desc);

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  currency text not null default 'CAD',
  provider text not null default 'MANUAL' check (provider in ('MANUAL','STRIPE')),
  status text not null default 'SUCCEEDED' check (status in ('PENDING','SUCCEEDED','FAILED','REFUNDED')),
  external_reference text,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  note text,
  created_by_admin_portal_user uuid references public.admin_portal_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists payment_transactions_invoice_idx on public.payment_transactions(invoice_id, created_at desc);
create unique index if not exists payment_transactions_stripe_session_uidx
  on public.payment_transactions(stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

-- Recalculate invoice totals every time invoice items change.
create or replace function public.recalculate_invoice_totals(p_invoice_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_subtotal numeric(10,2);
  v_rate numeric(5,2);
begin
  select coalesce(sum(line_total),0) into v_subtotal
  from public.invoice_items
  where invoice_id=p_invoice_id;

  select gst_rate into v_rate from public.invoices where id=p_invoice_id;
  if v_rate is null then return; end if;

  update public.invoices
  set subtotal=round(v_subtotal,2),
      gst_amount=round(v_subtotal*(v_rate/100.0),2),
      total_amount=round(v_subtotal + v_subtotal*(v_rate/100.0),2),
      updated_at=now()
  where id=p_invoice_id;
end $$;

create or replace function public.invoice_items_recalculate_trigger()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  if tg_op='DELETE' then
    perform public.recalculate_invoice_totals(old.invoice_id);
    return old;
  else
    new.line_total := round(new.qty * new.unit_rate,2);
    perform public.recalculate_invoice_totals(new.invoice_id);
    return new;
  end if;
end $$;

drop trigger if exists trg_invoice_items_recalculate on public.invoice_items;
create trigger trg_invoice_items_recalculate
before insert or update on public.invoice_items
for each row execute function public.invoice_items_recalculate_trigger();

create or replace function public.invoice_items_recalculate_after_delete_trigger()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  perform public.recalculate_invoice_totals(old.invoice_id);
  return old;
end $$;

drop trigger if exists trg_invoice_items_recalculate_delete on public.invoice_items;
create trigger trg_invoice_items_recalculate_delete
after delete on public.invoice_items
for each row execute function public.invoice_items_recalculate_after_delete_trigger();

-- After insert/update totals need one final recalculation because BEFORE trigger runs before the row is visible to SUM.
create or replace function public.invoice_items_recalculate_after_write_trigger()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  perform public.recalculate_invoice_totals(new.invoice_id);
  return new;
end $$;

drop trigger if exists trg_invoice_items_recalculate_after_write on public.invoice_items;
create trigger trg_invoice_items_recalculate_after_write
after insert or update on public.invoice_items
for each row execute function public.invoice_items_recalculate_after_write_trigger();

alter table public.invoice_status_history enable row level security;
alter table public.payment_transactions enable row level security;

-- Browser clients should not access billing tables directly. Custom Admin Portal uses the service role on Netlify.
revoke all on public.invoice_status_history from anon, authenticated;
revoke all on public.payment_transactions from anon, authenticated;

comment on table public.payment_transactions is 'PLEASE invoice payment ledger. Stripe rows are created only after verified webhook events; manual rows are admin-attributed.';
comment on table public.invoice_status_history is 'Immutable operational billing history for invoice and payment status transitions.';
