begin;

create extension if not exists pgcrypto;

-- ============================================================
-- PLEASE STEP 13.2D
-- Provider Self-Management + Developer Account Control
-- ============================================================

-- Provider services keep a developer authorization boundary while allowing
-- the provider to temporarily enable/disable already-authorized services.
alter table public.provider_services
  add column if not exists developer_authorized boolean not null default true,
  add column if not exists provider_enabled boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

update public.provider_services
   set developer_authorized = true,
       provider_enabled = coalesce(active,true),
       active = coalesce(active,true)
 where developer_authorized is null or provider_enabled is null;

-- Provider documents are private. Existing Work With Us files are linked to
-- the activated provider without copying the Storage object.
create table if not exists public.provider_documents (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete cascade,
  source_application_file_id uuid references public.provider_application_files(id) on delete set null,
  document_type text not null check (document_type in ('CERTIFICATION','INSURANCE','LICENCE','PORTFOLIO','OTHER')),
  document_name text not null,
  storage_path text not null,
  mime_type text not null,
  file_size_bytes integer not null check (file_size_bytes >= 0),
  verification_status text not null default 'PENDING_REVIEW'
    check (verification_status in ('PENDING_REVIEW','VERIFIED','REJECTED','EXPIRED')),
  expires_on date,
  active boolean not null default true,
  uploaded_by_provider_user uuid references public.provider_portal_users(id) on delete set null,
  reviewed_by_developer_user uuid references public.admin_portal_users(id) on delete set null,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_id, source_application_file_id)
);
create index if not exists provider_documents_provider_idx
  on public.provider_documents(provider_id, active, document_type, created_at desc);
alter table public.provider_documents enable row level security;
revoke all on public.provider_documents from anon, authenticated;

-- Technical activity visible to the Provider (safe entries only) and to the
-- Developer. Security secrets/IPs are intentionally excluded from this log.
create table if not exists public.provider_technical_history (
  id bigint generated by default as identity primary key,
  provider_id uuid not null references public.providers(id) on delete cascade,
  event_type text not null,
  event_label text not null,
  details jsonb not null default '{}'::jsonb,
  actor_type text not null check (actor_type in ('DEVELOPER','PROVIDER','SYSTEM')),
  actor_admin_user_id uuid references public.admin_portal_users(id) on delete set null,
  actor_provider_user_id uuid references public.provider_portal_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists provider_technical_history_provider_idx
  on public.provider_technical_history(provider_id, created_at desc);
alter table public.provider_technical_history enable row level security;
revoke all on public.provider_technical_history from anon, authenticated;

-- Link documents submitted during Work With Us to providers that already exist.
insert into public.provider_documents(
  provider_id, source_application_file_id, document_type, document_name,
  storage_path, mime_type, file_size_bytes, verification_status, active, created_at
)
select p.id, f.id,
       case when f.file_type='CERTIFICATION' then 'CERTIFICATION'
            when f.file_type='INSURANCE' then 'INSURANCE'
            when f.file_type='PORTFOLIO' then 'PORTFOLIO'
            else 'OTHER' end,
       f.file_name, f.storage_path, f.mime_type, f.file_size_bytes,
       'PENDING_REVIEW', true, f.created_at
  from public.providers p
  join public.provider_application_files f on f.application_id=p.source_application_id
 where p.source_application_id is not null
on conflict(provider_id,source_application_file_id) do nothing;

-- Helper used by provider self-service RPCs.
create or replace function public.require_active_provider_user(p_actor uuid)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare v_provider uuid;
begin
  select u.provider_id into v_provider
    from public.provider_portal_users u
    join public.providers p on p.id=u.provider_id
   where u.id=p_actor and u.active=true and p.status='ACTIVE';
  if v_provider is null then raise exception 'Unauthorized'; end if;
  return v_provider;
end;
$$;
revoke all on function public.require_active_provider_user(uuid) from public,anon,authenticated;
grant execute on function public.require_active_provider_user(uuid) to service_role;

-- Provider edits only its business/profile fields. Account credentials and
-- provider status remain Developer-controlled.
create or replace function public.provider_portal_profile_action(
  p_actor uuid,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_provider uuid;
begin
  v_provider := public.require_active_provider_user(p_actor);

  update public.providers set
    display_name = coalesce(nullif(trim(p_payload->>'display_name'),''),display_name),
    company_name = nullif(trim(p_payload->>'company_name'),''),
    primary_email = nullif(trim(p_payload->>'primary_email'),''),
    primary_phone = nullif(trim(p_payload->>'primary_phone'),''),
    public_title = coalesce(nullif(trim(p_payload->>'public_title'),''),public_title),
    short_bio = nullif(trim(p_payload->>'short_bio'),''),
    technical_description = nullif(trim(p_payload->>'technical_description'),''),
    service_area = nullif(trim(p_payload->>'service_area'),''),
    licensed_certified = coalesce((p_payload->>'licensed_certified')::boolean,licensed_certified),
    insured = coalesce((p_payload->>'insured')::boolean,insured),
    profile_image_url = nullif(trim(p_payload->>'profile_image_url'),''),
    logo_url = nullif(trim(p_payload->>'logo_url'),''),
    updated_at=now()
  where id=v_provider;

  insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_provider_user_id)
  values(v_provider,'PROFILE_UPDATED','Provider profile / landing profile updated',
         '{}'::jsonb,'PROVIDER',p_actor);

  return jsonb_build_object('ok',true,'provider_id',v_provider);
end;
$$;
revoke all on function public.provider_portal_profile_action(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.provider_portal_profile_action(uuid,jsonb) to service_role;

-- Provider may only toggle services already authorized by Developer.
create or replace function public.provider_portal_service_action(
  p_actor uuid,
  p_service_id uuid,
  p_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_provider uuid;
  v_name text;
begin
  v_provider := public.require_active_provider_user(p_actor);

  update public.provider_services ps
     set provider_enabled=p_enabled,
         active=(developer_authorized and p_enabled),
         updated_at=now()
    from public.services s
   where ps.provider_id=v_provider
     and ps.service_id=p_service_id
     and ps.service_id=s.id
     and ps.developer_authorized=true
  returning s.name into v_name;
  if not found then raise exception 'Service is not authorized for this provider'; end if;

  insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_provider_user_id)
  values(v_provider,'SERVICE_AVAILABILITY_CHANGED',
         case when p_enabled then 'Assigned service enabled' else 'Assigned service paused' end,
         jsonb_build_object('service_id',p_service_id,'service_name',v_name,'enabled',p_enabled),
         'PROVIDER',p_actor);
  return jsonb_build_object('ok',true,'enabled',p_enabled);
end;
$$;
revoke all on function public.provider_portal_service_action(uuid,uuid,boolean) from public,anon,authenticated;
grant execute on function public.provider_portal_service_action(uuid,uuid,boolean) to service_role;

-- Developer controls account credentials and ability to sign in. Provider data,
-- Jobs and financial history are preserved when the account is deactivated.
create or replace function public.developer_provider_account_action(
  p_actor uuid,
  p_provider_id uuid,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_action text := upper(trim(coalesce(p_action,'')));
  v_email text;
  v_password text;
  v_user uuid;
  v_status text;
begin
  if not exists(select 1 from public.admin_portal_users where id=p_actor and active=true and role='DEVELOPER_ADMIN') then
    raise exception 'Unauthorized';
  end if;
  if not exists(select 1 from public.providers where id=p_provider_id) then raise exception 'Provider not found'; end if;
  select id into v_user from public.provider_portal_users where provider_id=p_provider_id limit 1;

  if v_action='CHANGE_LOGIN_EMAIL' then
    v_email := lower(trim(coalesce(p_payload->>'email','')));
    if v_email='' or position('@' in v_email)<2 then raise exception 'Valid login email is required'; end if;
    if v_user is null then raise exception 'Provider portal account does not exist'; end if;
    update public.provider_portal_users set email=v_email,updated_at=now() where id=v_user;
    insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_admin_user_id)
    values(p_provider_id,'LOGIN_EMAIL_CHANGED','Provider login email changed',jsonb_build_object('email',v_email),'DEVELOPER',p_actor);

  elsif v_action='RESET_PASSWORD' then
    v_password := coalesce(p_payload->>'password','');
    if length(v_password)<10 then raise exception 'Provider password must be at least 10 characters'; end if;
    if v_user is null then raise exception 'Provider portal account does not exist'; end if;
    update public.provider_portal_users
       set password_hash=crypt(v_password,gen_salt('bf',12)),password_changed_at=now(),updated_at=now()
     where id=v_user;
    update public.provider_portal_sessions set revoked_at=now() where provider_user_id=v_user and revoked_at is null;
    insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_admin_user_id)
    values(p_provider_id,'PASSWORD_RESET','Provider password reset by Developer','DEVELOPER',p_actor);

  elsif v_action='DEACTIVATE' then
    update public.providers set status='SUSPENDED',public_visible=false,updated_by_portal_user=p_actor,updated_at=now() where id=p_provider_id;
    update public.provider_portal_users set active=false,updated_at=now() where provider_id=p_provider_id;
    update public.provider_portal_sessions set revoked_at=now()
     where provider_user_id in (select id from public.provider_portal_users where provider_id=p_provider_id) and revoked_at is null;
    insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_admin_user_id)
    values(p_provider_id,'ACCOUNT_DEACTIVATED','Provider portal account deactivated','DEVELOPER',p_actor);

  elsif v_action='REACTIVATE' then
    if v_user is null then raise exception 'Provider portal account does not exist'; end if;
    update public.providers set status='ACTIVE',updated_by_portal_user=p_actor,updated_at=now() where id=p_provider_id;
    update public.provider_portal_users set active=true,updated_at=now() where provider_id=p_provider_id;
    insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_admin_user_id)
    values(p_provider_id,'ACCOUNT_REACTIVATED','Provider portal account reactivated','DEVELOPER',p_actor);

  elsif v_action='ARCHIVE' then
    update public.providers set status='INACTIVE',public_visible=false,updated_by_portal_user=p_actor,updated_at=now() where id=p_provider_id;
    update public.provider_portal_users set active=false,updated_at=now() where provider_id=p_provider_id;
    update public.provider_portal_sessions set revoked_at=now()
     where provider_user_id in (select id from public.provider_portal_users where provider_id=p_provider_id) and revoked_at is null;
    insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_admin_user_id)
    values(p_provider_id,'ACCOUNT_ARCHIVED','Provider account archived','DEVELOPER',p_actor);

  elsif v_action='SET_PUBLIC_VISIBILITY' then
    update public.providers set public_visible=coalesce((p_payload->>'public_visible')::boolean,false),updated_by_portal_user=p_actor,updated_at=now()
     where id=p_provider_id;
    insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_admin_user_id)
    values(p_provider_id,'PUBLIC_VISIBILITY_CHANGED','Landing profile visibility changed by Developer',
           jsonb_build_object('public_visible',coalesce((p_payload->>'public_visible')::boolean,false)),'DEVELOPER',p_actor);
  else
    raise exception 'Unsupported developer provider-account action';
  end if;

  select status into v_status from public.providers where id=p_provider_id;
  return jsonb_build_object('ok',true,'provider_id',p_provider_id,'status',v_status);
end;
$$;
revoke all on function public.developer_provider_account_action(uuid,uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.developer_provider_account_action(uuid,uuid,text,jsonb) to service_role;

-- Document review remains Developer-controlled.
create or replace function public.developer_provider_document_action(
  p_actor uuid,
  p_document_id uuid,
  p_status text,
  p_note text default null,
  p_expires_on date default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_provider uuid; v_status text:=upper(trim(coalesce(p_status,'')));
begin
  if not exists(select 1 from public.admin_portal_users where id=p_actor and active=true and role='DEVELOPER_ADMIN') then raise exception 'Unauthorized'; end if;
  if v_status not in ('PENDING_REVIEW','VERIFIED','REJECTED','EXPIRED') then raise exception 'Invalid document status'; end if;
  update public.provider_documents
     set verification_status=v_status,review_note=nullif(trim(p_note),''),expires_on=p_expires_on,
         reviewed_by_developer_user=p_actor,updated_at=now()
   where id=p_document_id and active=true returning provider_id into v_provider;
  if not found then raise exception 'Document not found'; end if;
  insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_admin_user_id)
  values(v_provider,'DOCUMENT_REVIEWED','Provider document reviewed',jsonb_build_object('document_id',p_document_id,'status',v_status),'DEVELOPER',p_actor);
  return jsonb_build_object('ok',true,'status',v_status);
end;
$$;
revoke all on function public.developer_provider_document_action(uuid,uuid,text,text,date) from public,anon,authenticated;
grant execute on function public.developer_provider_document_action(uuid,uuid,text,text,date) to service_role;

-- Keep existing availability behavior but add safe technical history.
create or replace function public.provider_portal_availability_action(
  p_actor uuid,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_provider_id uuid;
  v_action text := upper(trim(coalesce(p_action,'')));
  v_item jsonb;
  v_exception_id bigint;
begin
  v_provider_id := public.require_active_provider_user(p_actor);

  if v_action='SAVE_WEEKLY' then
    delete from public.provider_availability where provider_id=v_provider_id;
    for v_item in select value from jsonb_array_elements(coalesce(p_payload->'availability','[]'::jsonb)) loop
      if coalesce((v_item->>'active')::boolean,true) then
        if (v_item->>'weekday')::int not between 1 and 7 then raise exception 'Invalid weekday'; end if;
        if (v_item->>'start_time')::time >= (v_item->>'end_time')::time then raise exception 'Availability end time must be after start time'; end if;
        insert into public.provider_availability(provider_id,weekday,start_time,end_time,active)
        values(v_provider_id,(v_item->>'weekday')::smallint,(v_item->>'start_time')::time,(v_item->>'end_time')::time,true);
      end if;
    end loop;
    insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_provider_user_id)
    values(v_provider_id,'AVAILABILITY_UPDATED','Weekly service hours updated','PROVIDER',p_actor);
    return jsonb_build_object('ok',true);

  elsif v_action='ADD_EXCEPTION' then
    if nullif(p_payload->>'exception_date','') is null then raise exception 'Date is required'; end if;
    if coalesce(p_payload->>'exception_type','') not in ('AVAILABLE','UNAVAILABLE') then raise exception 'Invalid exception type'; end if;
    insert into public.provider_availability_exceptions(provider_id,exception_date,start_time,end_time,exception_type,reason)
    values(v_provider_id,(p_payload->>'exception_date')::date,nullif(p_payload->>'start_time','')::time,
           nullif(p_payload->>'end_time','')::time,p_payload->>'exception_type',nullif(trim(p_payload->>'reason'),''))
    returning id into v_exception_id;
    insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_provider_user_id)
    values(v_provider_id,'AVAILABILITY_EXCEPTION_ADDED','Availability exception added',jsonb_build_object('exception_id',v_exception_id,'date',p_payload->>'exception_date'),'PROVIDER',p_actor);
    return jsonb_build_object('ok',true,'exception_id',v_exception_id);

  elsif v_action='DELETE_EXCEPTION' then
    v_exception_id := nullif(p_payload->>'exception_id','')::bigint;
    if v_exception_id is null then raise exception 'Exception ID is required'; end if;
    delete from public.provider_availability_exceptions where id=v_exception_id and provider_id=v_provider_id;
    if not found then raise exception 'Availability exception not found'; end if;
    insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_provider_user_id)
    values(v_provider_id,'AVAILABILITY_EXCEPTION_REMOVED','Availability exception removed',jsonb_build_object('exception_id',v_exception_id),'PROVIDER',p_actor);
    return jsonb_build_object('ok',true);
  end if;
  raise exception 'Unsupported availability action';
end;
$$;
revoke all on function public.provider_portal_availability_action(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.provider_portal_availability_action(uuid,text,jsonb) to service_role;


-- Developer authorizes the service catalogue available to a Provider. Provider
-- may later pause/re-enable only rows that remain developer_authorized=true.
create or replace function public.developer_provider_service_action(
  p_actor uuid,
  p_provider_id uuid,
  p_service_ids jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_item jsonb; v_service uuid; v_names text[] := array[]::text[];
begin
  if not exists(select 1 from public.admin_portal_users where id=p_actor and active=true and role='DEVELOPER_ADMIN') then raise exception 'Unauthorized'; end if;
  if not exists(select 1 from public.providers where id=p_provider_id) then raise exception 'Provider not found'; end if;

  update public.provider_services
     set developer_authorized=false,provider_enabled=false,active=false,updated_at=now()
   where provider_id=p_provider_id;

  for v_item in select value from jsonb_array_elements(coalesce(p_service_ids,'[]'::jsonb)) loop
    begin v_service := trim(both '"' from v_item::text)::uuid;
    exception when others then raise exception 'Invalid service id'; end;
    if not exists(select 1 from public.services where id=v_service and active=true) then raise exception 'Service does not exist or is inactive'; end if;
    insert into public.provider_services(provider_id,service_id,active,developer_authorized,provider_enabled,updated_at)
    values(p_provider_id,v_service,true,true,true,now())
    on conflict(provider_id,service_id) do update set
      developer_authorized=true,
      provider_enabled=case when public.provider_services.developer_authorized=false then true else public.provider_services.provider_enabled end,
      active=case when public.provider_services.developer_authorized=false then true else public.provider_services.provider_enabled end,
      updated_at=now();
    v_names := array_append(v_names,(select name from public.services where id=v_service));
  end loop;

  insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type,actor_admin_user_id)
  values(p_provider_id,'AUTHORIZED_SERVICES_CHANGED','Developer updated authorized services',jsonb_build_object('services',v_names),'DEVELOPER',p_actor);
  return jsonb_build_object('ok',true,'count',jsonb_array_length(coalesce(p_service_ids,'[]'::jsonb)));
end;
$$;
revoke all on function public.developer_provider_service_action(uuid,uuid,jsonb) from public,anon,authenticated;
grant execute on function public.developer_provider_service_action(uuid,uuid,jsonb) to service_role;

-- Provider self-service password changes are also recorded in the safe technical history.
create or replace function public.provider_portal_change_password(
  p_actor uuid,
  p_current_password text,
  p_new_password text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_provider uuid;
begin
  if length(coalesce(p_new_password,'')) < 10 then raise exception 'New password must be at least 10 characters'; end if;
  update public.provider_portal_users u
     set password_hash=crypt(p_new_password,gen_salt('bf',12)),password_changed_at=now(),updated_at=now()
   where u.id=p_actor and u.active=true and u.password_hash=crypt(p_current_password,u.password_hash)
   returning provider_id into v_provider;
  if not found then raise exception 'Current password is incorrect'; end if;
  update public.provider_portal_sessions set revoked_at=now() where provider_user_id=p_actor and revoked_at is null;
  insert into public.provider_technical_history(provider_id,event_type,event_label,actor_type,actor_provider_user_id)
  values(v_provider,'PASSWORD_CHANGED','Provider changed portal password','PROVIDER',p_actor);
end;
$$;
revoke all on function public.provider_portal_change_password(uuid,text,text) from public,anon,authenticated;
grant execute on function public.provider_portal_change_password(uuid,text,text) to service_role;

-- Seed one safe baseline event for existing providers with no history yet.
insert into public.provider_technical_history(provider_id,event_type,event_label,details,actor_type)
select p.id,'ACCOUNT_BASELINE','Provider account present at STEP 13.2D migration',jsonb_build_object('status',p.status),'SYSTEM'
from public.providers p
where not exists(select 1 from public.provider_technical_history h where h.provider_id=p.id);

-- Harden browser access: all new tables stay service-role only.
revoke all on public.provider_documents from public,anon,authenticated;
revoke all on public.provider_technical_history from public,anon,authenticated;

commit;
