begin;

create extension if not exists pgcrypto;

create table if not exists public.admin_portal_users (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  display_name text not null,
  password_hash text not null,
  role text not null default 'PLEASE_ADMIN' check (role in ('PLEASE_ADMIN','DEVELOPER_ADMIN')),
  active boolean not null default true,
  last_login_at timestamptz,
  password_changed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admin_portal_users_email_uidx
  on public.admin_portal_users (lower(email));

create table if not exists public.admin_portal_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.admin_portal_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ip_address text,
  user_agent text
);

create index if not exists admin_portal_sessions_user_idx
  on public.admin_portal_sessions(user_id, expires_at desc);
create index if not exists admin_portal_sessions_active_idx
  on public.admin_portal_sessions(token_hash, expires_at)
  where revoked_at is null;

create table if not exists public.admin_portal_login_audit (
  id bigint generated by default as identity primary key,
  email text not null,
  success boolean not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.admin_portal_users enable row level security;
alter table public.admin_portal_sessions enable row level security;
alter table public.admin_portal_login_audit enable row level security;

revoke all on public.admin_portal_users from anon, authenticated;
revoke all on public.admin_portal_sessions from anon, authenticated;
revoke all on public.admin_portal_login_audit from anon, authenticated;

-- Keep the original Supabase Auth columns for compatibility/audit, but add
-- custom portal-user attribution for the new non-Supabase-Auth admin login.
alter table public.provider_applications
  add column if not exists reviewed_by_portal_user uuid references public.admin_portal_users(id) on delete set null,
  add column if not exists referred_by_portal_user uuid references public.admin_portal_users(id) on delete set null;

alter table public.provider_application_status_history
  add column if not exists changed_by_portal_user uuid references public.admin_portal_users(id) on delete set null;

-- Called only from a privileged Netlify Function. Passwords are verified in
-- PostgreSQL using bcrypt-compatible pgcrypto crypt(), never returned to JS.
create or replace function public.admin_portal_authenticate(
  p_email text,
  p_password text
)
returns table (
  id uuid,
  email text,
  display_name text,
  role text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if nullif(trim(p_email), '') is null or coalesce(p_password, '') = '' then
    return;
  end if;

  return query
  update public.admin_portal_users u
     set last_login_at = now(), updated_at = now()
   where lower(u.email) = lower(trim(p_email))
     and u.active = true
     and u.password_hash = crypt(p_password, u.password_hash)
  returning u.id, u.email, u.display_name, u.role;
end;
$$;

revoke all on function public.admin_portal_authenticate(text,text) from public, anon, authenticated;
grant execute on function public.admin_portal_authenticate(text,text) to service_role;

-- Manual/developer provisioning helper. The real password is hashed before
-- storage. This function is never granted to browser roles.
create or replace function public.admin_portal_upsert_user(
  p_email text,
  p_display_name text,
  p_password text,
  p_role text default 'PLEASE_ADMIN'
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id uuid;
begin
  if nullif(trim(p_email), '') is null then raise exception 'Email is required'; end if;
  if nullif(trim(p_display_name), '') is null then raise exception 'Display name is required'; end if;
  if length(coalesce(p_password,'')) < 10 then raise exception 'Password must be at least 10 characters'; end if;
  if p_role not in ('PLEASE_ADMIN','DEVELOPER_ADMIN') then raise exception 'Invalid portal role'; end if;

  select id into v_id
    from public.admin_portal_users
   where lower(email) = lower(trim(p_email))
   limit 1;

  if v_id is null then
    insert into public.admin_portal_users(email, display_name, password_hash, role, active)
    values(lower(trim(p_email)), trim(p_display_name), crypt(p_password, gen_salt('bf', 12)), p_role, true)
    returning id into v_id;
  else
    update public.admin_portal_users
       set display_name = trim(p_display_name),
           password_hash = crypt(p_password, gen_salt('bf', 12)),
           role = p_role,
           active = true,
           password_changed_at = now(),
           updated_at = now()
     where id = v_id;
  end if;

  -- Password reset/change invalidates any previous sessions.
  update public.admin_portal_sessions set revoked_at = now()
   where user_id = v_id and revoked_at is null;

  return v_id;
end;
$$;

revoke all on function public.admin_portal_upsert_user(text,text,text,text) from public, anon, authenticated;
grant execute on function public.admin_portal_upsert_user(text,text,text,text) to service_role;

create or replace function public.admin_portal_change_password(
  p_actor uuid,
  p_current_password text,
  p_new_password text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if length(coalesce(p_new_password,'')) < 10 then
    raise exception 'New password must be at least 10 characters';
  end if;

  update public.admin_portal_users u
     set password_hash = crypt(p_new_password, gen_salt('bf',12)),
         password_changed_at = now(),
         updated_at = now()
   where u.id = p_actor
     and u.active = true
     and u.password_hash = crypt(p_current_password, u.password_hash);

  if not found then raise exception 'Current password is incorrect'; end if;

  update public.admin_portal_sessions
     set revoked_at = now()
   where user_id = p_actor and revoked_at is null;
end;
$$;

revoke all on function public.admin_portal_change_password(uuid,text,text) from public, anon, authenticated;
grant execute on function public.admin_portal_change_password(uuid,text,text) to service_role;

-- Status history now recognizes either a Supabase Auth user (legacy/provider
-- flows) or the custom portal user set locally by the privileged workflow RPC.
create or replace function public.log_provider_application_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_portal_user uuid;
begin
  begin
    v_portal_user := nullif(current_setting('app.portal_user_id', true),'')::uuid;
  exception when others then
    v_portal_user := null;
  end;

  if tg_op = 'INSERT' then
    insert into public.provider_application_status_history(
      application_id, old_status, new_status, changed_by, changed_by_portal_user, note
    ) values (
      new.id, null, new.status, auth.uid(), v_portal_user, 'Application submitted'
    );
  elsif old.status is distinct from new.status then
    insert into public.provider_application_status_history(
      application_id, old_status, new_status, changed_by, changed_by_portal_user, note
    ) values (
      new.id, old.status, new.status, auth.uid(), v_portal_user, null
    );
  end if;
  return new;
end;
$$;

-- Single server-only workflow entrypoint for PLEASE Admin. The browser never
-- receives the Supabase secret and cannot arbitrarily update workflow fields.
create or replace function public.admin_portal_application_action(
  p_actor uuid,
  p_application_id uuid,
  p_action text,
  p_value text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_action text := upper(trim(coalesce(p_action,'')));
begin
  if not exists (
    select 1 from public.admin_portal_users
     where id = p_actor and active = true and role = 'PLEASE_ADMIN'
  ) then raise exception 'Unauthorized'; end if;

  perform set_config('app.portal_user_id', p_actor::text, true);

  select status into v_status
    from public.provider_applications
   where id = p_application_id
   for update;
  if not found then raise exception 'Application not found'; end if;

  if v_action = 'START_REVIEW' then
    if v_status <> 'NEW' then raise exception 'Application must be NEW to start review'; end if;
    update public.provider_applications
       set status='UNDER_REVIEW', reviewed_by_portal_user=p_actor,
           reviewed_at=now(), updated_at=now()
     where id=p_application_id;

  elsif v_action = 'REFER_TO_DEVELOPER' then
    if v_status <> 'UNDER_REVIEW' then raise exception 'Application must be UNDER_REVIEW before referral'; end if;
    update public.provider_applications
       set status='REFERRED_TO_DEVELOPER', referred_by_portal_user=p_actor,
           referred_to_developer_at=now(), updated_at=now()
     where id=p_application_id;

  elsif v_action = 'DECLINE' then
    if v_status not in ('NEW','UNDER_REVIEW') then
      raise exception 'PLEASE can only decline NEW or UNDER_REVIEW applications';
    end if;
    if nullif(trim(coalesce(p_value,'')),'') is null then raise exception 'Decline reason is required'; end if;
    update public.provider_applications
       set status='DECLINED', declined_at=now(), decline_reason=trim(p_value), updated_at=now()
     where id=p_application_id;

  elsif v_action = 'SAVE_NOTES' then
    update public.provider_applications
       set internal_notes=nullif(trim(coalesce(p_value,'')),''), updated_at=now()
     where id=p_application_id;

  else
    raise exception 'Unsupported action';
  end if;
end;
$$;

revoke all on function public.admin_portal_application_action(uuid,uuid,text,text) from public, anon, authenticated;
grant execute on function public.admin_portal_application_action(uuid,uuid,text,text) to service_role;

commit;
