(()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n)||0),fmt=v=>v?new Intl.DateTimeFormat('en-CA',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Edmonton'}).format(new Date(v)):'—';let data={};
async function api(u,o={}){const isJson=o.body&&typeof o.body==='string';const r=await fetch(u,{credentials:'same-origin',cache:'no-store',headers:{...(isJson?{'content-type':'application/json'}:{}),...(o.headers||{})},...o}),d=await r.json().catch(()=>({}));if(r.status===401){location.replace('admin-login.html');throw Error('Session expired.')}if(!r.ok)throw Error(d.error||'Request failed.');return d}
async function rawUpload(url,file){if(!file)throw Error('Select a supporting document.');if(file.size>5*1024*1024)throw Error('Supporting document must be 5 MB or smaller.');const allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type))throw Error('Use PDF, JPG, PNG or WEBP.');const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'content-type':file.type,'x-file-name':encodeURIComponent(file.name||'document')},body:file}),d=await r.json().catch(()=>({}));if(r.status===401){location.replace('admin-login.html');throw Error('Session expired.')}if(!r.ok)throw Error(d.error||'Document upload failed.');return d}
function show(m,ok=false){const a=$('finance-alert');a.hidden=false;a.className=`form-alert ${ok?'success':''}`;a.textContent=m;scrollTo({top:0,behavior:'smooth'});}
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Edmonton',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),v=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${v.year}-${v.month}-${v.day}`}
function categoryInfo(id){return(data.categories||[]).find(x=>x.id===id)||{}}
function setInventoryVisibility(prefix){const c=categoryInfo($(`${prefix}-category`).value),on=!!c.inventory;$(`${prefix}-item-wrap`).hidden=!on;$(`${prefix}-location-wrap`).hidden=!on;$(`${prefix}-item`).required=on;$(`${prefix}-location`).required=on;}
function opt(items,value,label){return(items||[]).map(x=>`<option value="${esc(x[value])}">${esc(label(x))}</option>`).join('')}

function render(d){data=d||{};const s=d.summary||{};
 $('fin-ar').textContent=money(s.receivable);$('fin-expenses').textContent=s.draft_expenses||0;$('fin-ap').textContent=money(s.payable);$('fin-collected').textContent=money(s.collected);$('fin-bank').textContent=s.unmatched_bank||0;$('fin-exceptions').textContent=s.open_exceptions||0;$('fin-queue').textContent=s.pending_finance||0;
 const settings=d.settings||{};$('fs-draft').checked=settings.auto_create_invoice_draft!==false;$('fs-issue').checked=!!settings.auto_issue_invoice;$('fs-email').checked=!!settings.auto_email_invoice;$('fs-gst').value=Number(settings.default_gst_rate??5).toFixed(2);
 const catHtml=opt(d.categories,'id',x=>`${x.label}${x.review?' · controlled review':''}`);$('qe-category').innerHTML=catHtml;$('qb-category').innerHTML=catHtml;
 const accountHtml='<option value="">Select account…</option>'+opt(d.financial_accounts,'id',x=>`${x.name} · ${String(x.financial_type||'').replaceAll('_',' ')}${x.is_primary?' · Primary':''}`);$('qe-account').innerHTML=accountHtml;
 $('qb-supplier').innerHTML='<option value="">Select supplier…</option>'+opt(d.suppliers,'id',x=>x.display_name||x.legal_name||x.email||'Supplier');
 const invItems='<option value="">Select item…</option>'+opt(d.inventory_items,'id',x=>`${x.sku} · ${x.name}`),invLoc='<option value="">Select location…</option>'+opt(d.inventory_locations,'id',x=>`${x.code} · ${x.name}`);$('qe-item').innerHTML=invItems;$('qb-item').innerHTML=invItems;$('qe-location').innerHTML=invLoc;$('qb-location').innerHTML=invLoc;
 $('bank-account').innerHTML='<option value="">Select bank…</option>'+opt(d.bank_accounts,'id',x=>x.name);$('cash-account').innerHTML='<option value="">Select cash account…</option>'+opt(d.cash_accounts,'id',x=>x.name);
 setInventoryVisibility('qe');setInventoryVisibility('qb');renderInvoices();renderExpenses();renderBills();renderBank();renderCash();renderExceptions();renderQueue();bindRows();
}
function renderInvoices(){const rows=data.open_invoices||[];$('finance-invoice-list').innerHTML=rows.length?rows.slice(0,40).map(x=>{const balance=Math.max(0,Number(x.total_amount||0)-Number(x.amount_paid||0)),buttons=[];if(x.status==='DRAFT')buttons.push(`<button class="admin-outline-button invoice-issue" data-id="${esc(x.id)}">ISSUE</button>`);if(x.status==='ISSUED')buttons.push(`<button class="admin-outline-button invoice-send" data-id="${esc(x.id)}">SEND</button>`);if(!['DRAFT','VOID','PAID'].includes(x.status)&&balance>.004)buttons.push(`<button class="admin-outline-button invoice-pay" data-id="${esc(x.id)}" data-balance="${balance}">RECORD PAYMENT</button>`);return`<article class="finance-row"><div><span>${esc(x.status||'')} · ${esc(x.payment_status||'')}</span><strong>${esc(x.invoice_number||'Invoice')} · ${money(x.total_amount)}</strong><small>${esc(x.client_name||x.client_email||'Customer')} · Balance ${money(balance)}${x.due_date?` · Due ${esc(x.due_date)}`:''}</small></div><div>${buttons.join('')}<a class="admin-outline-button" href="admin-invoices.html">VIEW</a></div></article>`}).join(''):'<p class="admin-muted">No open invoices.</p>'}
function renderExpenses(){const rows=data.quick_expenses||[];$('quick-expense-recent').innerHTML=rows.slice(0,8).map(x=>`<div><span><b>${esc(x.expense_number||'Expense')}</b> · ${esc(x.expense_date||'')} · ${esc(x.description||'')}</span><strong>${money(x.total)}</strong><small>${esc(x.status||'')} · Receipt ${esc(x.receipt_status||'—')}${['DRAFT','REJECTED','SUBMITTED','APPROVED'].includes(x.status)?` · <button class="finance-text-button expense-finish" data-id="${esc(x.id)}" data-receipt="${esc(x.receipt_status||'')}">Finish / Post</button>`:''}</small></div>`).join('')||'<p class="admin-muted">No operational expenses yet.</p>'}
function renderBills(){const rows=data.supplier_bills||[];$('finance-bill-list').innerHTML=rows.slice(0,12).map(x=>{const controls=[];if(['DRAFT','SUBMITTED','APPROVED'].includes(x.status))controls.push(`<button class="admin-outline-button bill-finish" data-id="${esc(x.id)}" data-doc="${x.source_document_id?'1':'0'}">FINISH / POST</button>`);if(['POSTED','PARTIAL'].includes(x.status)&&Number(x.balance_due)>.004)controls.push(`<button class="admin-outline-button bill-pay" data-id="${esc(x.id)}" data-balance="${Number(x.balance_due)}">PAY</button>`);return`<article class="finance-row"><div><span>${esc(x.status||'')}</span><strong>${esc(x.bill_number||'Bill')} · ${money(x.total)}</strong><small>${esc(x.supplier?.display_name||x.supplier?.legal_name||'Supplier')} · Balance ${money(x.balance_due)}${x.supplier_invoice_number?` · Invoice ${esc(x.supplier_invoice_number)}`:''}</small></div><div>${controls.join('')}</div></article>`}).join('')||'<p class="admin-muted">No supplier bills yet.</p>'}
function renderBank(){const rs=data.bank_reconciliations||[];$('bank-recon-list').innerHTML=rs.slice(0,6).map(x=>`<div><span><b>${esc(x.period_start)} → ${esc(x.period_end)}</b></span><strong>${esc(x.status||'')}</strong><small>${esc(x.statement_reference||'Statement')}${x.status!=='CLOSED'?` · <button class="finance-text-button bank-import" data-id="${esc(x.id)}">Import & Match</button> · <button class="finance-text-button bank-match" data-id="${esc(x.id)}">Auto Match</button> · <button class="finance-text-button bank-close" data-id="${esc(x.id)}">Close</button>`:''}</small></div>`).join('')||'<p class="admin-muted">No bank reconciliations yet.</p>';
 const un=data.unmatched_bank_transactions||[];$('bank-unmatched-list').innerHTML=un.length?`<h3 style="margin-top:18px">Unmatched bank items</h3>`+un.slice(0,20).map(x=>`<article class="finance-row error"><div><span>${esc(x.status||'UNMATCHED')}</span><strong>${money(x.amount)} · ${esc(x.description||'Statement transaction')}</strong><small>${esc(x.statement_date||x.transaction_date||'')} · Accountant review only if Auto Match cannot resolve it.</small></div></article>`).join(''):'<p class="admin-muted" style="margin-top:16px">No unmatched bank statement items.</p>'}
function renderCash(){const fm=new Map((data.financial_accounts||[]).map(x=>[x.id,x]));$('cash-count-list').innerHTML=(data.cash_counts||[]).slice(0,8).map(x=>`<div><span><b>${esc(fm.get(x.financial_account_id)?.name||'Cash')}</b> · ${esc(x.count_date||'')}</span><strong>${esc(x.status||'')}</strong><small>Expected ${money(x.expected_amount)} · Physical ${money(x.physical_amount)} · Difference ${money(x.difference)}</small></div>`).join('')||'<p class="admin-muted">No physical cash counts yet.</p>'}
function renderExceptions(){const exceptions=(data.exceptions||[]).filter(x=>x.status==='OPEN'),qErrors=(data.queue||[]).filter(x=>x.status==='ERROR').map(x=>({id:x.id,queue:true,exception_type:'AUTOMATION_ERROR',summary:x.last_error||'Operational Finance queue error',created_at:x.updated_at,source_id:x.event_key})),all=[...qErrors,...exceptions];$('finance-exception-list').innerHTML=all.length?all.map(x=>`<article class="finance-row ${x.queue?'error':''}"><div><span>${esc(x.exception_type||'REVIEW')}</span><strong>${esc(x.summary||'Needs review')}</strong><small>${esc(x.source_id||'')} · ${esc(fmt(x.created_at))}</small></div><div>${x.queue?`<button class="admin-outline-button finance-retry" data-id="${esc(x.id)}">RETRY</button>`:`<button class="admin-outline-button finance-resolve" data-id="${esc(x.id)}">RESOLVE</button>`}</div></article>`).join(''):'<p class="admin-muted">No open Finance Exceptions.</p>'}
function renderQueue(){$('finance-queue-list').innerHTML=(data.queue||[]).slice(0,40).map(x=>`<article class="finance-row"><div><span>${esc(x.status||'')}</span><strong>${esc(x.event_key||'')}</strong><small>Attempts ${Number(x.attempts)||0} · ${esc(fmt(x.created_at))}${x.last_error?` · ${esc(x.last_error)}`:''}</small></div><div>${x.invoice_id?`<a class="admin-outline-button" href="admin-invoices.html">INVOICE</a>`:''}${['ERROR','SKIPPED'].includes(x.status)?`<button class="admin-outline-button finance-retry" data-id="${esc(x.id)}">RETRY</button>`:''}</div></article>`).join('')||'<p class="admin-muted">No Operational Finance events yet.</p>'}

async function load(){const r=await api('/.netlify/functions/admin-finance');render(r.data)}
async function post(action,payload,msg){const r=await api('/.netlify/functions/admin-finance',{method:'POST',body:JSON.stringify({action,payload})});render(r.data);if(msg||r.result?.message)show(msg||r.result.message,true);return r}
function pickFile(){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept='application/pdf,image/jpeg,image/png,image/webp';i.onchange=()=>resolve(i.files?.[0]||null);i.click()})}
async function finishExpense(id,receiptStatus,file=null){if(receiptStatus==='MISSING'){file=file||await pickFile();if(!file)return;show('Uploading expense evidence…',true);await rawUpload(`/.netlify/functions/cal-expense-document-upload?expense_id=${encodeURIComponent(id)}`,file)}await post('FINALIZE_EXPENSE',{id},'Expense posted automatically. STEP 17 will process the accounting event.')}
async function finishBill(id,hasDoc,file=null){if(!hasDoc){file=file||await pickFile();if(!file)return;show('Uploading supplier evidence…',true);await rawUpload(`/.netlify/functions/admin-finance-supplier-document-upload?bill_id=${encodeURIComponent(id)}`,file)}await post('FINALIZE_BILL',{id},'Supplier bill posted. Accounts Payable and STEP 17 are updated automatically.')}

function bindRows(){
 document.querySelectorAll('.finance-retry').forEach(b=>b.onclick=()=>post('RETRY_QUEUE',{id:b.dataset.id}));document.querySelectorAll('.finance-resolve').forEach(b=>b.onclick=()=>{const note=prompt('Resolution note:','Reviewed by PLEASE Administration');if(note!==null)post('RESOLVE_EXCEPTION',{id:b.dataset.id,status:'RESOLVED',note})});
 document.querySelectorAll('.invoice-issue').forEach(b=>b.onclick=async()=>{if(!confirm('Issue this Draft invoice? This creates the normal STEP 17 accounting event.'))return;try{await api('/.netlify/functions/admin-invoice-action',{method:'POST',body:JSON.stringify({action:'ISSUE',invoice_id:b.dataset.id})});await load();show('Invoice issued. STEP 17 accounting event created.',true)}catch(e){show(e.message)}});
 document.querySelectorAll('.invoice-send').forEach(b=>b.onclick=async()=>{try{const r=await api('/.netlify/functions/admin-invoice-action',{method:'POST',body:JSON.stringify({action:'MARK_SENT',invoice_id:b.dataset.id})});await load();show(r.notification_sent?'Invoice sent to customer.':'Invoice status updated; email delivery reported an issue.',!!r.notification_sent)}catch(e){show(e.message)}});
 document.querySelectorAll('.invoice-pay').forEach(b=>b.onclick=async()=>{const amount=prompt(`Payment amount (remaining ${money(b.dataset.balance)}):`,Number(b.dataset.balance).toFixed(2));if(amount===null)return;const method=prompt('Payment method:','E-TRANSFER');if(method===null)return;const ref=prompt('Payment reference (optional):','')??'';try{await api('/.netlify/functions/admin-invoice-action',{method:'POST',body:JSON.stringify({action:'MARK_PAID',invoice_id:b.dataset.id,amount:Number(amount),payment_method:method,payment_reference:ref,note:'Payment recorded from PLEASE Operational Finance'})});await load();show('Customer payment recorded. A/R and accounting update automatically.',true)}catch(e){show(e.message)}});
 document.querySelectorAll('.expense-finish').forEach(b=>b.onclick=()=>finishExpense(b.dataset.id,b.dataset.receipt).catch(e=>show(e.message)));
 document.querySelectorAll('.bill-finish').forEach(b=>b.onclick=()=>finishBill(b.dataset.id,b.dataset.doc==='1').catch(e=>show(e.message)));
 document.querySelectorAll('.bill-pay').forEach(b=>b.onclick=async()=>{const amount=prompt(`Supplier payment amount (remaining ${money(b.dataset.balance)}):`,Number(b.dataset.balance).toFixed(2));if(amount===null)return;const fin=(data.financial_accounts||[]).find(x=>['BANK','CASH'].includes(String(x.financial_type).toUpperCase()))?.id||'';const selected=prompt(`Payment account id (copy from Finance if multiple):`,fin);if(selected===null)return;const ref=prompt('Payment reference (optional):','')??'';try{await post('PAY_SUPPLIER',{supplier_bill_id:b.dataset.id,financial_account_id:selected,amount:Number(amount),payment_date:today(),method:'PLEASE Admin',reference:ref})}catch(e){show(e.message)}});
 document.querySelectorAll('.bank-match').forEach(b=>b.onclick=()=>post('AUTO_MATCH_BANK',{reconciliation_id:b.dataset.id}).catch(e=>show(e.message)));
 document.querySelectorAll('.bank-close').forEach(b=>b.onclick=()=>{if(confirm('Close this bank reconciliation? Unmatched/control differences must already be resolved.'))post('CLOSE_BANK_RECONCILIATION',{reconciliation_id:b.dataset.id}).catch(e=>show(e.message))});
 document.querySelectorAll('.bank-import').forEach(b=>b.onclick=async()=>{const i=document.createElement('input');i.type='file';i.accept='text/csv,.csv';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;try{const rows=parseStatement(await f.text());await post('IMPORT_BANK_ROWS',{reconciliation_id:b.dataset.id,file_name:f.name,rows});await post('AUTO_MATCH_BANK',{reconciliation_id:b.dataset.id},`Imported ${rows.length} rows and ran Auto Match.`)}catch(e){show(e.message)}};i.click()});
}

$('qe-category').onchange=()=>setInventoryVisibility('qe');$('qb-category').onchange=()=>setInventoryVisibility('qb');
$('quick-expense-form').onsubmit=async e=>{e.preventDefault();const b=$('qe-save'),cat=categoryInfo($('qe-category').value),file=$('qe-file').files?.[0];if(!cat.review&&!file){show('Select the receipt/invoice so PLEASE can complete the controlled expense automatically.');return}b.disabled=true;b.textContent='PROCESSING…';try{const r=await post('QUICK_EXPENSE',{expense_date:$('qe-date').value,category:$('qe-category').value,description:$('qe-description').value,subtotal:Number($('qe-subtotal').value),financial_account_id:$('qe-account').value,gst_5:$('qe-gst').checked,reference:$('qe-reference').value,inventory_item_id:$('qe-item').value,inventory_location_id:$('qe-location').value});if(r.result?.kind!=='EXCEPTION'){await rawUpload(`/.netlify/functions/cal-expense-document-upload?expense_id=${encodeURIComponent(r.result.id)}`,file);await post('FINALIZE_EXPENSE',{id:r.result.id},'Expense recorded and posted automatically.')}$('qe-description').value='';$('qe-subtotal').value='';$('qe-reference').value='';$('qe-file').value=''}catch(e){show(`${e.message} If a Draft was already created, use “Finish / Post” in Recent Expenses.`)}finally{b.disabled=false;b.textContent='RECORD EXPENSE →'}};
$('quick-bill-form').onsubmit=async e=>{e.preventDefault();const b=$('qb-save'),cat=categoryInfo($('qb-category').value),file=$('qb-file').files?.[0];if(!cat.review&&!file){show('Select the supplier invoice/receipt so PLEASE can complete the controlled purchase automatically.');return}b.disabled=true;b.textContent='PROCESSING…';try{const r=await post('QUICK_BILL',{supplier_party_id:$('qb-supplier').value,supplier_invoice_number:$('qb-number').value,bill_date:$('qb-date').value,due_date:$('qb-due').value,description:$('qb-description').value,category:$('qb-category').value,subtotal:Number($('qb-subtotal').value),gst_5:$('qb-gst').checked,reference:$('qb-reference').value,inventory_item_id:$('qb-item').value,inventory_location_id:$('qb-location').value});if(r.result?.kind!=='EXCEPTION'){await rawUpload(`/.netlify/functions/admin-finance-supplier-document-upload?bill_id=${encodeURIComponent(r.result.id)}`,file);await post('FINALIZE_BILL',{id:r.result.id},'Supplier bill recorded and posted automatically.')}$('qb-number').value='';$('qb-description').value='';$('qb-subtotal').value='';$('qb-reference').value='';$('qb-file').value=''}catch(e){show(`${e.message} If a Draft was already created, use “Finish / Post” in Purchases & A/P.`)}finally{b.disabled=false;b.textContent='RECORD SUPPLIER BILL →'}};
$('add-supplier').onclick=async()=>{const name=prompt('Supplier legal/business name:','');if(!name)return;const email=prompt('Supplier email (optional):','')??'';const terms=prompt('Payment terms in days:','30');if(terms===null)return;try{await api('/.netlify/functions/cal-master-data',{method:'POST',body:JSON.stringify({action:'SAVE_PARTY',payload:{party_type:'ORGANIZATION',legal_name:name,email,payment_terms_days:Number(terms)||0,default_currency:'CAD',active:true,roles:['SUPPLIER']}})});await load();show('Supplier created and available in Purchases.',true)}catch(e){show(e.message)}};

function splitCsv(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){field+='"';i++}else q=!q}else if(c===','&&!q){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(x=>String(x).trim()!==''))rows.push(row);row=[]}else field+=c}row.push(field);if(row.some(x=>String(x).trim()!==''))rows.push(row);return rows}
function dateIso(v){v=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;let m=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;m=v.match(/^(\d{4})[\/](\d{1,2})[\/](\d{1,2})$/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;throw Error(`Unsupported statement date: ${v}`)}
function num(v){const n=Number(String(v??'').replace(/[$,()]/g,x=>x==='('?'-':x===')'?'':x).trim());return Number.isFinite(n)?n:0}
function parseStatement(text){const a=splitCsv(text);if(a.length<2)throw Error('CSV statement requires a header and at least one transaction.');const h=a[0].map(x=>String(x).trim().toLowerCase().replace(/[^a-z0-9]+/g,'')),ix=names=>{for(const n of names){const i=h.indexOf(n);if(i>=0)return i}return-1},di=ix(['date','transactiondate','posteddate']),desc=ix(['description','details','memo','transaction','name']),ai=ix(['amount','transactionamount']),debit=ix(['debit','withdrawal','withdrawals']),credit=ix(['credit','deposit','deposits']),eid=ix(['id','reference','transactionid']);if(di<0||ai<0&&(debit<0||credit<0))throw Error('CSV must contain Date + Amount, or Date + Debit + Credit.');const rows=a.slice(1).map((r,k)=>{const amount=ai>=0?num(r[ai]):num(r[credit])-Math.abs(num(r[debit]));return{date:dateIso(r[di]),description:desc>=0?String(r[desc]||'').trim():`Statement row ${k+2}`,amount,external_id:eid>=0?String(r[eid]||'').trim():null,currency:'CAD'}}).filter(x=>Math.abs(x.amount)>.004);if(!rows.length)throw Error('No non-zero transactions were found in the statement.');return rows}
$('bank-form').onsubmit=async e=>{e.preventDefault();const b=$('bank-start-btn'),file=$('bank-file').files?.[0];if(!file){show('Select the bank statement CSV so PLEASE can import and Auto Match it.');return}b.disabled=true;b.textContent='PROCESSING…';try{const rows=parseStatement(await file.text()),r=await post('START_BANK_RECONCILIATION',{financial_account_id:$('bank-account').value,period_start:$('bank-start').value,period_end:$('bank-end').value,statement_opening_balance:Number($('bank-opening').value),statement_ending_balance:Number($('bank-ending').value),statement_reference:$('bank-reference').value});await post('IMPORT_BANK_ROWS',{reconciliation_id:r.result.id,file_name:file.name,rows});await post('AUTO_MATCH_BANK',{reconciliation_id:r.result.id},`Bank statement imported (${rows.length} rows) and Auto Match completed.`);$('bank-file').value=''}catch(e){show(e.message)}finally{b.disabled=false;b.textContent='START & AUTO-MATCH →'}};
$('cash-form').onsubmit=async e=>{e.preventDefault();const b=$('cash-save');b.disabled=true;try{await post('RECORD_CASH_COUNT',{financial_account_id:$('cash-account').value,count_date:$('cash-date').value,physical_amount:Number($('cash-physical').value),reference:$('cash-reference').value});$('cash-physical').value='';$('cash-reference').value=''}catch(e){show(e.message)}finally{b.disabled=false}};
$('finance-settings-form').onsubmit=async e=>{e.preventDefault();try{await post('UPDATE_SETTINGS',{auto_create_invoice_draft:$('fs-draft').checked,auto_issue_invoice:$('fs-issue').checked,auto_email_invoice:$('fs-email').checked,default_gst_rate:Number($('fs-gst').value)})}catch(e){show(e.message)}};
$('finance-refresh').onclick=()=>load().then(()=>show('Finance refreshed.',true)).catch(e=>show(e.message));$('admin-signout').onclick=async()=>{try{await api('/.netlify/functions/admin-logout',{method:'POST',body:'{}'})}catch{}location.replace('admin-login.html')};
(async()=>{try{const s=await api('/.netlify/functions/admin-session');$('admin-name').textContent=s.user?.display_name||'PLEASE Administrator';$('admin-email').textContent=s.user?.email||'';$('admin-loading').remove();$('admin-app').hidden=false;const t=today();$('qe-date').value=t;$('qb-date').value=t;$('cash-date').value=t;$('bank-end').value=t;const d=new Date(`${t}T12:00:00Z`);d.setUTCDate(1);$('bank-start').value=d.toISOString().slice(0,10);await load()}catch(e){if($('admin-loading'))$('admin-loading').textContent=e.message}})();
})();
