(()=>{
 const loading=document.getElementById('developer-loading'),app=document.getElementById('developer-app'),tbody=document.getElementById('developer-applications-body'),drawer=document.getElementById('developer-drawer'),backdrop=document.getElementById('developer-backdrop'),actions=document.getElementById('developer-actions'),alertBox=document.getElementById('developer-alert');let rows=[],selected=null,detail=null;
 const labels={REFERRED_TO_DEVELOPER:'Referred',ONBOARDING:'Onboarding',APPROVED:'Approved',ACTIVATED:'Activated'};const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 function show(msg,type='error'){alertBox.hidden=false;alertBox.className=`form-alert ${type}`;alertBox.textContent=msg;}
 async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',headers:{...(opt.body?{'content-type':'application/json'}:{}),...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace('developer-login.html');throw new Error('Session expired.');}if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
 function fmt(v){if(!v)return'—';return new Intl.DateTimeFormat('en-CA',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Edmonton'}).format(new Date(v));}
 function badge(s){return `<span class="status-badge status-${String(s).toLowerCase().replaceAll('_','-')}">${esc(labels[s]||s)}</span>`;}
 async function session(){const d=await api('/.netlify/functions/developer-session');document.getElementById('developer-name').textContent=d.user.display_name;document.getElementById('developer-email').textContent=d.user.email;}
 async function load(){const d=await api('/.netlify/functions/developer-applications');rows=d.applications||[];render();stats();if(selected){const r=rows.find(x=>x.id===selected.id);if(r)await open(r,false);}}
 function stats(){for(const [id,s] of [['dev-stat-referred','REFERRED_TO_DEVELOPER'],['dev-stat-onboarding','ONBOARDING'],['dev-stat-approved','APPROVED'],['dev-stat-activated','ACTIVATED']])document.getElementById(id).textContent=rows.filter(x=>x.status===s).length;document.getElementById('developer-queue-count').textContent=rows.filter(x=>x.status!=='ACTIVATED').length;}
 function render(){tbody.innerHTML=rows.map(r=>`<tr><td><strong class="admin-reference">${esc(r.reference)}</strong></td><td><strong>${esc(r.full_name)}</strong><small>${esc(r.company_name||r.email)}</small></td><td>${esc(r.service_trade||'—')}</td><td>${esc(fmt(r.referred_to_developer_at))}</td><td>${badge(r.status)}</td><td><button class="admin-row-button" data-id="${r.id}">Open</button></td></tr>`).join('');tbody.querySelectorAll('button').forEach(b=>b.onclick=()=>open(rows.find(r=>r.id===b.dataset.id)));}
 function availabilityUI(existing=[]){const map=new Map(existing.map(x=>[Number(x.weekday),x]));document.getElementById('dev-availability').innerHTML=weekdays.map((day,i)=>{const x=map.get(i+1);return `<div class="developer-availability-row"><label><input type="checkbox" data-day="${i+1}" class="dev-day-active" ${x?'checked':''}> ${day}</label><input type="time" class="dev-day-start" data-day="${i+1}" value="${x?String(x.start_time).slice(0,5):'08:00'}"><span>to</span><input type="time" class="dev-day-end" data-day="${i+1}" value="${x?String(x.end_time).slice(0,5):'17:00'}"></div>`}).join('');}
 function servicesUI(services,assigned){const ids=new Set((assigned||[]).filter(x=>x.active).map(x=>x.service_id));document.getElementById('dev-services').innerHTML=(services||[]).map(s=>`<label><input type="checkbox" class="dev-service" value="${s.id}" ${ids.has(s.id)?'checked':''}> ${esc(s.name)}</label>`).join('');}
 function historyUI(h){document.getElementById('dev-history').innerHTML=(h||[]).map(x=>`<div class="admin-history-row"><span>${esc(fmt(x.created_at))}</span><strong>${esc(x.old_status||'START')} → ${esc(x.new_status)}</strong>${x.note?`<p>${esc(x.note)}</p>`:''}</div>`).join('')||'<span class="admin-muted">No history.</span>';}
 function fill(d){detail=d;const a=d.application,p=d.provider||{};document.getElementById('dev-detail-reference').textContent=a.reference;document.getElementById('dev-detail-name').textContent=a.full_name;const st=document.getElementById('dev-detail-status');st.className=`status-badge status-${a.status.toLowerCase().replaceAll('_','-')}`;st.textContent=labels[a.status]||a.status;document.getElementById('dev-summary').innerHTML=[['Company',a.company_name||'—'],['Application Service',a.service_trade||'—'],['Experience',`${a.years_experience??'—'} yrs`],['Referred',fmt(a.referred_to_developer_at)]].map(([l,v])=>`<div><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('');
 const set=(id,v)=>document.getElementById(id).value=v??'';set('dev-display-name',p.display_name||a.full_name);set('dev-company-name',p.company_name??a.company_name??'');set('dev-public-title',p.public_title||a.service_trade||'');set('dev-service-area',p.service_area||a.service_area||'');set('dev-primary-email',p.primary_email||a.email||'');set('dev-primary-phone',p.primary_phone||a.phone||'');set('dev-short-bio',p.short_bio||a.experience_details||'');set('dev-technical-description',p.technical_description||'');document.getElementById('dev-licensed').checked=p.id?!!p.licensed_certified:!!a.licensed_certified;document.getElementById('dev-insured').checked=p.id?!!p.insured:!!a.insured;set('dev-login-email',d.credential?.email||p.primary_email||a.email||'');set('dev-login-password','');document.getElementById('dev-credential-state').textContent=d.credential?`Credential active for ${d.credential.email}. Last password update: ${fmt(d.credential.password_changed_at)}.`:'No provider portal credential has been created yet.';servicesUI(d.services,d.provider_services);availabilityUI(d.availability);historyUI(d.history);renderActions(a,p);}
 async function open(row,showDrawer=true){selected=row;const d=await api(`/.netlify/functions/developer-applications?id=${encodeURIComponent(row.id)}`);fill(d);if(showDrawer){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.classList.add('admin-drawer-open');}}
 function payload(){const service_ids=[...document.querySelectorAll('.dev-service:checked')].map(x=>x.value);const availability=[...document.querySelectorAll('.dev-day-active:checked')].map(x=>{const day=x.dataset.day;return{weekday:Number(day),start_time:document.querySelector(`.dev-day-start[data-day="${day}"]`).value,end_time:document.querySelector(`.dev-day-end[data-day="${day}"]`).value,active:true}});const password=document.getElementById('dev-login-password').value;const p={display_name:document.getElementById('dev-display-name').value,company_name:document.getElementById('dev-company-name').value,public_title:document.getElementById('dev-public-title').value,service_area:document.getElementById('dev-service-area').value,primary_email:document.getElementById('dev-primary-email').value,primary_phone:document.getElementById('dev-primary-phone').value,short_bio:document.getElementById('dev-short-bio').value,technical_description:document.getElementById('dev-technical-description').value,licensed_certified:document.getElementById('dev-licensed').checked,insured:document.getElementById('dev-insured').checked,service_ids,availability};if(password)p.credential={email:document.getElementById('dev-login-email').value,password,display_name:document.getElementById('dev-display-name').value};return p;}
 async function action(name,p={}){actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await api('/.netlify/functions/developer-onboarding-action',{method:'POST',body:JSON.stringify({application_id:selected.id,action:name,payload:p})});show('Developer workflow updated.','success');await load();}catch(e){show(e.message);if(detail)renderActions(detail.application,detail.provider||{});}}
 function add(label,cls,fn){const b=document.createElement('button');b.className=cls;b.textContent=label;b.onclick=fn;actions.appendChild(b);}
 function renderActions(a,p){actions.innerHTML='';if(a.status==='REFERRED_TO_DEVELOPER'){add('START ONBOARDING →','btn primary',()=>action('START_ONBOARDING'));return;}if(a.status==='ONBOARDING'){add('SAVE ONBOARDING','admin-outline-button',()=>action('SAVE_ONBOARDING',payload()));add('APPROVE PROVIDER →','btn primary',()=>{if(confirm('Approve this provider? This moves the onboarding workflow to APPROVED.'))action('APPROVE');});return;}if(a.status==='APPROVED'){add('SAVE CHANGES','admin-outline-button',()=>action('SAVE_ONBOARDING',payload()));const wrap=document.createElement('label');wrap.className='developer-publish-toggle';wrap.innerHTML='<input id="dev-publish" type="checkbox"> Publish landing on activation';actions.appendChild(wrap);add('ACTIVATE PROVIDER →','btn primary',()=>{if(confirm('Activate this provider? The provider account will become operational.'))action('ACTIVATE',{public_visible:document.getElementById('dev-publish')?.checked||false});});return;}const span=document.createElement('span');span.className='admin-muted';span.textContent=a.status==='ACTIVATED'?(p.public_visible?'Provider is active and public landing is enabled.':'Provider is active; public landing remains hidden.'):'No developer action available.';actions.appendChild(span);}
 document.getElementById('developer-refresh').onclick=()=>load().catch(e=>show(e.message));document.getElementById('developer-signout').onclick=async()=>{try{await api('/.netlify/functions/admin-logout',{method:'POST',body:'{}'});}catch(_){}location.replace('developer-login.html');};document.getElementById('developer-drawer-close').onclick=()=>{drawer.classList.remove('open');backdrop.hidden=true;document.body.classList.remove('admin-drawer-open');};backdrop.onclick=document.getElementById('developer-drawer-close').onclick;
 (async()=>{try{await session();loading.hidden=true;loading.remove();app.hidden=false;await load();}catch(e){loading.textContent=e.message||'Unable to load developer portal.';}})();
})();
