const crypto = require('crypto');
const COOKIE_NAME='please_provider_session';
const SESSION_SECONDS=12*60*60;
function json(statusCode,payload,extraHeaders={}){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, max-age=0','x-content-type-options':'nosniff','referrer-policy':'no-referrer',...extraHeaders},body:JSON.stringify(payload)}}
function config(){const url=process.env.PLEASE_SUPABASE_URL,secret=process.env.PLEASE_SUPABASE_SECRET_KEY;if(!url||!secret)throw new Error('Provider backend is not configured.');return{url:url.replace(/\/$/,''),secret};}
async function sbFetch(path,options={}){const{url,secret}=config();return fetch(`${url}${path}`,{...options,headers:{apikey:secret,'content-type':'application/json',...(options.headers||{})}})}
async function sbJson(path,options={}){const r=await sbFetch(path,options),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok){const e=new Error(d?.message||d?.error||d?.hint||`Supabase request failed (${r.status})`);e.status=r.status;throw e;}return d;}
function parseCookies(h=''){return String(h).split(';').reduce((o,x)=>{const i=x.indexOf('=');if(i>-1)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim());return o},{})}
const tokenHash=t=>crypto.createHash('sha256').update(t).digest('hex');
const newToken=()=>crypto.randomBytes(32).toString('base64url');
const sessionCookie=(t,maxAge=SESSION_SECONDS)=>`${COOKIE_NAME}=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
const clearCookie=()=>`${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;
const requestIp=e=>String(e.headers['x-nf-client-connection-ip']||e.headers['x-forwarded-for']||'').split(',')[0].trim().slice(0,120);
const requestUserAgent=e=>String(e.headers['user-agent']||'').slice(0,500);
function sameOrigin(e){const origin=e.headers.origin;if(!origin)return true;const host=e.headers.host;if(!host)return false;try{return new URL(origin).host===host}catch{return false}}
async function createSession(user,event){const token=newToken(),hash=tokenHash(token),expires=new Date(Date.now()+SESSION_SECONDS*1000).toISOString();await sbJson('/rest/v1/provider_portal_sessions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({provider_user_id:user.id,token_hash:hash,expires_at:expires,ip_address:requestIp(event)||null,user_agent:requestUserAgent(event)||null})});return{token,expires};}
async function getSession(event){const cookies=parseCookies(event.headers.cookie||event.headers.Cookie||''),token=cookies[COOKIE_NAME];if(!token)return null;const hash=tokenHash(token),now=encodeURIComponent(new Date().toISOString());const sessions=await sbJson(`/rest/v1/provider_portal_sessions?select=id,provider_user_id,expires_at&token_hash=eq.${hash}&revoked_at=is.null&expires_at=gt.${now}&limit=1`),session=Array.isArray(sessions)?sessions[0]:null;if(!session)return null;const users=await sbJson(`/rest/v1/provider_portal_users?select=id,provider_id,email,display_name,active&id=eq.${session.provider_user_id}&active=eq.true&limit=1`),user=Array.isArray(users)?users[0]:null;if(!user)return null;const providers=await sbJson(`/rest/v1/providers?select=id,reference,display_name,status&id=eq.${encodeURIComponent(user.provider_id)}&limit=1`).catch(()=>[]),provider=Array.isArray(providers)?providers[0]:null;if(!provider||provider.status!=='ACTIVE')return null;sbFetch(`/rest/v1/provider_portal_sessions?id=eq.${session.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:new Date().toISOString()})}).catch(()=>{});return{session,user,provider,tokenHash:hash};}
async function requireProvider(event){const auth=await getSession(event);if(!auth){const e=new Error('Unauthorized');e.status=401;throw e;}return auth;}
async function revokeSession(auth){if(!auth?.session?.id)return;await sbJson(`/rest/v1/provider_portal_sessions?id=eq.${auth.session.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});}
module.exports={COOKIE_NAME,SESSION_SECONDS,json,sbFetch,sbJson,sameOrigin,requestIp,requestUserAgent,sessionCookie,clearCookie,createSession,getSession,requireProvider,revokeSession};
