const fs=require('fs'),crypto=require('crypto');
let fail=0;const pass=m=>console.log('PASS',m),bad=m=>{fail++;console.error('FAIL',m)};
const read=p=>fs.readFileSync(p,'utf8');
const eq=(a,b,m)=>a===b?pass(m):bad(m);
const has=(s,re,m)=>re.test(s)?pass(m):bad(m);
const not=(s,re,m)=>!re.test(s)?pass(m):bad(m);
const lib=read('netlify/functions/_cal-accounting-lib.js');
const rootLib=read('_cal-accounting-lib.js');
const dash=read('netlify/functions/cal-dashboard-data.js');
const rootDash=read('cal-dashboard-data.js');
const sql=read('supabase/STEP18_2_1_AR_PAYMENT_INTEGRITY_FIX.sql');
const verify=read('supabase/STEP18_2_1_VERIFY.sql');
eq(lib,rootLib,'CAL accounting library mirrors remain identical');
eq(dash,rootDash,'CAL dashboard function mirrors remain identical');
has(lib,/async function accountingPaidTotal\(accountingInvoiceId\)/,'Payment-derived paid total helper exists');
has(lib,/accounting_payments\?select=amount&invoice_id=eq\./,'Paid total is derived from accounting_payments');
not(lib,/paid_total:MONEY\(inv\.amount_paid\)/,'Invoice mirror no longer copies PLEASE amount_paid into paid_total');
not(lib,/Number\(ai\?\.\[0\]\?\.paid_total\|\|0\)\+Number\(tx\.amount\|\|0\)/,'Payment mirror no longer incrementally adds to cached paid_total');
has(lib,/const paid=await accountingPaidTotal\(accountingInvoiceId\)/,'Payment mirror recomputes paid_total idempotently');
has(dash,/const paidByInvoice=new Map\(\)/,'A/R read model builds payment-derived totals');
has(dash,/paid:MONEY\(paidByInvoice\.get\(x\.id\)\|\|0\)/,'A/R display uses payment history instead of cached paid_total');
has(sql,/update public\.accounting_invoices ai[\s\S]*set paid_total=pt\.payment_total/,'Repair SQL only recalculates accounting invoice paid cache');
not(sql,/update public\.invoices|update public\.payment_transactions|accounting_journal_entries|accounting_journal_lines/i,'Repair SQL does not touch operational payments or journals');
has(verify,/A\/R mirror paid_total equals payment history/,'Verification checks A/R mirror integrity');
has(verify,/No duplicate PLEASE payment mirror references/,'Verification checks payment mirror idempotency');
process.exitCode=fail?1:0;
