const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
function ok(c,m){if(!c){console.error('FAIL:',m);process.exitCode=1}else console.log('PASS:',m)}
const adminLib=read('netlify/functions/_admin-lib.js');
const notify=read('netlify/functions/_notify-lib.js');
const calData=read('netlify/functions/admin-calendar-data.js');
const calJs=read('js/admin-calendar.js');
const calHtml=read('admin-calendar.html');
const reqAction=read('netlify/functions/admin-service-request-action.js');
const jobAction=read('netlify/functions/admin-job-action.js');
ok(adminLib.includes('PLEASE_SUPABASE_FETCH_TIMEOUT_MS')&&adminLib.includes("err.status = 504"),'Supabase calls are bounded so gateway stalls become controlled 504 responses');
ok(notify.includes('PLEASE_EMAIL_FETCH_TIMEOUT_MS')&&notify.includes('AbortController'),'Resend delivery has a bounded network timeout');
ok(calData.includes('all independent calendar reads execute in one parallel wave')&&calData.includes("optional('providers'")&&calData.includes("optional('provider-rates'"),'Master Calendar parallelizes and isolates all independent catalog/operational reads');
ok(fs.existsSync(path.join(root,'netlify/functions/admin-assignment-form-data.js')),'Assignment drawer has an independent lightweight catalog endpoint');
ok(calJs.includes("admin-assignment-form-data")&&calJs.includes('ensureAssignmentCatalog(true)'),'Service Request assignment retries its catalog independently of calendar background data');
ok(calJs.includes('Calendar refresh failed after the Job was already created')&&(calJs.includes('assignment was sent, but the calendar refresh failed')||calJs.includes('Calendar refresh failed after the reassignment was already saved')),'Post-create/reassignment refresh failure can no longer masquerade as transaction failure');
ok(calJs.includes('You can still continue assigning the selected Service Request'),'A calendar background error no longer blocks the Service Request assignment drawer');
ok(reqAction.includes('Promise.all([')&&reqAction.includes('recordHistory({requestId:current.id')&&reqAction.includes('notify.send({to:out.email'),'Service Request history and email run in parallel after the state change');
ok(jobAction.includes('const validations=await Promise.all')&&jobAction.includes('const results=await Promise.all([...postTasks,...noticeTasks])'),'Multi-provider validation and post-create work are parallelized to stay within function runtime');
ok(/js\/admin-calendar\.js\?v=(?:15\.8\.6\.[2-9](?:\.\d+)*|15\.(?:9|\d{2,}))/.test(calHtml),'Master Calendar cache-busts STEP 15.8.6.2 or newer runtime recovery JavaScript');
ok(!fs.existsSync(path.join(root,'supabase/STEP15_8_6_2.sql')),'STEP 15.8.6.2 requires no database migration');
if(process.exitCode)process.exit(process.exitCode);else console.log('STEP 15.8.6.2 gateway timeout recovery audit completed successfully.');
