const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
function pass(name,cond){assert.ok(cond,name);console.log('PASS:',name)}
const sql=read('supabase/STEP17_NATIVE_ACCOUNTING_ENGINE.sql');
const lib=read('netlify/functions/_cal-accounting-lib.js');
const worker=read('netlify/functions/cal-accounting-worker.js');
const recovery=read('netlify/functions/cal-accounting-recovery.js');
const syncCompat=read('netlify/functions/cal-accounting-sync.js');
const invoice=read('netlify/functions/admin-invoice-action.js');
const provider=read('netlify/functions/admin-provider-payment-action.js');
const stripe=read('netlify/functions/stripe-webhook.js');
const dashboard=read('cal/dashboard.html');
const calApp=read('cal/js/app.js');
const dashApi=read('netlify/functions/cal-dashboard-data.js');
const toml=read('netlify.toml');
const doc=read('STEP17_NATIVE_ACCOUNTING_ENGINE.md');
pass('STEP 17 creates separate immutable domain event ledger',sql.includes('please_domain_events')&&sql.includes('accounting_prevent_domain_event_mutation'));
pass('Financial source triggers enqueue durable accounting events inside PostgreSQL',sql.includes('accounting_invoice_event_trigger')&&sql.includes('accounting_payment_event_trigger')&&sql.includes('accounting_provider_payment_event_trigger')&&sql.includes('accounting_enqueue_event'));
pass('Queue lifecycle includes processing, retry and dead letter states',sql.includes("'PROCESSING'")&&sql.includes("'RETRY'")&&sql.includes("'DEAD_LETTER'"));
pass('STEP 16 ERROR rows remain rollout-compatible and are claimable',sql.includes("'DEAD_LETTER','ERROR'")&&sql.includes("status in ('PENDING','RETRY','ERROR')"));
pass('Queue claims are concurrency safe',sql.includes('FOR UPDATE SKIP LOCKED')&&sql.includes('accounting_claim_outbox'));
pass('Journal posting is atomic inside PostgreSQL',sql.includes('accounting_post_event_journal')&&lib.includes('/rest/v1/rpc/accounting_post_event_journal')&&!lib.includes("/rest/v1/accounting_journal_lines',{method:'POST'"));
pass('Posted journal lines are immutable',sql.includes('accounting_prevent_posted_journal_line_mutation'));
pass('Worker is scheduled automatically',toml.includes('[functions."cal-accounting-worker"]')&&toml.includes('schedule = "* * * * *"')&&worker.includes('runWorker'));
pass('Accounting worker uses retry and Dead Letter controls',lib.includes('CAL_ACCOUNTING_MAX_ATTEMPTS')&&lib.includes("status:dead?'DEAD_LETTER':'RETRY'"));
pass('Dead Letter recovery resets retry budget',sql.includes("set status='RETRY',attempts=0")&&sql.includes("public.please_accounting_outbox.status in ('RETRY','DEAD_LETTER')"));
pass('Posting rules table is actively read by worker',lib.includes('async function postingRule')&&lib.includes('accounting_posting_rules'));
pass('Financial action handlers no longer post CAL synchronously',!invoice.includes('accounting.handle')&&!provider.includes('accounting.handle')&&!stripe.includes('accounting.handle'));
pass('Issued invoice financial edits are locked',invoice.includes("inv.status!=='DRAFT'")&&read('js/admin-invoices.js').includes("editable=inv.status==='DRAFT'"));
pass('Operational responses identify event-driven accounting without waiting for posting',invoice.includes("accounting_mode:'EVENT_DRIVEN'")&&provider.includes("accounting_mode:'EVENT_DRIVEN'"));
pass('Stripe still stores fee and net reconciliation details',stripe.includes('stripe_fee_amount')&&stripe.includes('stripe_net_amount'));
pass('Stripe webhook id is stored structurally when STEP 17 schema is available',sql.includes('stripe_webhook_event_id')&&stripe.includes('stripe_webhook_event_id:evt.id'));
pass('CAL dashboard has no user-facing Sync button',!dashboard.includes('syncAccounting')&&!dashboard.includes('Sync PLEASE Accounting')&&!calApp.includes("remoteJson('/cal-accounting-sync'"));
pass('CAL dashboard exposes native engine health',dashboard.includes('Accounting Engine')&&dashboard.includes('engineDeadLetter')&&dashboard.includes('engineOldestPending')&&dashApi.includes('accounting_engine_health'));
pass('Engine health degrades on stale pending events',sql.includes("oldest_pending_at < now()-interval '5 minutes'"));
pass('Recovery remains protected and exceptional',recovery.includes('requireAdmin')&&recovery.includes('accounting.reconcile')&&syncCompat.includes('deprecated:true'));
pass('Posted journals are immutable and corrections use reversal entries',sql.includes('accounting_prevent_posted_journal_mutation')&&sql.includes('accounting_reverse_journal_entry'));
pass('Event versioning, hashes and correlation/causation are present',sql.includes('event_version')&&sql.includes('payload_hash')&&sql.includes('correlation_id')&&sql.includes('causation_id'));
pass('Refunds are not auto-posted without a dedicated source document',sql.includes('PAYMENT_REFUNDED_REQUIRES_ACCOUNTING_REVIEW')&&doc.includes('does **not** invent accounting treatment'));
pass('STEP 17 documentation defines safe deployment order and rollback principle',doc.includes('Deployment order')&&doc.includes('Rollback principle')&&doc.includes('No accounting side effect without a durable event'));
console.log('STEP 17 Native Accounting Engine static audit completed successfully.');
