const path=require('path');
const crypto=require('crypto');
const root=path.resolve(__dirname,'../netlify/functions');
const calls=[];
const INVOICE_ID='11111111-1111-1111-1111-111111111111';
const invoice={id:INVOICE_ID,invoice_number:'PLS-INV-1593',public_token:'abc123abc123abc123abc123abc123',client_name:'Customer',client_email:'customer@example.com',total_amount:1.05,amount_paid:0,currency:'CAD',status:'SENT',payment_status:'PENDING',stripe_checkout_session_id:'cs_live_old'};
const fakeLib={json:(statusCode,payload,headers={})=>({statusCode,headers,body:JSON.stringify(payload)}),sbJson:async(url,opt={})=>{calls.push({url,method:opt.method||'GET',body:opt.body?JSON.parse(opt.body):null,headers:opt.headers||{}});if(url.startsWith('/rest/v1/invoices?id=eq.')&&opt.method==='PATCH')return null;if(url==='/rest/v1/payment_transactions')return null;if(url==='/rest/v1/invoice_status_history')return null;throw new Error(`Unexpected ${opt.method||'GET'} ${url}`);}};
const fakeNotify={baseUrl:()=> 'https://pleaseservice.ca',send:async()=>({sent:true}),sendAdmins:async()=>({sent:true})};
const fakePay={MONEY:n=>Math.round((Number(n)||0)*100)/100,paid:inv=>inv.payment_status==='PAID',balance:inv=>Math.round((Number(inv.total_amount)-Number(inv.amount_paid||0))*100)/100,invoiceById:async id=>id===INVOICE_ID?invoice:null,invoiceBySession:async()=>null,addHistory:async()=>{},stripePaymentDetails:async()=>({payment_intent:'pi_live_123',charge_id:'ch_live_123',receipt_url:'https://pay.stripe.com/receipts/test',fee_amount:.33,net_amount:.72}),detailsNote:({eventId,session,details})=>`Stripe webhook event: ${eventId}\nCheckout Session: ${session.id}\nPayment Intent: ${details.payment_intent}\nCharge ID: ${details.charge_id}\nReceipt URL: ${details.receipt_url}\nStripe fee: ${details.fee_amount.toFixed(2)} CAD\nNet after Stripe fee: ${details.net_amount.toFixed(2)} CAD`};
require.cache[require.resolve(path.join(root,'_admin-lib.js'))]={exports:fakeLib};
require.cache[require.resolve(path.join(root,'_notify-lib.js'))]={exports:fakeNotify};
require.cache[require.resolve(path.join(root,'_stripe-payment-lib.js'))]={exports:fakePay};
process.env.STRIPE_WEBHOOK_SECRET='whsec_test_secret';
const handler=require(path.join(root,'stripe-webhook.js')).handler;
function sign(raw){const ts=Math.floor(Date.now()/1000);const sig=crypto.createHmac('sha256',process.env.STRIPE_WEBHOOK_SECRET).update(`${ts}.${raw}`,'utf8').digest('hex');return `t=${ts},v1=${sig}`}
(async()=>{const evt={id:'evt_live_123',type:'checkout.session.completed',data:{object:{id:'cs_live_new',payment_status:'paid',amount_total:105,currency:'cad',payment_intent:'pi_live_123',metadata:{invoice_id:INVOICE_ID,invoice_number:'PLS-INV-1593'},customer_email:'customer@example.com'}}};const raw=JSON.stringify(evt);const res=await handler({httpMethod:'POST',headers:{'stripe-signature':sign(raw)},body:raw,isBase64Encoded:false});if(res.statusCode!==200){console.error(res);process.exit(1)}const patch=calls.find(c=>c.method==='PATCH'&&c.url.startsWith('/rest/v1/invoices?id=eq.'));if(!patch||patch.body.payment_status!=='PAID'||patch.body.status!=='PAID'||patch.body.stripe_checkout_session_id!=='cs_live_new'||patch.body.stripe_payment_intent_id!=='pi_live_123')process.exit(2);const tx=calls.find(c=>c.url==='/rest/v1/payment_transactions');if(!tx||tx.body.amount!==1.05||tx.body.provider!=='STRIPE'||!tx.body.note.includes('Charge ID: ch_live_123')||!tx.body.note.includes('Net after Stripe fee'))process.exit(3);const hist=calls.find(c=>c.url==='/rest/v1/invoice_status_history');if(!hist||hist.body.source!=='STRIPE'||hist.headers.Prefer!=='return=minimal')process.exit(4);console.log('STEP 15.9.3 STRIPE WEBHOOK RUNTIME PASS');})().catch(e=>{console.error(e);process.exit(10)});
