const path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'../netlify/functions'),calls=[];
const IDs={claim:'11111111-1111-1111-1111-111111111111',line:'22222222-2222-2222-2222-222222222222',acct:'33333333-3333-3333-3333-333333333333',tax:'44444444-4444-4444-4444-444444444444',fin:'55555555-5555-5555-5555-555555555555',bank:'66666666-6666-6666-6666-666666666666',reimb:'77777777-7777-7777-7777-777777777777'};let evt=0;
const fake={sbJson:async(url,opt={})=>{const body=opt.body?JSON.parse(opt.body):null;calls.push({url,method:opt.method||'GET',body});
if(url.includes('/accounting_posting_rules?')&&url.includes('EXPENSE_POSTED'))return[{debit_account_code:'5400',credit_account_code:'1000',tax_account_code:'1200',configuration_json:{qst_recoverable_account:'1210',reimbursement_payable_account:'2020'}}];
if(url.includes('/accounting_posting_rules?')&&url.includes('EXPENSE_REIMBURSEMENT_PAID'))return[{debit_account_code:'2020',credit_account_code:'1000',configuration_json:{}}];
if(url.startsWith(`/rest/v1/accounting_expense_claims?id=eq.${IDs.claim}`))return[{id:IDs.claim,expense_number:'EXP-001001',expense_date:'2026-09-07',posting_date:'2026-09-07',payment_mode:'COMPANY_PAID',financial_account_id:IDs.fin,status:'PAID',subtotal:100,tax_total:5,recoverable_tax:5,nonrecoverable_tax:0,total:105}];
if(url.startsWith('/rest/v1/accounting_expense_claim_lines?'))return[{id:IDs.line,expense_claim_id:IDs.claim,description:'Fuel',classification:'EXPENSE',posting_account_id:IDs.acct,tax_code_id:IDs.tax,line_subtotal:100,tax_amount:5,recoverable_tax:5,nonrecoverable_tax:0,line_total:105}];
if(url.startsWith(`/rest/v1/accounting_expense_reimbursements?id=eq.${IDs.reimb}`))return[{id:IDs.reimb,reimbursement_number:'ER-001001',expense_claim_id:IDs.claim,financial_account_id:IDs.fin,payment_date:'2026-09-08',amount:105,status:'PAID'}];
if(url.startsWith(`/rest/v1/accounting_financial_accounts?id=eq.${IDs.fin}`))return[{id:IDs.fin,name:'Operating Bank',financial_type:'BANK',gl_account_id:IDs.bank,active:true}];
if(url.startsWith(`/rest/v1/accounting_accounts?id=eq.${IDs.acct}`))return[{id:IDs.acct,code:'5100',name:'Fuel & Vehicle',account_type:'EXPENSE',active:true}];
if(url.startsWith(`/rest/v1/accounting_accounts?id=eq.${IDs.bank}`))return[{id:IDs.bank,code:'1000',name:'Operating Bank',account_type:'ASSET',active:true}];
if(url.startsWith(`/rest/v1/accounting_tax_codes?id=eq.${IDs.tax}`))return[{id:IDs.tax,code:'AB-GST',tax_kind:'GST',federal_rate:5,provincial_rate:0,recoverable_default:true}];
if(url.startsWith(`/rest/v1/please_accounting_outbox?event_key=eq.${encodeURIComponent('PLEASE:EXPENSE_POSTED:'+IDs.claim)}`))return[{id:'dep',status:'POSTED'}];
if(url.startsWith('/rest/v1/accounting_external_events?'))return[];if(url==='/rest/v1/accounting_external_events'&&opt.method==='POST')return[{id:`evt-${++evt}`,posting_status:'PENDING'}];if(url.startsWith('/rest/v1/accounting_external_events?id=eq.')&&opt.method==='PATCH')return null;if(url.startsWith('/rest/v1/please_accounting_outbox?id=eq.')&&opt.method==='PATCH')return null;
if(url.startsWith('/rest/v1/accounting_accounts?code=eq.')){const code=decodeURIComponent((url.match(/code=eq\.([^&]+)/)||[])[1]||'0000');return[{id:`acc-${code}`,code}]}
if(url==='/rest/v1/rpc/accounting_post_event_journal')return[{accounting_post_event_journal:`journal-${evt}`}];throw new Error(`Unexpected ${opt.method||'GET'} ${url}`)}};
require.cache[require.resolve(path.join(root,'_admin-lib.js'))]={exports:fake};const acct=require(path.join(root,'_cal-accounting-lib.js'));
(async()=>{const row={id:'o1',event_key:`PLEASE:EXPENSE_POSTED:${IDs.claim}`,event_type:'EXPENSE_POSTED',event_version:1,source_record_id:IDs.claim,source_reference:'EXP-001001',occurred_at:'2026-09-07T18:00:00Z',payload_json:{expense_claim:{id:IDs.claim,expense_number:'EXP-001001',posting_date:'2026-09-07',payment_mode:'COMPANY_PAID',financial_account_id:IDs.fin,status:'PAID',total:105},lines:[{description:'Fuel',posting_account_id:IDs.acct,tax_code_id:IDs.tax,line_subtotal:100,tax_amount:5,recoverable_tax:5,nonrecoverable_tax:0,line_total:105}]},attempts:1};const r=await acct.processOutboxEvent(row,{workerId:'test'});assert.strictEqual(r.status,'POSTED');const post=calls.find(c=>c.url==='/rest/v1/rpc/accounting_post_event_journal'&&c.body?.p_memo?.includes('Expense posted'));assert.deepStrictEqual(post.body.p_lines.map(x=>({code:x.code,debit:x.debit,credit:x.credit})),[{code:'5100',debit:100,credit:0},{code:'1200',debit:5,credit:0},{code:'1000',debit:0,credit:105}]);
const rr={id:'o2',event_key:`PLEASE:EXPENSE_REIMBURSEMENT_PAID:${IDs.reimb}`,event_type:'EXPENSE_REIMBURSEMENT_PAID',event_version:1,source_record_id:IDs.reimb,source_reference:'ER-001001',occurred_at:'2026-09-08T18:00:00Z',payload_json:{expense_reimbursement:{id:IDs.reimb,reimbursement_number:'ER-001001',expense_claim_id:IDs.claim,financial_account_id:IDs.fin,payment_date:'2026-09-08',amount:105,status:'PAID'}},attempts:1};const r2=await acct.processOutboxEvent(rr,{workerId:'test'});assert.strictEqual(r2.status,'POSTED');const p2=calls.find(c=>c.url==='/rest/v1/rpc/accounting_post_event_journal'&&c.body?.p_memo?.includes('Expense reimbursement'));assert.deepStrictEqual(p2.body.p_lines.map(x=>({code:x.code,debit:x.debit,credit:x.credit})),[{code:'2020',debit:105,credit:0},{code:'1000',debit:0,credit:105}]);console.log('STEP 18.4 EXPENSE WORKER RUNTIME PASS')})().catch(e=>{console.error(e);process.exit(1)});
