const path=require('path');
const root=path.resolve(__dirname,'../netlify/functions'),calls=[];
const JOB='11111111-1111-1111-1111-111111111111',REQ='22222222-2222-2222-2222-222222222222',A1='33333333-3333-3333-3333-333333333333',P1='55555555-5555-5555-5555-555555555555',B1='77777777-7777-7777-7777-777777777777';
const job={id:JOB,reference:'PLS-JOB-1592',status:'CONFIRMED',service_name:'Cleaning',work_address:'100 Main St',work_description:'Clean home',internal_notes:null,estimated_duration_minutes:180,quoted_subtotal:150,source_service_request_id:REQ,customers:{first_name:'Maria',email:'customer@example.com'}};
const assignment={id:A1,job_id:JOB,provider_id:P1,status:'CONFIRMED',scheduled_start:'2026-09-10T16:00:00.000Z',scheduled_end:'2026-09-10T19:00:00.000Z',sequence_no:1,is_primary:true,providers:{display_name:'Provider One'}};
let billing=[{id:B1,job_id:JOB,assignment_id:A1,provider_id:P1,quantity:3,unit:'hour',customer_unit_rate:50,customer_line_total:150,provider_unit_rate:30,provider_line_total:90,gross_profit:60,unit_rate:50,line_total:150}];
const request={id:REQ,reference:'PLS-REQ-1592',status:'ASSIGNED',preferred_date:'2026-09-10',preferred_start_time:'10:00',estimated_hours:3,street_address:'100 Main St',city:'Calgary',province:'AB',postal_code:'T2X 0X0',work_description:'Clean home'};
const fakeLib={sbJson:async(url,opt={})=>{const method=opt.method||'GET';calls.push([url,method,opt.body]);
 if(url.startsWith('/rest/v1/jobs?select=id,reference,status'))return [{...job}];
 if(url.startsWith('/rest/v1/job_assignments?select=id,job_id,provider_id,status'))return [{...assignment}];
 if(url.startsWith('/rest/v1/job_service_events?select=assignment_id,event_type'))return [];
 if(url.startsWith('/rest/v1/job_assignments?select=id,job_id,scheduled_start,scheduled_end,status&provider_id='))return [];
 if(url.startsWith('/rest/v1/job_billing_items?select=id,job_id,assignment_id,provider_id'))return billing.map(x=>({...x}));
 if(url.startsWith('/rest/v1/service_requests?select=id,reference,status'))return [{...request}];
 if(url.startsWith('/rest/v1/job_assignments?id=eq.')&&method==='PATCH')return null;
 if(url.startsWith('/rest/v1/job_billing_items?id=eq.')&&method==='PATCH'){const id=decodeURIComponent(url.match(/id=eq\.([^&]+)/)[1]),patch=JSON.parse(opt.body);billing=billing.map(x=>x.id===id?{...x,...patch}:x);return null;}
 if(url.startsWith('/rest/v1/job_billing_items?select=customer_line_total'))return billing.map(x=>({customer_line_total:x.customer_line_total}));
 if(url.startsWith('/rest/v1/job_billing_items?select=id,quantity,unit,customer_unit_rate'))return billing.map(x=>({...x}));
 if(url.startsWith('/rest/v1/jobs?id=eq.')&&method==='PATCH')return null;
 if(url.startsWith('/rest/v1/service_requests?id=eq.')&&method==='PATCH')return null;
 if(['/rest/v1/assignment_status_history','/rest/v1/job_status_history','/rest/v1/service_request_status_history'].includes(url))return null;
 throw new Error(`Unexpected ${method} ${url}`);
}};
const fakeNotify={sendProvider:async()=>({sent:true}),send:async()=>({sent:true}),formatDateTime:x=>x,baseUrl:()=> 'https://pleaseservice.ca'};
require.cache[require.resolve(path.join(root,'_admin-lib.js'))]={exports:fakeLib};require.cache[require.resolve(path.join(root,'_notify-lib.js'))]={exports:fakeNotify};
const helper=require(path.join(root,'_job-schedule-lib.js'));
(async()=>{
 const assert=require('node:assert/strict');
 const base={actorId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',jobId:JOB,scheduledStart:'2026-09-10T16:00:00.000Z',scheduledEnd:'2026-09-10T18:00:00.000Z',estimatedDurationMinutes:120,syncHourlyBilling:true,syncSourceRequest:false,notifyPeople:false};
 await helper.updateActiveJob({...base,billingOverrides:[{id:B1,unit:'service',quantity:99,customer_unit_rate:500,provider_unit_rate:200}]});
 assert.equal(billing[0].unit,'service');assert.equal(billing[0].quantity,1);assert.equal(billing[0].customer_line_total,500);assert.equal(billing[0].provider_line_total,200);
 await helper.updateActiveJob({...base,scheduledEnd:'2026-09-10T20:00:00.000Z',estimatedDurationMinutes:240});
 assert.equal(billing[0].quantity,1);assert.equal(billing[0].customer_line_total,500);
 await helper.updateActiveJob({...base,billingOverrides:[{id:B1,unit:'item',quantity:3,customer_unit_rate:40,provider_unit_rate:15}]});
 assert.equal(billing[0].unit,'item');assert.equal(billing[0].quantity,3);assert.equal(billing[0].customer_line_total,120);assert.equal(billing[0].provider_line_total,45);
 await helper.updateActiveJob({...base,billingOverrides:[{id:B1,unit:'hour',quantity:99,customer_unit_rate:60,provider_unit_rate:25}]});
 assert.equal(billing[0].unit,'hour');assert.equal(billing[0].quantity,2);assert.equal(billing[0].customer_line_total,120);assert.equal(billing[0].provider_line_total,50);
 await assert.rejects(helper.updateActiveJob({...base,billingOverrides:[{id:B1,unit:'item',quantity:-1}]}),/positive number/);
 assert.equal(billing[0].unit,'hour');
 billing[0]={...billing[0],unit:'service',quantity:2,customer_unit_rate:60,provider_unit_rate:25,customer_line_total:120,provider_line_total:50};
 await helper.updateActiveJob(base);
 assert.equal(billing[0].quantity,2);assert.equal(billing[0].customer_line_total,120);
 console.log('Flexible billing runtime: Hourly → Flat Rate → Quantity → Hourly passed; schedule changes preserve fixed prices.');
})().catch(e=>{console.error(e);process.exit(10)});
