const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
function pass(name,cond){assert.ok(cond,name);console.log('PASS:',name)}
const sql=read('supabase/STEP18_1_FINANCIAL_MASTER_DATA.sql');
const api=read('netlify/functions/cal-master-data.js');
const page=read('cal/master-data.html');
const css=read('cal/css/style.css');
const doc=read('STEP18_1_FINANCIAL_MASTER_DATA.md');
const toml=read('netlify.toml');
const calPages=fs.readdirSync('cal').filter(x=>x.endsWith('.html')&&x!=='index.html'&&x!=='master-data.html');
pass('Business Partner Master is additive',sql.includes('create table if not exists public.accounting_parties')&&sql.includes('create table if not exists public.accounting_party_roles'));
pass('Party supports customer, operational provider and supplier roles',sql.includes("'CUSTOMER','OPERATIONAL_PROVIDER','SUPPLIER','EMPLOYEE','CONTRACTOR','OTHER'"));
pass('Legacy accounting_contacts is linked rather than replaced',sql.includes('alter table public.accounting_contacts add column if not exists party_id')&&!sql.includes('drop table public.accounting_contacts'));
pass('Financial account registry maps identity to GL without balances',sql.includes('create table if not exists public.accounting_financial_accounts')&&sql.includes('gl_account_id uuid not null references public.accounting_accounts')&&!/accounting_financial_accounts[\s\S]{0,800}\bbalance\s+numeric/i.test(sql));
pass('STEP 17 control accounts are protected',sql.includes('system_managed=true')&&sql.includes('accounting_protect_system_account'));
pass('Seeded Canadian tax codes are protected',sql.includes("where code in ('AB-GST','ON-HST'")&&sql.includes('system_managed boolean'));
pass('Source sync is best-effort and cannot block PLEASE operations',sql.includes('accounting_source_party_trigger')&&sql.includes('exception when others')&&sql.includes("raise warning 'STEP 18.1 party sync skipped"));
pass('Operational customer/provider tables are not structurally altered',!sql.includes('alter table public.customers')&&!sql.includes('alter table public.providers'));
pass('STEP 18.1 introduces no financial posting event',!sql.includes('accounting_enqueue_event(')&&!sql.includes('please_accounting_outbox'));
pass('New master tables are RLS hardened',sql.includes("array['accounting_parties','accounting_party_roles','accounting_financial_accounts']")&&sql.includes('revoke all on public.%I from anon, authenticated'));
pass('Business partner deletion is prevented for audit continuity',sql.includes('accounting_protect_party_delete'));
pass('Master-data API requires PLEASE Admin and same-origin writes',api.includes('requireAdmin(event)')&&api.includes("event.httpMethod==='POST'&&!lib.sameOrigin(event)"));
pass('PLEASE-managed party identity remains protected while financial attributes/roles are editable',api.includes("party.source_system==='PLEASE'")&&api.includes('await setPartyRoles(party,payload.roles||[])'));
pass('Financial account mappings validate asset/liability semantics',api.includes("assetKinds=new Set(['BANK','CASH','CLEARING'])")&&api.includes("liabilityKinds=new Set(['CREDIT_CARD','LOAN'])"));
pass('Master Data UI exposes all STEP 18.1 master areas',page.includes('Business Partners')&&page.includes('Financial Accounts')&&page.includes('Chart of Accounts Master')&&page.includes('Tax Code Master'));
pass('Master Data UI declares PLEASE source protection',page.includes('remain managed by PLEASE Operations'));
pass('All existing CAL sidebar pages expose Financial Master Data',calPages.every(f=>read('cal/'+f).includes('Financial Master Data')));
pass('Master Data styles are isolated under STEP 18.1 section',css.includes('STEP 18.1 — Financial Master Data'));
pass('Convenience route stays under CAL namespace',toml.includes('from = "/master-data.html"')&&toml.includes('to = "/cal/master-data.html"'));
pass('Documentation explicitly blocks scope creep into STEP 18.2+',doc.includes('What STEP 18.1 explicitly does NOT do')&&doc.includes('Only after acceptance proceed to STEP 18.2'));
console.log('STEP 18.1 Financial Master Data static audit completed successfully.');
