(function(){
const APP='CAL 1.5';const KEY='cal_1_5_data';const SESSION='cal_1_5_session';const LEGAL_VERSION='CAL-LEGAL-1.0-2026-09-05';const LEGAL_EFFECTIVE='2026-09-05';
const provinces={AB:{gst:5,pst:0,name:'Alberta'},BC:{gst:5,pst:7,name:'British Columbia'},MB:{gst:5,pst:7,name:'Manitoba'},NB:{hst:15,name:'New Brunswick'},NL:{hst:15,name:'Newfoundland and Labrador'},NS:{hst:14,name:'Nova Scotia'},NT:{gst:5,pst:0,name:'Northwest Territories'},NU:{gst:5,pst:0,name:'Nunavut'},ON:{hst:13,name:'Ontario'},PE:{hst:15,name:'Prince Edward Island'},QC:{gst:5,qst:9.975,name:'Quebec'},SK:{gst:5,pst:6,name:'Saskatchewan'},YT:{gst:5,pst:0,name:'Yukon'}};
const seed={company:{legalName:'Demo Company Canada Inc.',operatingName:'Demo Company',businessNumber:'',province:'AB',fiscalYearEnd:'12-31',currency:'CAD',gstRegistered:true,gstNumber:'',storageMode:'CLIENT_SUPABASE',retentionYears:6},accounts:[['1000','Operating Bank','ASSET'],['1100','Accounts Receivable','ASSET'],['1200','GST/HST Recoverable','ASSET'],['1500','Equipment & Vehicles','ASSET'],['2000','Accounts Payable','LIABILITY'],['2100','GST/HST Payable','LIABILITY'],['2200','Credit Cards','LIABILITY'],['3000','Share Capital','EQUITY'],['3100','Retained Earnings','EQUITY'],['4000','Service Revenue','REVENUE'],['4100','Other Revenue','REVENUE'],['5000','Subcontractors','EXPENSE'],['5100','Fuel & Vehicle','EXPENSE'],['5200','Insurance','EXPENSE'],['5300','Advertising','EXPENSE'],['5400','Office & Software','EXPENSE'],['5500','Professional Fees','EXPENSE'],['5600','Repairs & Maintenance','EXPENSE'],['5700','Bank Fees','EXPENSE']].map((x,i)=>({id:i+1,code:x[0],name:x[1],type:x[2],active:true})),invoices:[{id:'INV-1001',date:'2026-08-01',customer:'Sample Customer',subtotal:1000,tax:50,total:1050,paid:1050,status:'PAID'}],expenses:[{id:'EXP-1001',date:'2026-08-05',vendor:'Sample Fuel',category:'Fuel & Vehicle',subtotal:140,tax:7,total:147,status:'POSTED'}],bank:[{id:'BNK-1001',date:'2026-08-01',description:'Customer payment INV-1001',amount:1050,type:'CREDIT',matched:true},{id:'BNK-1002',date:'2026-08-05',description:'Sample Fuel',amount:147,type:'DEBIT',matched:true}],journals:[{id:'JE-1001',date:'2026-08-01',memo:'Invoice INV-1001',debits:1050,credits:1050,status:'POSTED'},{id:'JE-1002',date:'2026-08-05',memo:'Expense EXP-1001',debits:147,credits:147,status:'POSTED'}],audit:[{at:'2026-08-01T10:00:00Z',actor:'System',action:'Seeded demo ledger',object:'Company',detail:'Opening demo dataset'}],documents:[],legalAcceptances:[]};
let remoteData=null,remoteSession=null;function connected(){return !!(window.LAC_CONFIG&&window.LAC_CONFIG.mode==='PLEASE_CONNECTED')}function calEndpointError(path,status,text){const raw=String(text||'');if(status===404&&/(<!doctype html|<html|page not found)/i.test(raw))return 'CAL backend function is not deployed yet for '+path+'. Upload the STEP16.0.2 hotfix including netlify/functions, then redeploy Netlify.';if(/(<!doctype html|<html)/i.test(raw))return 'CAL backend returned an HTML error page instead of JSON. Redeploy the STEP16.0.2 backend files and try again.';return raw.slice(0,400)||'CAL request failed';}async function remoteJson(path,opt={}){const base=(window.LAC_CONFIG&&window.LAC_CONFIG.apiBase)||'/.netlify/functions';const url=base+path;let r,t;try{r=await fetch(url,{credentials:'same-origin',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});t=await r.text();}catch(e){throw Error('Could not reach CAL backend. Check connection and Netlify deploy, then try again.')}let j={};try{j=t?JSON.parse(t):{}}catch{j={error:calEndpointError(path,r&&r.status,t)}}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required')}if(!r.ok)throw Error(j.error||calEndpointError(path,r.status,t));return j}async function loadRemote(){if(!connected())return;try{const j=await remoteJson('/cal-dashboard-data');remoteSession=j.session||null;remoteData=j.data||null}catch(e){console.error('CAL connected data',e);remoteData=clone(seed);remoteData.audit=[{at:new Date().toISOString(),actor:'CAL',action:'Connected data unavailable',object:'Accounting Bridge',detail:e.message||String(e)}]}}function clone(v){return JSON.parse(JSON.stringify(v))}function data(){if(remoteData)return clone(remoteData);try{return JSON.parse(localStorage.getItem(KEY))||clone(seed)}catch(e){return clone(seed)}}function save(d){if(connected()){alert('Connected CAL mode is read-only for manual browser edits. PLEASE operational events generate accounting entries through the server-side bridge.');return}localStorage.setItem(KEY,JSON.stringify(d))}function money(n){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0))}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function id(prefix,arr){return prefix+'-'+String(1001+(arr?.length||0)).padStart(4,'0')}
function log(d,action,object,detail){d.audit.unshift({at:new Date().toISOString(),actor:'Administrator',action,object,detail})}
function currentPage(){return document.body.dataset.page||''}
function nav(){let p=currentPage();document.querySelectorAll('.sidebar a').forEach(a=>{if(a.dataset.page===p)a.classList.add('active')})}
function currentUser(){return connected()?(remoteSession?.user?.id||'please-admin'):sessionStorage.getItem(SESSION)||''}function hasLegalAcceptance(){if(connected())return !!remoteSession?.legalAccepted;let d=data();let a=d.legalAcceptances||[];return a.some(x=>x.userId===currentUser()&&x.agreementVersion===LEGAL_VERSION)}function auth(){if(currentPage()==='login'){if(connected()&&remoteSession?.user)location.href='dashboard.html';return}if(!currentUser()){location.href='index.html';return}if(currentPage()!=='disclaimer'&&!hasLegalAcceptance()){location.href='disclaimer.html'}}
function initHeader(){let d=data(), el=document.querySelector('[data-tenant]');if(el)el.innerHTML='<strong>'+esc(d.company.operatingName)+'</strong><span>'+esc(provinces[d.company.province]?.name||d.company.province)+' · Client-custodied data</span>'}
function calc(){let d=data();let rev=d.invoices.reduce((a,x)=>a+x.subtotal,0),ar=d.invoices.reduce((a,x)=>a+(x.total-x.paid),0),exp=d.expenses.reduce((a,x)=>a+x.subtotal,0),taxOut=d.invoices.reduce((a,x)=>a+x.tax,0),itc=d.expenses.reduce((a,x)=>a+x.tax,0);return{d,rev,ar,exp,profit:rev-exp,taxOut,itc,taxNet:taxOut-itc,bank:d.bank.reduce((a,x)=>a+(x.type==='CREDIT'?x.amount:-x.amount),0)}}
function taxRate(prov){let p=provinces[prov]||provinces.AB;return p.hst||((p.gst||0)+(p.qst||0)+(p.pst||0))}
function dashboard(){let c=calc();setText('kpiRevenue',money(c.rev));setText('kpiExpenses',money(c.exp));setText('kpiProfit',money(c.profit));setText('kpiTax',money(c.taxNet));let bn=document.getElementById('bridgeNotice');if(bn&&c.d.bridge){bn.textContent='PLEASE Accounting Bridge: '+(c.d.bridge.enabled?'enabled':'disabled')+' · Posted events: '+(c.d.bridge.posted||0)+' · Pending: '+(c.d.bridge.pending||0)+' · Errors: '+(c.d.bridge.errors||0);}let t=document.querySelector('#recentInvoices');if(t)t.innerHTML=c.d.invoices.slice(-5).reverse().map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.customer)}</td><td>${esc(x.date)}</td><td class="money">${money(x.total)}</td><td><span class="pill ${x.status==='PAID'?'green':'amber'}">${esc(x.status)}</span></td></tr>`).join('');let bars=document.querySelector('#miniChart');if(bars){let vals=[42,58,44,75,61,87,69,92];bars.innerHTML=vals.map((v,i)=>`<div class="bar" style="height:${v}%"><span>W${i+1}</span></div>`).join('')}}
function setText(id,v){let e=document.getElementById(id);if(e)e.textContent=v}
function renderInvoices(){let d=data(),b=document.querySelector('#invoiceRows');if(!b)return;b.innerHTML=d.invoices.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.date)}</td><td>${esc(x.customer)}</td><td>${money(x.subtotal)}</td><td>${money(x.tax)}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td><span class="pill ${x.status==='PAID'?'green':'amber'}">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No invoices yet.</td></tr>'}
function renderExpenses(){let d=data(),b=document.querySelector('#expenseRows');if(!b)return;b.innerHTML=d.expenses.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.date)}</td><td>${esc(x.vendor)}</td><td>${esc(x.category)}</td><td>${money(x.subtotal)}</td><td>${money(x.tax)}</td><td>${money(x.total)}</td><td><span class="pill green">${esc(x.status)}</span></td></tr>`).join('')}
function renderBank(){let d=data(),b=document.querySelector('#bankRows');if(!b)return;b.innerHTML=d.bank.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.description)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td><span class="pill ${x.matched?'green':'amber'}">${x.matched?'MATCHED':'UNMATCHED'}</span></td></tr>`).join('');setText('bankBalance',money(calc().bank));setText('bookBalance',money(calc().bank));setText('difference',money(0))}
function renderJournals(){let d=data(),b=document.querySelector('#journalRows');if(!b)return;b.innerHTML=d.journals.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.date)}</td><td>${esc(x.memo)}</td><td>${money(x.debits)}</td><td>${money(x.credits)}</td><td><span class="pill green">${esc(x.status)}</span></td></tr>`).join('')}
function renderTaxes(){let c=calc(),prov=provinces[c.d.company.province]||provinces.AB;setText('taxProvince',prov.name);setText('taxRate',taxRate(c.d.company.province).toFixed(3).replace(/\.000$/,'')+'%');setText('taxCollected',money(c.taxOut));setText('taxCredits',money(c.itc));setText('taxNet',money(c.taxNet));let note=document.querySelector('#taxNote');if(note)note.textContent=c.d.company.province==='QC'?'Quebec setup supports separate GST and QST configuration. Filing is intentionally not transmitted directly in CAL 1.5.':'CAL 1.5 prepares working totals. Direct CRA filing is intentionally disabled.'}
function renderReports(){let c=calc();['reportRevenue','reportExpenses','reportProfit','reportAR','reportBank'].forEach((id,i)=>setText(id,money([c.rev,c.exp,c.profit,c.ar,c.bank][i])));let b=document.querySelector('#trialRows');if(b)b.innerHTML=c.d.accounts.map(a=>`<tr><td>${esc(a.code)}</td><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${money(0)}</td><td>${money(0)}</td></tr>`).join('')}
function renderAccounts(){let d=data(),b=document.querySelector('#accountRows');if(!b)return;b.innerHTML=d.accounts.map(a=>`<tr><td>${esc(a.code)}</td><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td><span class="pill green">ACTIVE</span></td></tr>`).join('')}
function renderAudit(){let d=data(),b=document.querySelector('#auditRows');if(!b)return;b.innerHTML=d.audit.map(x=>`<tr><td>${new Date(x.at).toLocaleString()}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.object)}</td><td>${esc(x.detail)}</td></tr>`).join('')}
function renderSettings(){let d=data();Object.entries(d.company).forEach(([k,v])=>{let e=document.querySelector(`[name="${k}"]`);if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v}})}
function renderDisclaimer(){let d=data(),a=connected()?(d.legalAcceptances||[])[0]:(d.legalAcceptances||[]).find(x=>x.userId===currentUser()&&x.agreementVersion===LEGAL_VERSION);let form=document.getElementById('legalAcceptanceForm');let pill=document.getElementById('legalStatusPill');let detail=document.getElementById('legalAcceptedDetail');let version=document.getElementById('agreementVersionLabel');if(version)version.textContent=LEGAL_VERSION;if(form){let company=form.querySelector('[name="legalCompanyName"]');if(company&&!company.value)company.value=d.company.legalName||'';let email=form.querySelector('[name="signerEmail"]');if(email&&!email.value&&currentUser()==='demo-admin')email.value='admin@demo.local'}if(a){if(pill){pill.textContent='ACCEPTED';pill.className='pill green'}if(detail)detail.textContent='Accepted by '+(a.signerName||a.signer_name)+' ('+(a.signerEmail||a.signer_email)+') on '+new Date(a.acceptedAt||a.accepted_at).toLocaleString()+' via '+String(a.acceptanceMethod||a.acceptance_method||'ELECTRONIC_SIGNATURE').replaceAll('_',' ')+'.';let gate=document.getElementById('legalGateNotice');if(gate)gate.textContent='Current agreement accepted. You may review or print this agreement at any time.'}}
function openModal(id){document.getElementById(id)?.classList.add('open')}function closeModal(id){document.getElementById(id)?.classList.remove('open')}
function bind(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
let lf=document.getElementById('loginForm');if(lf)lf.onsubmit=e=>{e.preventDefault();sessionStorage.setItem(SESSION,'demo-admin');location.href=hasLegalAcceptance()?'dashboard.html':'disclaimer.html'};
let inv=document.getElementById('invoiceForm');if(inv)inv.onsubmit=e=>{e.preventDefault();let d=data(),f=new FormData(inv),sub=Number(f.get('subtotal')),rate=taxRate(d.company.province),tax=d.company.gstRegistered?sub*rate/100:0,total=sub+tax;let x={id:id('INV',d.invoices),date:f.get('date'),customer:f.get('customer'),subtotal:sub,tax:+tax.toFixed(2),total:+total.toFixed(2),paid:Number(f.get('paid')||0),status:Number(f.get('paid')||0)>=total?'PAID':'OPEN'};d.invoices.push(x);d.journals.push({id:id('JE',d.journals),date:x.date,memo:'Invoice '+x.id,debits:x.total,credits:x.total,status:'POSTED'});log(d,'Created invoice',x.id,x.customer+' '+money(x.total));save(d);closeModal('invoiceModal');renderInvoices()};
let ex=document.getElementById('expenseForm');if(ex)ex.onsubmit=e=>{e.preventDefault();let d=data(),f=new FormData(ex),sub=Number(f.get('subtotal')),tax=Number(f.get('tax')||0),x={id:id('EXP',d.expenses),date:f.get('date'),vendor:f.get('vendor'),category:f.get('category'),subtotal:sub,tax,total:sub+tax,status:'POSTED'};d.expenses.push(x);d.journals.push({id:id('JE',d.journals),date:x.date,memo:'Expense '+x.id,debits:x.total,credits:x.total,status:'POSTED'});log(d,'Posted expense',x.id,x.vendor+' '+money(x.total));save(d);closeModal('expenseModal');renderExpenses()};
let jf=document.getElementById('journalForm');if(jf)jf.onsubmit=e=>{e.preventDefault();let d=data(),f=new FormData(jf),debit=Number(f.get('debit')),credit=Number(f.get('credit'));if(Math.abs(debit-credit)>0.001){alert('Journal entry must balance: total debits must equal total credits.');return}let x={id:id('JE',d.journals),date:f.get('date'),memo:f.get('memo'),debits:debit,credits:credit,status:'POSTED'};d.journals.push(x);log(d,'Posted journal entry',x.id,x.memo);save(d);closeModal('journalModal');renderJournals()};
let sf=document.getElementById('settingsForm');if(sf)sf.onsubmit=e=>{e.preventDefault();let d=data(),f=new FormData(sf);['legalName','operatingName','businessNumber','province','fiscalYearEnd','gstNumber','storageMode'].forEach(k=>d.company[k]=f.get(k)||'');d.company.gstRegistered=f.get('gstRegistered')==='on';d.company.retentionYears=6;log(d,'Updated company settings','Company',d.company.operatingName);save(d);initHeader();alert('Company settings saved locally. In production, the client-owned Supabase deployment becomes the source of truth.')};

let legal=document.getElementById('legalAcceptanceForm');if(legal)legal.onsubmit=async e=>{e.preventDefault();let d=data(),f=new FormData(legal),signerName=String(f.get('signerName')||'').trim(),signatureText=String(f.get('signatureText')||'').trim();if(!f.get('agreementAccepted')){alert('You must accept the agreement to continue.');return}if(!signerName||!signatureText){alert('Signer name and signature are required.');return}if(connected()){try{await remoteJson('/cal-legal-acceptance',{method:'POST',body:JSON.stringify({agreementAccepted:true,legalCompanyName:String(f.get('legalCompanyName')||'').trim(),signerName,signerTitle:String(f.get('signerTitle')||'').trim(),signerEmail:String(f.get('signerEmail')||'').trim(),signatureText,acceptanceMethod:String(f.get('acceptanceMethod')||'ELECTRONIC_SIGNATURE')})});alert('Agreement acceptance recorded in CAL and copy notification queued to Lottus.');location.href='dashboard.html'}catch(err){alert(err.message||'Agreement acceptance could not be recorded. Confirm the STEP16.0.2 CAL backend files are deployed and the STEP16.0 SQL has been executed.')}return}d.legalAcceptances=d.legalAcceptances||[];let record={id:'LEGAL-'+Date.now(),userId:currentUser(),agreementVersion:LEGAL_VERSION,effectiveDate:LEGAL_EFFECTIVE,legalCompanyName:String(f.get('legalCompanyName')||'').trim(),signerName,signerTitle:String(f.get('signerTitle')||'').trim(),signerEmail:String(f.get('signerEmail')||'').trim(),signatureText,acceptanceMethod:String(f.get('acceptanceMethod')||'ELECTRONIC_SIGNATURE'),acceptedAt:new Date().toISOString(),platform:'CAL 1.5',provider:'Lottus Services Inc.'};d.legalAcceptances=d.legalAcceptances.filter(x=>!(x.userId===record.userId&&x.agreementVersion===LEGAL_VERSION));d.legalAcceptances.push(record);log(d,'Accepted legal agreement',LEGAL_VERSION,record.signerName+' · '+record.acceptanceMethod);save(d);alert('Agreement acceptance recorded. A copy should also be retained in the Customer-controlled records.');location.href='dashboard.html'};
let printAgreement=document.getElementById('printAgreement');if(printAgreement)printAgreement.onclick=()=>window.print();let printAgreementBottom=document.getElementById('printAgreementBottom');if(printAgreementBottom)printAgreementBottom.onclick=()=>window.print();
let reset=document.getElementById('resetDemo');if(reset)reset.onclick=()=>{if(confirm('Reset all demo data?')){save(clone(seed));location.reload()}};let exp=document.getElementById('exportData');if(exp)exp.onclick=()=>{let blob=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='accounting-export-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};let sync=document.getElementById('syncAccounting');if(sync)sync.onclick=async()=>{if(!connected())return;sync.disabled=true;sync.textContent='Syncing...';try{const r=await remoteJson('/cal-accounting-sync',{method:'POST',body:JSON.stringify({limit:300})});await loadRemote();alert('Accounting sync complete. '+JSON.stringify(r.summary||{}));location.reload()}catch(err){alert(err.message||'Accounting sync failed')}finally{sync.disabled=false;sync.textContent='Sync PLEASE Accounting'}}}
async function init(){await loadRemote();auth();nav();initHeader();bind();({dashboard, invoices:renderInvoices,expenses:renderExpenses,banking:renderBank,journal:renderJournals,taxes:renderTaxes,reports:renderReports,accounts:renderAccounts,audit:renderAudit,settings:renderSettings,disclaimer:renderDisclaimer}[currentPage()]||(()=>{}))()}
document.addEventListener('DOMContentLoaded',()=>{init().catch(e=>console.error('CAL init',e))});window.CAL={data,save,money,openModal,closeModal,provinces,LEGAL_VERSION,LEGAL_EFFECTIVE,hasLegalAcceptance};
})();
