(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const signedMoney=n=>`${Number(n||0)>=0?'+':'−'}${money(Math.abs(Number(n||0)))}`;
const today=()=>new Date().toISOString().slice(0,10);
let state={financialAccounts:[],reconciliations:[],selectedReconciliation:null,transactions:[],ledgerCandidates:[],treasury:{},imports:[]},selectedReconId=null,selectedTx=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-banking',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Banking backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Banking & Reconciliation request failed.');return j;}
function status(msg,bad=false){const el=$('#bankingStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function accountName(id){const f=state.financialAccounts.find(x=>x.id===id);return f?`${f.name}${f.institution_name?' · '+f.institution_name:''}`:'Financial account'}
function pill(s){const x=String(s||'').toUpperCase(),c=x==='CLOSED'?'green':x==='IN_PROGRESS'?'blue':x==='MATCHED'?'green':x==='UNMATCHED'?'amber':'amber';return `<span class="pill ${c}">${esc(x||'DRAFT')}</span>`}
async function load(reconciliationId=null,accountId=null){status('Loading treasury and reconciliation data…');let q=[];if(reconciliationId)q.push(`reconciliation_id=${encodeURIComponent(reconciliationId)}`);if(accountId)q.push(`financial_account_id=${encodeURIComponent(accountId)}`);const url='/.netlify/functions/cal-banking'+(q.length?'?'+q.join('&'):'');const r=await fetch(url,{credentials:'same-origin'}),t=await r.text();let out;try{out=t?JSON.parse(t):{}}catch{throw Error('Banking backend returned a non-JSON response.')}if(r.status===401){location.replace('../admin-login.html');return}if(!r.ok)throw Error(out.error||'Unable to load Banking.');state=out.data||state;selectedReconId=state.selectedReconciliation?.id||null;render();status('');}
function render(){renderTreasury();renderSelectors();renderReconciliation();renderTransactions();renderBook();renderHistory();}
function renderTreasury(){const t=state.treasury||{};$('#cashAsOf').textContent=`Automatic ledger position as of ${t.asOf||today()}`;$('#cashBank').textContent=money(t.bankCash);$('#cashClearing').textContent=money(t.clearing);$('#cashDueToday').textContent=money(t.commitmentsToday);$('#cashAvailable').textContent=money(t.availableResources);$('#cashDue7').textContent=money(t.commitments7);$('#cashDue30').textContent=money(t.commitments30);$('#cashAR7').textContent=money(t.receivables7);$('#cashAR30').textContent=money(t.receivables30);$('#cashDebt').textContent=money(t.creditCardAndLoanBalance);}
function renderSelectors(){const a=$('#accountSelect'),r=$('#reconSelect'),currentAccount=state.selectedReconciliation?.financial_account_id||a.value||state.financialAccounts.find(x=>x.is_primary)?.id||state.financialAccounts[0]?.id||'';a.innerHTML=state.financialAccounts.map(f=>`<option value="${esc(f.id)}" ${f.id===currentAccount?'selected':''}>${esc(f.name)} · ${esc(f.financial_type)} · ${money(f.balance)}</option>`).join('')||'<option value="">No financial accounts</option>';const relevant=state.reconciliations.filter(x=>!currentAccount||x.financial_account_id===currentAccount);r.innerHTML='<option value="">No reconciliation selected</option>'+relevant.map(x=>`<option value="${esc(x.id)}" ${x.id===selectedReconId?'selected':''}>${esc(x.reconciliation_number)} · ${esc(x.period_start)} → ${esc(x.period_end)} · ${esc(x.status)}</option>`).join('');}
function renderReconciliation(){const r=state.selectedReconciliation,s=r?.snapshot||{};$('#reconEmpty').hidden=!!r;$('#reconWorkspace').hidden=!r;if(!r)return;$('#reconBook').textContent=money(s.book_ending_balance);$('#reconStatement').textContent=money(r.statement_ending_balance);$('#reconAdjusted').textContent=money(s.adjusted_statement_balance);$('#reconDifference').textContent=money(s.difference);$('#reconStatementControl').textContent=`Calculated ending ${money(s.calculated_statement_ending)} · control ${money(s.statement_control_difference)}`;$('#reconOutstanding').textContent=`${s.outstanding_book_count||0} outstanding · ${signedMoney(s.outstanding_book_effect||0)}`;const balanced=Math.abs(Number(s.difference||0))<=.01&&Math.abs(Number(s.statement_control_difference||0))<=.01&&Number(s.unmatched_statement_count||0)===0,el=$('#reconIntegrity');el.textContent=r.status==='CLOSED'?'CLOSED':balanced?'READY TO CLOSE':'IN PROGRESS';el.className='pill '+(r.status==='CLOSED'||balanced?'green':'amber');$('#reconMeta').innerHTML=`<div><span>Account</span><strong>${esc(accountName(r.financial_account_id))}</strong></div><div><span>Period</span><strong>${esc(r.period_start)} → ${esc(r.period_end)}</strong></div><div><span>Opening statement</span><strong>${money(r.statement_opening_balance)}</strong></div><div><span>Statement activity</span><strong>${signedMoney(s.statement_activity||0)}</strong></div><div><span>Unmatched statement</span><strong>${s.unmatched_statement_count||0}</strong></div><div><span>Status</span><strong>${esc(r.status)}</strong></div>`;const closed=r.status==='CLOSED';$('#editControlBtn').hidden=closed;$('#importBtn').hidden=closed;$('#autoMatchBtn').hidden=closed;$('#closeReconBtn').hidden=closed;}
function matchEvidence(t){if(!t.matches?.length)return '—';return t.matches.map(m=>`${esc(m.entry_number||'Journal')} · ${esc(m.entry_date||'')} · ${esc(m.memo||m.description||'')}`).join('<br>')}
function renderTransactions(){const rows=state.transactions||[];$('#statementCount').textContent=`${rows.length} imported · ${rows.filter(x=>!x.matches?.length).length} unmatched`;$('#statementRows').innerHTML=rows.map(t=>{const matched=!!t.matches?.length,closed=state.selectedReconciliation?.status==='CLOSED';return `<tr><td>${esc(t.statement_date)}</td><td>${esc(t.description)}${t.external_id?`<br><span class="small">${esc(t.external_id)}</span>`:''}</td><td class="money ${Number(t.signed_amount)<0?'danger':'ok'}"><strong>${signedMoney(t.signed_amount)}</strong></td><td>${pill(matched?'MATCHED':'UNMATCHED')}</td><td class="treasury-evidence">${matchEvidence(t)}</td><td>${closed?'—':matched?`<button class="btn secondary master-action" data-unmatch="${esc(t.id)}">Unmatch</button>`:`<button class="btn secondary master-action" data-match="${esc(t.id)}">Match</button>`}</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No statement transactions.</td></tr>';$$('[data-match]').forEach(b=>b.onclick=()=>openMatch(b.dataset.match));$$('[data-unmatch]').forEach(b=>b.onclick=()=>unmatch(b.dataset.unmatch));}
function renderBook(){const rows=state.ledgerCandidates||[];$('#bookCount').textContent=`${rows.length} outstanding`;$('#bookRows').innerHTML=rows.map(x=>`<tr><td>${esc(x.entry_date)}</td><td><strong>${esc(x.entry_number)}</strong></td><td>${esc(x.memo||'')}<br><span class="small">${esc(x.description||'')}</span></td><td class="money ${Number(x.effect)<0?'danger':'ok'}"><strong>${signedMoney(x.effect)}</strong></td><td><span class="pill amber">OUTSTANDING</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No outstanding book items in this reconciliation.</td></tr>';}
function renderHistory(){const am=new Map(state.financialAccounts.map(f=>[f.id,f]));$('#historyRows').innerHTML=(state.reconciliations||[]).map(r=>`<tr data-recon-row="${esc(r.id)}"><td><strong>${esc(r.reconciliation_number)}</strong></td><td>${esc(am.get(r.financial_account_id)?.name||'—')}</td><td>${esc(r.period_start)} → ${esc(r.period_end)}</td><td>${money(r.statement_ending_balance)}</td><td>${money(r.book_ending_balance)}</td><td>${money(r.difference)}</td><td>${pill(r.status)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No reconciliations yet.</td></tr>';$$('[data-recon-row]').forEach(tr=>{tr.style.cursor='pointer';tr.onclick=()=>load(tr.dataset.reconRow)});}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});status('Saved.');return j.result}
function setDefaultPeriod(){const d=new Date(),end=d.toISOString().slice(0,10),start=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)).toISOString().slice(0,10),f=$('#startReconForm');f.elements.period_start.value=start;f.elements.period_end.value=end;const selected=$('#accountSelect').value;f.elements.financial_account_id.innerHTML=state.financialAccounts.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.name)} · ${esc(x.financial_type)}</option>`).join('');}
async function startRecon(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await post('START_RECONCILIATION',Object.fromEntries(f.entries()));close('startReconModal');await load(r.id)}catch(err){status(err.message,true);alert(err.message)}}
function openControl(){const r=state.selectedReconciliation;if(!r)return;const f=$('#controlForm');f.elements.statement_opening_balance.value=Number(r.statement_opening_balance||0).toFixed(2);f.elements.statement_ending_balance.value=Number(r.statement_ending_balance||0).toFixed(2);f.elements.statement_reference.value=r.statement_reference||'';open('controlModal')}
async function saveControl(e){e.preventDefault();if(!selectedReconId)return;const f=new FormData(e.currentTarget);try{await post('UPDATE_RECONCILIATION_CONTROL',{reconciliation_id:selectedReconId,...Object.fromEntries(f.entries())});close('controlModal');await load(selectedReconId)}catch(err){status(err.message,true);alert(err.message)}}
function parseCsv(text){const first=(text.split(/\r?\n/)[0]||''),delims=[',',';','\t'],delim=delims.sort((a,b)=>(first.split(b).length-first.split(a).length))[0];const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===delim&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row)}if(rows.length<2)throw Error('CSV must contain a header row and at least one transaction.');const headers=rows.shift().map(x=>String(x).trim().toLowerCase().replace(/[^a-z0-9]/g,''));const idx=names=>{for(const n of names){const i=headers.indexOf(n);if(i>=0)return i}return -1},di=idx(['date','transactiondate','posteddate','postingdate']),desc=idx(['description','details','memo','name','transaction','payee']),amt=idx(['amount','transactionamount','value']),debit=idx(['debit','withdrawal','withdrawals']),credit=idx(['credit','deposit','deposits']),id=idx(['id','fitid','transactionid','reference','ref']);if(di<0||desc<0||(amt<0&&(debit<0||credit<0)))throw Error('CSV requires Date, Description, and either Amount or Debit/Credit columns.');return rows.map(r=>{let a=amt>=0?num(r[amt]):num(r[credit])-num(r[debit]);return{date:dateValue(r[di]),description:String(r[desc]||'').trim(),amount:a,external_id:id>=0?String(r[id]||'').trim():null}}).filter(x=>x.date&&x.description&&Math.abs(x.amount)>.004)}
function num(v){let s=String(v??'').trim(),neg=/^\(.*\)$/.test(s);s=s.replace(/[,$()\s]/g,'');const n=Number(s||0);return (neg?-1:1)*(Number.isFinite(n)?n:0)}
function dateValue(v){const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;if(/^\d{8}/.test(s))return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m){let a=Number(m[1]),b=Number(m[2]),month=a,day=b;if(a>12){day=a;month=b}return `${m[3]}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}return ''}
function tag(block,name){const m=block.match(new RegExp(`<${name}>([^<\\r\\n]+)`,'i'));return m?m[1].trim():''}
function parseOfx(text){const blocks=text.split(/<STMTTRN>/i).slice(1);if(!blocks.length)throw Error('No OFX/QFX statement transactions found.');return blocks.map(b=>({date:dateValue(tag(b,'DTPOSTED')),description:[tag(b,'NAME'),tag(b,'MEMO')].filter(Boolean).join(' · ')||'OFX transaction',amount:num(tag(b,'TRNAMT')),external_id:tag(b,'FITID')||null})).filter(x=>x.date&&Math.abs(x.amount)>.004)}
async function sha256(text){const b=new TextEncoder().encode(text),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function normalizeSigns(rows,mode,account){let invert=mode==='INVERT'||(mode==='AUTO'&&['CREDIT_CARD','LOAN'].includes(String(account?.financial_type||'').toUpperCase()));return rows.map(x=>({...x,amount:Math.round((invert?-Number(x.amount):Number(x.amount))*100)/100}))}
async function importStatement(e){e.preventDefault();if(!selectedReconId)return;const f=new FormData(e.currentTarget),file=f.get('statement_file');if(!(file instanceof File)||!file.size)return alert('Choose a CSV, OFX, or QFX statement file.');try{status('Reading statement…');const text=await file.text(),ext=(file.name.split('.').pop()||'CSV').toUpperCase(),format=['OFX','QFX'].includes(ext)?ext:'CSV',raw=format==='CSV'?parseCsv(text):parseOfx(text),account=state.financialAccounts.find(x=>x.id===state.selectedReconciliation?.financial_account_id),rows=normalizeSigns(raw,String(f.get('sign_mode')||'AUTO'),account);if(!rows.length)throw Error('No usable statement transactions were found.');const result=await post('IMPORT_STATEMENT',{reconciliation_id:selectedReconId,file_name:file.name,file_hash:await sha256(text),file_format:format,rows});close('importModal');alert(`Statement imported: ${result.inserted||0} new transaction(s), ${result.skipped_duplicates||0} duplicate(s) skipped.`);await load(selectedReconId)}catch(err){status(err.message,true);alert(err.message)}}
function openMatch(id){selectedTx=state.transactions.find(x=>x.id===id);if(!selectedTx)return;$('#matchTarget').textContent=`${selectedTx.statement_date} · ${selectedTx.description} · ${signedMoney(selectedTx.signed_amount)}`;$('#matchStatementTotal').textContent=signedMoney(selectedTx.signed_amount);const sameSign=state.ledgerCandidates.filter(x=>Math.sign(Number(x.effect))===Math.sign(Number(selectedTx.signed_amount))).slice(0,500);$('#matchRows').innerHTML=sameSign.map(x=>`<tr><td><input type="checkbox" data-line-id="${esc(x.id)}" data-effect="${esc(x.effect)}"></td><td>${esc(x.entry_date)}</td><td>${esc(x.entry_number)}</td><td>${esc(x.memo||'')}<br><span class="small">${esc(x.description||'')}</span></td><td class="money">${signedMoney(x.effect)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No same-direction outstanding ledger candidates.</td></tr>';$$('[data-line-id]').forEach(x=>x.onchange=matchTotal);matchTotal();open('matchModal')}
function matchTotal(){const total=$$('[data-line-id]:checked').reduce((n,x)=>n+Number(x.dataset.effect||0),0);$('#matchSelectedTotal').textContent=signedMoney(total);}
async function saveMatch(){if(!selectedTx)return;const ids=$$('[data-line-id]:checked').map(x=>x.dataset.lineId);if(!ids.length)return alert('Select at least one ledger line.');try{await post('MATCH_TRANSACTION',{bank_transaction_id:selectedTx.id,journal_line_ids:ids});close('matchModal');await load(selectedReconId)}catch(err){status(err.message,true);alert(err.message)}}
async function unmatch(id){if(!confirm('Remove this statement-to-ledger match?'))return;try{await post('UNMATCH_TRANSACTION',{bank_transaction_id:id});await load(selectedReconId)}catch(err){status(err.message,true);alert(err.message)}}
async function autoMatch(){if(!selectedReconId)return;try{const r=await post('AUTO_MATCH',{reconciliation_id:selectedReconId});alert(`Auto Match complete. Matched ${r.matched||0}; ambiguous ${r.ambiguous||0}; unmatched ${r.unmatched||0}.`);await load(selectedReconId)}catch(err){status(err.message,true);alert(err.message)}}
async function closeRecon(){if(!selectedReconId||!confirm('Close this reconciliation? Closed reconciliations and their match evidence become immutable.'))return;try{await post('CLOSE_RECONCILIATION',{reconciliation_id:selectedReconId});await load(selectedReconId);alert('Reconciliation closed successfully.')}catch(err){status(err.message,true);alert(err.message)}}
function bind(){$('#startReconBtn').onclick=()=>{setDefaultPeriod();open('startReconModal')};$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#startReconForm').onsubmit=startRecon;$('#editControlBtn').onclick=openControl;$('#controlForm').onsubmit=saveControl;$('#importBtn').onclick=()=>{if(!selectedReconId)return;$('#importForm').reset();open('importModal')};$('#importForm').onsubmit=importStatement;$('#autoMatchBtn').onclick=autoMatch;$('#closeReconBtn').onclick=closeRecon;$('#saveMatchBtn').onclick=saveMatch;$('#accountSelect').onchange=()=>load(null,$('#accountSelect').value);$('#reconSelect').onchange=()=>load($('#reconSelect').value||null,$('#accountSelect').value);}
document.addEventListener('DOMContentLoaded',()=>{bind();load().catch(e=>{status(e.message,true);console.error(e)})});
})();
