(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const todayLocal=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={company:null,settings:null,accounts:[],gifiCodes:[],gifiPapers:[],obligations:[],approvals:[],evidence:[],packages:[],documents:[],summary:{}},reviewContext=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-compliance',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Compliance backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Compliance request failed.');return j}
function status(msg,bad=false){const el=$('#complianceStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function pill(s){const x=String(s||'').toUpperCase(),c=['APPROVED','FILED','PAID'].includes(x)?'green':['PREPARED','REVIEWED'].includes(x)?'blue':x==='WAIVED'?'wine':x==='OPEN'?'amber':'blue';return `<span class="pill ${c}">${esc(x||'—')}</span>`}
function dt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.valueOf())?esc(v):esc(d.toLocaleString())}
function dateRange(o){if(!o.period_start&&!o.period_end)return'—';return `${esc(o.period_start||'—')} → ${esc(o.period_end||'—')}`}
function currentYear(){return new Date().getFullYear()}
function render(){const m=state.summary||{};$('#complianceOverdue').textContent=m.overdue||0;$('#complianceDue30').textContent=m.due30||0;$('#gifiUnmapped').textContent=m.unmappedAccounts||0;$('#approvedPackages').textContent=m.approvedPackages||0;renderObligations();renderMappings();renderPapers();renderPackages();renderEvidence();renderApprovals()}
function nextAction(o){if(o.status==='OPEN')return'PREPARE';if(o.status==='PREPARED')return'REVIEW';if(o.status==='REVIEWED')return'APPROVE';return null}
function renderObligations(){const year=Number($('#calendarYear').value||currentYear());const rows=state.obligations.filter(o=>{const y=Number(String(o.due_date||'').slice(0,4));return y===year||Number(String(o.period_end||'').slice(0,4))===year});$('#obligationRows').innerHTML=rows.map(o=>{const a=nextAction(o);const source=`${o.source_reference||''}${o.due_date_requires_holiday_review?' · Holiday/business-day review':''}`;let buttons=a?`<button class="btn secondary master-action" data-ob-action="${esc(a)}" data-ob="${esc(o.id)}">${esc(a)}</button>`:'';if(o.status==='APPROVED'&&o.action_kind!=='INTERNAL')buttons+=` <button class="btn green master-action" data-evidence="${esc(o.id)}">Evidence</button>`;if(['OPEN','PREPARED','REVIEWED','APPROVED'].includes(o.status))buttons+=` <button class="btn secondary master-action" data-waive="${esc(o.id)}">Waive</button>`;return `<tr><td><strong>${esc(o.due_date)}</strong></td><td>${esc(o.authority)}</td><td><strong>${esc(o.title)}</strong><br><span class="small">${esc(o.obligation_type)}</span></td><td>${dateRange(o)}</td><td>${esc(o.action_kind)}</td><td>${pill(o.status)}</td><td class="compliance-evidence-cell">${esc(source||'—')}</td><td>${buttons||'—'}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No obligations for this year. Generate / Refresh the calendar after confirming settings.</td></tr>';$$('[data-ob-action]').forEach(b=>b.onclick=()=>advance(b.dataset.ob,b.dataset.obAction));$$('[data-waive]').forEach(b=>b.onclick=()=>waive(b.dataset.waive));$$('[data-evidence]').forEach(b=>b.onclick=()=>openEvidence(b.dataset.evidence))}
function renderMappings(){const rows=state.accounts;$('#mappingSummary').textContent=`${rows.filter(x=>x.gifi_mapping).length}/${rows.length} active GL accounts mapped · ${rows.filter(x=>!x.gifi_mapping).length} unmapped`;$('#mappingRows').innerHTML=rows.map(a=>{const m=a.gifi_mapping,g=m?.gifi;return `<tr><td><strong>${esc(a.code)}</strong></td><td>${esc(a.name)}</td><td>${esc(a.account_type)}</td><td>${g?`<strong>${esc(g.code)}</strong> · ${esc(g.name)}${Number(m.sign_multiplier)===-1?' · × -1':''}`:'<span class="danger">UNMAPPED</span>'}</td><td>${m?esc(m.mapping_source):'—'}</td><td><button class="btn secondary master-action" data-map="${esc(a.id)}">Map</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No active GL accounts.</td></tr>';$$('[data-map]').forEach(b=>b.onclick=()=>openMapping(b.dataset.map))}
function renderPapers(){const rows=state.gifiPapers;$('#gifiPaperRows').innerHTML=rows.map(p=>{let actions=`<button class="btn secondary master-action" data-gifi-csv="${esc(p.id)}">CSV</button>`;if(p.status==='DRAFT')actions+=` <button class="btn secondary master-action" data-review="REVIEW_GIFI" data-id="${esc(p.id)}">Review</button>`;if(p.status==='REVIEWED')actions+=` <button class="btn green master-action" data-review="APPROVE_GIFI" data-id="${esc(p.id)}">Approve</button>`;return `<tr><td><strong>${esc(p.paper_number)}</strong></td><td>${esc(p.period_end)}</td><td>v${Number(p.revision)}</td><td class="${Math.abs(Number(p.source_trial_balance_difference||0))>.01?'danger':'ok'}">${money(p.source_trial_balance_difference)}</td><td class="${Number(p.unmapped_nonzero_count)>0?'danger':'ok'}">${Number(p.unmapped_nonzero_count||0)}</td><td>${Number(p.closed_coverage_days||0)}/${Number(p.required_coverage_days||0)} days</td><td>${pill(p.status)}</td><td>${actions}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No GIFI working papers yet.</td></tr>';$$('[data-gifi-csv]').forEach(b=>b.onclick=()=>downloadGifi(b.dataset.gifiCsv));$$('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review,b.dataset.id))}
function renderPackages(){const papers=new Map(state.gifiPapers.map(x=>[x.id,x]));$('#packageRows').innerHTML=state.packages.map(p=>{const g=papers.get(p.gifi_working_paper_id);let actions=`<button class="btn secondary master-action" data-package-json="${esc(p.id)}">JSON</button>`;if(p.status==='PREPARED')actions+=` <button class="btn secondary master-action" data-review="REVIEW_PACKAGE" data-id="${esc(p.id)}">Review</button>`;if(p.status==='REVIEWED')actions+=` <button class="btn green master-action" data-review="APPROVE_PACKAGE" data-id="${esc(p.id)}">Approve</button>`;return `<tr><td><strong>${esc(p.package_number)}</strong></td><td>${esc(p.period_end)}</td><td>v${Number(p.revision)}</td><td>${esc(p.period_start)} → ${esc(p.period_end)}</td><td>${g?`${esc(g.paper_number)} · ${esc(g.status)}`:'—'}</td><td><code>${esc(String(p.snapshot_sha256||'').slice(0,12))}…</code></td><td>${pill(p.status)}</td><td>${actions}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No accountant packages yet.</td></tr>';$$('[data-package-json]').forEach(b=>b.onclick=()=>downloadPackage(b.dataset.packageJson));$$('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review,b.dataset.id))}
function latestEvidenceName(id){const o=state.obligations.find(x=>x.id===id);return o?.title||id}
function renderEvidence(){const rows=state.evidence;$('#evidenceCount').textContent=`${rows.length} evidence row(s)`;$('#evidenceRows').innerHTML=rows.map(e=>`<tr><td>${dt(e.recorded_at)}</td><td>${esc(latestEvidenceName(e.obligation_id))}${e.supersedes_evidence_id?'<br><span class="pill amber">CORRECTION</span>':''}</td><td>${esc(e.evidence_type)}</td><td>${pill(e.final_status)}</td><td><strong>${esc(e.confirmation_reference)}</strong></td><td>${dt(e.filed_or_paid_at)}</td><td>${e.amount==null?'—':money(e.amount)}</td><td>${esc(e.document_reference||'—')}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No filing or payment evidence.</td></tr>'}
function renderApprovals(){const rows=state.approvals;$('#approvalCount').textContent=`${rows.length} action(s)`;$('#approvalRows').innerHTML=rows.map(a=>`<tr><td>${dt(a.occurred_at)}</td><td>${esc(a.object_type)}<br><span class="small">${esc(a.object_id)}</span></td><td>${pill(a.action)}</td><td>${esc(a.actor_id||'System')}</td><td>${esc(a.comment||'—')}${a.metadata&&Object.keys(a.metadata).length?`<br><span class="small">${esc(JSON.stringify(a.metadata))}</span>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No compliance approvals yet.</td></tr>'}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});state=j.data;render();status('Saved.');return j}
function openSettings(){const f=$('#settingsForm'),s=state.settings||{};f.reset();f.elements.gst_reporting_frequency.value=s.gst_reporting_frequency||'UNCONFIGURED';f.elements.federal_balance_due_months.value=String(s.federal_balance_due_months||2);f.elements.alberta_balance_due_months.value=String(s.alberta_balance_due_months||2);f.elements.three_month_balance_due_basis.value=s.three_month_balance_due_basis||'';for(const k of ['t2_enabled','at1_enabled','gst_hst_enabled','payroll_remittance_enabled','t4_enabled','accountant_package_enabled'])f.elements[k].checked=s[k]!==false;f.elements.notes.value=s.notes||'';open('settingsModal')}
function mappableCodes(){return state.gifiCodes.filter(x=>!['TOTAL_CONTROL','RETAINED_EARNINGS'].includes(x.statement_section))}
function openMapping(id){const a=state.accounts.find(x=>x.id===id);if(!a)return;const f=$('#mappingForm'),m=a.gifi_mapping;f.reset();f.elements.account_id.value=id;f.elements.gifi_code.innerHTML='<option value="">Select verified GIFI code</option>'+mappableCodes().map(g=>`<option value="${esc(g.code)}">${esc(g.code)} · ${esc(g.name)}</option>`).join('');f.elements.gifi_code.value=m?.gifi_code||'';f.elements.sign_multiplier.value=String(m?.sign_multiplier??1);f.elements.mapping_note.value=m?.mapping_note||'';$('#mappingAccountName').textContent=`${a.code} · ${a.name} · ${a.account_type}`;open('mappingModal')}
function openReview(action,id){reviewContext={action,id};const isG=action.includes('GIFI'),approve=action.startsWith('APPROVE');$('#reviewTitle').textContent=`${approve?'Approve':'Review'} ${isG?'GIFI Working Paper':'Accountant Package'}`;$('#reviewTarget').textContent=id;const f=$('#reviewForm');f.reset();f.elements.action.value=action;f.elements.object_id.value=id;open('reviewModal')}
async function advance(id,action){try{let comment='';if(['REVIEW','APPROVE'].includes(action)){comment=prompt(`${action} comment / evidence:`)||'';if(comment.trim().length<5){if(comment==='')return;throw Error('Comment must be at least 5 characters.')}}await post('ADVANCE_OBLIGATION',{obligation_id:id,workflow_action:action,comment})}catch(e){status(e.message,true);alert(e.message)}}
async function waive(id){const reason=prompt('Waiver reason / evidence (minimum 10 characters):')||'';if(!reason)return;try{await post('ADVANCE_OBLIGATION',{obligation_id:id,workflow_action:'WAIVE',comment:reason})}catch(e){status(e.message,true);alert(e.message)}}
function evidenceDefaults(o,f){f.elements.final_status.value=o.action_kind==='FILE'?'FILED':'PAID';f.elements.evidence_type.value=o.action_kind==='FILE'?'FILING_CONFIRMATION':o.action_kind==='REMIT'?'REMITTANCE_CONFIRMATION':'PAYMENT_CONFIRMATION';const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());f.elements.filed_or_paid_at.value=d.toISOString().slice(0,16);f.elements.accounting_document_id.innerHTML='<option value="">No linked document</option>'+state.documents.map(x=>`<option value="${esc(x.id)}">${esc(x.original_name)} · ${esc(x.document_type)}</option>`).join('')}
function openEvidence(id){const o=state.obligations.find(x=>x.id===id);if(!o)return;const f=$('#evidenceForm');f.reset();f.elements.obligation_id.value=id;evidenceDefaults(o,f);$('#evidenceTarget').textContent=`${o.title} · ${o.action_kind} · due ${o.due_date}`;open('evidenceModal')}
function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function downloadGifi(id){const p=state.gifiPapers.find(x=>x.id===id);if(!p)return;const grouped=new Map(),totals=[];for(const l of p.lines||[]){if(!l.gifi_code)continue;if(l.line_type==='DERIVED_TOTAL'){totals.push(l);continue}const cur=grouped.get(l.gifi_code)||{gifi_code:l.gifi_code,gifi_name:l.gifi_name,amount:0};cur.amount+=Number(l.amount||0);grouped.set(l.gifi_code,cur)}const rows=[...grouped.values(),...totals.map(x=>({gifi_code:x.gifi_code,gifi_name:x.gifi_name,amount:Number(x.amount||0)}))].sort((a,b)=>String(a.gifi_code).localeCompare(String(b.gifi_code)));const out=['GIFI Code,Description,Amount',...rows.map(x=>[csv(x.gifi_code),csv(x.gifi_name),Number(x.amount||0).toFixed(2)].join(','))].join('\n');download(`${p.paper_number}_${p.period_end}.csv`,'text/csv;charset=utf-8',out)}
function downloadPackage(id){const p=state.packages.find(x=>x.id===id);if(!p)return;download(`${p.package_number}_${p.period_end}.json`,'application/json;charset=utf-8',JSON.stringify({package_number:p.package_number,tax_year_end_year:p.tax_year_end_year,period_start:p.period_start,period_end:p.period_end,revision:p.revision,status:p.status,snapshot_sha256:p.snapshot_sha256,snapshot:p.snapshot_json},null,2))}
async function load(){try{status('Loading Accountant & Compliance Center…');const j=await api();state=j.data;const y=currentYear();if(!$('#calendarYear').value)$('#calendarYear').value=y;if(!$('#gifiYear').value)$('#gifiYear').value=y;render();status('')}catch(e){status(e.message,true);alert(e.message)}}
$$('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#settingsBtn').onclick=openSettings;$('#calendarYear').onchange=renderObligations;$('#generateCalendarBtn').onclick=async()=>{try{await post('GENERATE_CALENDAR',{year:Number($('#calendarYear').value)})}catch(e){status(e.message,true);alert(e.message)}};$('#generateGifiBtn').onclick=async()=>{try{await post('GENERATE_GIFI',{tax_year_end_year:Number($('#gifiYear').value)})}catch(e){status(e.message,true);alert(e.message)}};$('#packageBtn').onclick=async()=>{const year=Number($('#gifiYear').value||currentYear());if(!confirm(`Generate a new immutable Accountant Package revision for fiscal year-end ${year}?`))return;try{await post('GENERATE_PACKAGE',{tax_year_end_year:year})}catch(e){status(e.message,true);alert(e.message)}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_SETTINGS',{gst_reporting_frequency:f.elements.gst_reporting_frequency.value,federal_balance_due_months:Number(f.elements.federal_balance_due_months.value),alberta_balance_due_months:Number(f.elements.alberta_balance_due_months.value),three_month_balance_due_basis:f.elements.three_month_balance_due_basis.value,t2_enabled:f.elements.t2_enabled.checked,at1_enabled:f.elements.at1_enabled.checked,gst_hst_enabled:f.elements.gst_hst_enabled.checked,payroll_remittance_enabled:f.elements.payroll_remittance_enabled.checked,t4_enabled:f.elements.t4_enabled.checked,accountant_package_enabled:f.elements.accountant_package_enabled.checked,notes:f.elements.notes.value});close('settingsModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#mappingForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_GIFI_MAPPING',{account_id:f.elements.account_id.value,gifi_code:f.elements.gifi_code.value,sign_multiplier:Number(f.elements.sign_multiplier.value),mapping_note:f.elements.mapping_note.value});close('mappingModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#reviewForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,action=f.elements.action.value,id=f.elements.object_id.value;try{const payload=action.includes('GIFI')?{working_paper_id:id,comment:f.elements.comment.value}:{package_id:id,comment:f.elements.comment.value};await post(action,payload);close('reviewModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#evidenceForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{if(!confirm('Record this immutable external filing/payment evidence?'))return;await post('RECORD_EVIDENCE',{obligation_id:f.elements.obligation_id.value,final_status:f.elements.final_status.value,evidence_type:f.elements.evidence_type.value,filed_or_paid_at:new Date(f.elements.filed_or_paid_at.value).toISOString(),confirmation_reference:f.elements.confirmation_reference.value,method:f.elements.method.value,amount:f.elements.amount.value,accounting_document_id:f.elements.accounting_document_id.value||null,document_reference:f.elements.document_reference.value,notes:f.elements.notes.value,supersedes_evidence_id:f.elements.supersedes_evidence_id.value||null});close('evidenceModal')}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
