(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0)),today=()=>new Date().toISOString().slice(0,10);
let state={expenses:[],operationalExpenses:[],vendors:[],payees:[],accounts:[],taxCodes:[],financialAccounts:[],inventoryItems:[],inventoryLocations:[],counts:{}};
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-expenses',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Expenses backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Expenses request failed.');return j}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}function option(v,l){return `<option value="${esc(v)}">${esc(l)}</option>`}function partyName(p){return p?.display_name||p?.legal_name||p?.party_number||'—'}
function pill(s){const c=s==='PAID'?'green':s==='VOID'||s==='REJECTED'?'wine':s==='APPROVED'?'amber':s==='SUBMITTED'?'amber':s==='POSTED'?'blue':'blue';return `<span class="pill ${c}">${esc(s)}</span>`}
function receiptPill(x){const c=x.receipt_status==='ATTACHED'?'green':x.receipt_status==='WAIVED'?'amber':'wine';return `<span class="pill ${c}">${esc(x.receipt_status)}</span>`}
function fillSelects(){const f=$('#advancedExpenseForm');if(!f)return;f.elements.vendor_party_id.innerHTML='<option value="">Not in master / receipt only</option>'+state.vendors.map(p=>option(p.id,`${p.party_number} · ${partyName(p)}`)).join('');f.elements.payee_party_id.innerHTML='<option value="">Select employee / contractor</option>'+state.payees.map(p=>option(p.id,`${p.party_number} · ${partyName(p)}`)).join('');f.elements.financial_account_id.innerHTML='<option value="">Select financial account</option>'+state.financialAccounts.map(x=>option(x.id,`${x.name} · ${x.gl_account?.code||''} ${x.gl_account?.name||''}`)).join('');const rf=$('#reimburseForm');if(rf)rf.elements.financial_account_id.innerHTML='<option value="">Select financial account</option>'+state.financialAccounts.map(x=>option(x.id,`${x.name} · ${x.gl_account?.code||''} ${x.gl_account?.name||''}`)).join('')}
function workflowButtons(x){const a=[];if(['DRAFT','REJECTED'].includes(x.status))a.push(`<button class="btn secondary master-action" data-edit="${x.id}">Edit</button><button class="btn green master-action" data-act="SUBMIT" data-id="${x.id}">Submit</button>`);if(x.status==='SUBMITTED')a.push(`<button class="btn green master-action" data-act="APPROVE" data-id="${x.id}">Approve</button><button class="btn wine master-action" data-act="REJECT" data-id="${x.id}">Reject</button>`);if(x.status==='APPROVED')a.push(`<button class="btn orange master-action" data-act="POST" data-id="${x.id}">Post</button><button class="btn wine master-action" data-act="REJECT" data-id="${x.id}">Reject</button>`);if(x.receipt_document_id)a.push(`<button class="btn secondary master-action" data-doc="${x.receipt_document_id}">Receipt</button>`);if(x.payment_mode==='REIMBURSEMENT'&&x.status==='POSTED'&&Number(x.reimbursement_balance)>0)a.push(`<button class="btn green master-action" data-reimburse="${x.id}">Reimburse</button>`);return `<div class="actions ap-row-actions">${a.join('')}</div>`}
function render(){const c=state.counts||{};$('#kSubmitted').textContent=c.submitted||0;$('#kApproved').textContent=c.approved||0;$('#kUnreimbursed').textContent=money(c.unreimbursed||0);$('#kMissing').textContent=c.missingReceipts||0;const st=$('#statusFilter').value||'';const rows=(state.expenses||[]).filter(x=>!st||x.status===st);$('#expenseRows').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.expense_number)}</strong><br><span class="small">${esc(x.description||'')}</span></td><td>${esc(x.expense_date)}</td><td>${esc(partyName(x.vendor)||partyName(x.payee))}</td><td>${esc(x.payment_mode)}</td><td>${receiptPill(x)}</td><td>${money(x.subtotal)}</td><td>${money(x.recoverable_tax)}</td><td><strong>${money(x.total)}</strong>${x.payment_mode==='REIMBURSEMENT'&&Number(x.amount_reimbursed)>0?`<br><span class="small">Reimbursed ${money(x.amount_reimbursed)}</span>`:''}</td><td>${pill(x.status)}</td><td>${workflowButtons(x)}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No advanced expenses match this filter.</td></tr>';const op=state.operationalExpenses||[];$('#operationalExpenseRows').innerHTML=op.map(x=>`<tr><td>${esc(x.expense_number)}</td><td>${esc(x.expense_date)}</td><td>${esc(x.description||x.source_reference||'Provider expense')}</td><td>${money(x.subtotal)}</td><td>${money(x.tax_total)}</td><td>${money(x.total)}</td><td>${pill(x.status)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No operational provider expenses recorded.</td></tr>';bindRows()}
function eligibleAccounts(classification='EXPENSE'){const c=String(classification||'EXPENSE').toUpperCase();if(c==='EXPENSE')return state.accounts.filter(a=>a.account_type==='EXPENSE');if(c==='PREPAID')return state.accounts.filter(a=>a.account_type==='ASSET'&&(a.account_subtype==='PREPAID'||a.code==='1400'));if(c==='FIXED_ASSET')return state.accounts.filter(a=>a.account_type==='ASSET'&&(a.account_subtype==='FIXED_ASSET'||a.code==='1500'));if(c==='INVENTORY')return state.accounts.filter(a=>a.account_type==='ASSET'&&(a.account_subtype==='INVENTORY'||a.code==='1600'));return []}
function accountOptions(selected='',classification='EXPENSE'){return '<option value="">GL account</option>'+eligibleAccounts(classification).map(a=>`<option value="${esc(a.id)}" ${a.id===selected?'selected':''}>${esc(a.code+' · '+a.name+' ('+a.account_type+')')}</option>`).join('')}
function taxOptions(selected=''){return '<option value="">No tax</option>'+state.taxCodes.map(t=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.code+' · '+(Number(t.federal_rate||0)+Number(t.provincial_rate||0))+'%')}</option>`).join('')}
function inventoryItemOptions(selected=''){return '<option value="">— Item —</option>'+state.inventoryItems.map(i=>`<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.sku+' · '+i.name)}</option>`).join('')}
function inventoryLocationOptions(selected=''){return '<option value="">— Location —</option>'+state.inventoryLocations.map(l=>`<option value="${esc(l.id)}" ${l.id===selected?'selected':''}>${esc(l.code+' · '+l.name)}</option>`).join('')}
function toggleInventory(tr){const isInv=tr.querySelector('[data-k=classification]').value==='INVENTORY',it=tr.querySelector('[data-k=inventory_item_id]'),loc=tr.querySelector('[data-k=inventory_location_id]');it.disabled=loc.disabled=!isInv;it.required=loc.required=isInv;if(!isInv){it.value='';loc.value=''}}
function addLine(line={}){const tr=document.createElement('tr');tr.className='expense-line';tr.innerHTML=`<td><input data-k="description" value="${esc(line.description||'')}" placeholder="Expense line"></td><td><select data-k="classification"><option ${line.classification==='EXPENSE'?'selected':''}>EXPENSE</option><option ${line.classification==='PREPAID'?'selected':''}>PREPAID</option><option ${line.classification==='FIXED_ASSET'?'selected':''}>FIXED_ASSET</option><option ${line.classification==='INVENTORY'?'selected':''}>INVENTORY</option></select></td><td><input data-k="quantity" type="number" min="0.0001" step="0.0001" value="${esc(line.quantity||1)}"></td><td><input data-k="unit_price" type="number" min="0" step="0.01" value="${esc(line.unit_price||0)}"></td><td><select data-k="posting_account_id">${accountOptions(line.posting_account_id||'',line.classification||'EXPENSE')}</select></td><td><select data-k="inventory_item_id">${inventoryItemOptions(line.inventory_item_id||'')}</select></td><td><select data-k="inventory_location_id">${inventoryLocationOptions(line.inventory_location_id||'')}</select></td><td><select data-k="tax_code_id">${taxOptions(line.tax_code_id||'')}</select></td><td><select data-k="itc_eligibility"><option ${line.itc_eligibility==='FULL'?'selected':''}>FULL</option><option ${line.itc_eligibility==='PARTIAL'?'selected':''}>PARTIAL</option><option ${line.itc_eligibility==='NONE'?'selected':''}>NONE</option><option ${line.itc_eligibility==='MANUAL'?'selected':''}>MANUAL</option></select></td><td><input data-k="recoverable_percent" type="number" min="0" max="100" step="0.01" value="${esc(line.recoverable_percent??100)}"></td><td data-sub>$0.00</td><td data-tax>$0.00</td><td data-total>$0.00</td><td><button type="button" class="btn secondary master-action" data-remove>×</button></td>`;$('#expenseLineRows').appendChild(tr);tr.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',()=>{if(x.dataset.k==='classification'){const sel=tr.querySelector('[data-k=posting_account_id]'),prior=sel.value;sel.innerHTML=accountOptions(prior,x.value);if(![...sel.options].some(o=>o.value===prior))sel.value='';toggleInventory(tr)}normalizeITC(tr);calc()}));tr.querySelector('[data-remove]').onclick=()=>{if(document.querySelectorAll('.expense-line').length>1)tr.remove();calc()};toggleInventory(tr);normalizeITC(tr);calc()}
function taxFor(id){return state.taxCodes.find(x=>x.id===id)}function normalizeITC(tr){const el=tr.querySelector('[data-k=itc_eligibility]'),pct=tr.querySelector('[data-k=recoverable_percent]');if(el.value==='FULL'){pct.value=100;pct.disabled=true}else if(el.value==='NONE'){pct.value=0;pct.disabled=true}else pct.disabled=false}
function calc(){let sub=0,tax=0,itc=0;document.querySelectorAll('.expense-line').forEach(tr=>{const q=Number(tr.querySelector('[data-k=quantity]').value||0),p=Number(tr.querySelector('[data-k=unit_price]').value||0),s=Math.round(q*p*100)/100,tc=taxFor(tr.querySelector('[data-k=tax_code_id]').value),rate=tc?Number(tc.federal_rate||0)+Number(tc.provincial_rate||0):0,t=Math.round(s*rate)/100,pct=Number(tr.querySelector('[data-k=recoverable_percent]').value||0),r=Math.round(t*pct)/100;sub+=s;tax+=t;itc+=r;tr.querySelector('[data-sub]').textContent=money(s);tr.querySelector('[data-tax]').textContent=money(t);tr.querySelector('[data-total]').textContent=money(s+t)});$('#expenseSubtotal').textContent=money(sub);$('#expenseTax').textContent=money(tax);$('#expenseITC').textContent=money(itc);$('#expenseTotal').textContent=money(sub+tax)}
function setMode(){const f=$('#advancedExpenseForm'),re=f.elements.payment_mode.value==='REIMBURSEMENT';document.querySelector('[data-company-paid]').style.display=re?'none':'';document.querySelector('[data-reimbursement]').style.display=re?'':'none'}
function resetExpense(x=null){const f=$('#advancedExpenseForm');f.reset();fillSelects();f.elements.id.value=x?.id||'';f.elements.expense_date.value=x?.expense_date||today();f.elements.posting_date.value=x?.posting_date||x?.expense_date||today();f.elements.vendor_party_id.value=x?.vendor_party_id||'';f.elements.payment_mode.value=x?.payment_mode||'COMPANY_PAID';f.elements.financial_account_id.value=x?.financial_account_id||'';f.elements.payee_party_id.value=x?.payee_party_id||'';f.elements.currency.value=x?.currency||'CAD';f.elements.reference.value=x?.reference||'';f.elements.department.value=x?.department||'';f.elements.project_reference.value=x?.project_reference||'';f.elements.description.value=x?.description||'';f.elements.business_purpose.value=x?.business_purpose||'';f.elements.receipt_waiver_reason.value=x?.receipt_waiver_reason||'';$('#receiptFile').value='';$('#expenseModalTitle').textContent=x?`Edit ${x.expense_number}`:'New Expense';$('#expenseLineRows').innerHTML='';(x?.lines?.length?x.lines:[{}]).forEach(addLine);setMode();calc()}
function linePayload(){return [...document.querySelectorAll('.expense-line')].map(tr=>({description:tr.querySelector('[data-k=description]').value,classification:tr.querySelector('[data-k=classification]').value,quantity:tr.querySelector('[data-k=quantity]').value,unit_price:tr.querySelector('[data-k=unit_price]').value,posting_account_id:tr.querySelector('[data-k=posting_account_id]').value,inventory_item_id:tr.querySelector('[data-k=inventory_item_id]').value,inventory_location_id:tr.querySelector('[data-k=inventory_location_id]').value,tax_code_id:tr.querySelector('[data-k=tax_code_id]').value,itc_eligibility:tr.querySelector('[data-k=itc_eligibility]').value,recoverable_percent:tr.querySelector('[data-k=recoverable_percent]').value}))}
async function post(action,payload){const j=await api({method:'POST',body:JSON.stringify({action,payload})});state=j.data;fillSelects();render();return j}
async function uploadReceipt(expenseId,file){if(!file)return;const r=await fetch(`/.netlify/functions/cal-expense-document-upload?expense_id=${encodeURIComponent(expenseId)}`,{method:'POST',credentials:'same-origin',headers:{'content-type':file.type,'x-file-name':encodeURIComponent(file.name)},body:file}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Receipt upload returned non-JSON.')}if(!r.ok)throw Error(j.error||'Receipt upload failed.')}
async function openDoc(id){try{const r=await fetch('/.netlify/functions/cal-expense-document-url',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({document_id:id})}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not open document.');window.open(j.url,'_blank','noopener')}catch(e){alert(e.message)}}
async function actionExpense(id,action){let reason=null;if(action==='REJECT'){reason=prompt('Reason for rejection:');if(!reason)return}const msg={SUBMIT:'Submit this expense for approval?',APPROVE:'Approve this expense?',POST:'Post this expense to the General Ledger?',VOID:'Void this unposted expense?'}[action]||'Continue?';if(action!=='REJECT'&&!confirm(msg))return;try{await post('EXPENSE_ACTION',{id,expense_action:action,reason})}catch(e){alert(e.message)}}
function reimburse(x){const f=$('#reimburseForm');f.reset();fillSelects();f.elements.expense_claim_id.value=x.id;f.elements.payment_date.value=today();f.elements.amount.value=Number(x.reimbursement_balance||0).toFixed(2);$('#reimburseInfo').textContent=`${x.expense_number} · ${partyName(x.payee)} · Remaining ${money(x.reimbursement_balance)}`;open('reimburseModal')}
function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{resetExpense(state.expenses.find(x=>x.id===b.dataset.edit));open('expenseModal')});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>actionExpense(b.dataset.id,b.dataset.act));document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));document.querySelectorAll('[data-reimburse]').forEach(b=>b.onclick=()=>reimburse(state.expenses.find(x=>x.id===b.dataset.reimburse)))}
async function load(){try{const j=await api();state=j.data;fillSelects();render()}catch(e){alert(e.message)}}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));$('#newExpenseBtn').onclick=()=>{resetExpense();open('expenseModal')};$('#addExpenseLine').onclick=()=>addLine();$('#statusFilter').onchange=render;$('#advancedExpenseForm').elements.payment_mode.onchange=setMode;
$('#advancedExpenseForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{const j=await post('SAVE_EXPENSE',{id:f.elements.id.value||null,expense_date:f.elements.expense_date.value,posting_date:f.elements.posting_date.value,vendor_party_id:f.elements.vendor_party_id.value,payee_party_id:f.elements.payee_party_id.value,payment_mode:f.elements.payment_mode.value,financial_account_id:f.elements.financial_account_id.value,currency:f.elements.currency.value,reference:f.elements.reference.value,description:f.elements.description.value,business_purpose:f.elements.business_purpose.value,department:f.elements.department.value,project_reference:f.elements.project_reference.value,receipt_waiver_reason:f.elements.receipt_waiver_reason.value,lines:linePayload()});const id=j.result?.id,file=$('#receiptFile').files?.[0];if(file&&id){await uploadReceipt(id,file);const fresh=await api();state=fresh.data;fillSelects();render()}close('expenseModal')}catch(err){alert(err.message)}};
$('#reimburseForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('RECORD_REIMBURSEMENT',{expense_claim_id:f.elements.expense_claim_id.value,payment_date:f.elements.payment_date.value,financial_account_id:f.elements.financial_account_id.value,amount:f.elements.amount.value,method:f.elements.method.value,reference:f.elements.reference.value,notes:f.elements.notes.value});close('reimburseModal')}catch(err){alert(err.message)}};
load();
})();
