(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const pct=n=>`${(Number(n||0)*100).toFixed(Number(n||0)*100%1?2:0)}%`;
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={assets:[],ccaClasses:[],depreciationRuns:[],parties:[],financialAccounts:[],ccaWorkingPapers:[],metrics:{}},selectedAsset=null,selectedCca=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-fixed-assets',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Fixed Assets backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Fixed Assets request failed.');return j}
function status(msg,bad=false){const el=$('#fixedAssetsStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function partyName(p){return p?.display_name||p?.legal_name||p?.party_number||'Party'}
function assetName(a){return `${a.asset_number} · ${a.name}`}
function pill(s){const x=String(s||'').toUpperCase(),c=x==='ACTIVE'||x==='POSTED'||x==='REVIEWED'?'green':x==='PENDING_SETUP'||x==='DRAFT'?'amber':x==='DISPOSED'?'wine':'blue';return `<span class="pill ${c}">${esc(x)}</span>`}
function partyOptions(selected=''){return '<option value="">—</option>'+state.parties.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(partyName(p))}</option>`).join('')}
function ccaOptions(selected=''){return '<option value="">No CCA class selected</option>'+state.ccaClasses.map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>Class ${esc(c.class_code)} · ${esc(c.name)} · ${pct(c.prescribed_rate)}</option>`).join('')}
function financialOptions(selected=''){return '<option value="">No proceeds / select account</option>'+state.financialAccounts.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(f.name)} · ${esc(f.financial_type)} · ${esc(f.gl_account?.code||'')}</option>`).join('')}
function sourceLabel(a){if(a.source_type==='SUPPLIER_BILL')return `Supplier Bill${a.source_reference?' · '+a.source_reference:''}`;if(a.source_type==='EXPENSE')return `Expense${a.source_reference?' · '+a.source_reference:''}`;if(a.source_type==='OPENING')return 'Opening / migration';return a.source_type||'Manual'}
function render(){const m=state.metrics||{};$('#faGross').textContent=money(m.grossCost);$('#faAccum').textContent=money(m.accumulatedDepreciation);$('#faNBV').textContent=money(m.netBookValue);$('#faPending').textContent=String(m.pendingSetup||0);$('#faGrossGL').textContent=money(m.grossGl);$('#faGrossDiff').textContent=money(m.grossDifference);$('#faAccumGL').textContent=money(m.accumGl);$('#faAccumDiff').textContent=money(m.accumDifference);const ok=Math.abs(Number(m.grossDifference||0))<=.02&&Math.abs(Number(m.accumDifference||0))<=.02;$('#faIntegrity').textContent=ok?'BALANCED':'REVIEW REQUIRED';$('#faIntegrity').className=ok?'ok':'danger';renderAssets();renderRuns();renderCca()}
function renderAssets(){const q=String($('#assetSearch')?.value||'').toLowerCase(),f=$('#assetStatus')?.value||'OPEN';let rows=state.assets.filter(a=>{if(f==='OPEN'&&!['ACTIVE','PENDING_SETUP','INACTIVE'].includes(a.status))return false;if(f!=='ALL'&&f!=='OPEN'&&a.status!==f)return false;return !q||`${a.asset_number} ${a.name} ${a.serial_number||''} ${a.category||''}`.toLowerCase().includes(q)});$('#assetRows').innerHTML=rows.map(a=>`<tr><td><strong>${esc(a.asset_number)}</strong><br><span class="small">${esc(a.purchase_date||'')}</span></td><td>${esc(a.name)}${a.serial_number?`<br><span class="small">${esc(a.serial_number)}</span>`:''}</td><td>${esc(sourceLabel(a))}</td><td>${money(a.capital_cost)}</td><td>${money(a.book_accumulated_depreciation)}</td><td><strong>${money(a.net_book_value)}</strong></td><td>${a.cca_class?`Class ${esc(a.cca_class.class_code)} · ${pct(a.cca_class.prescribed_rate)}`:'—'}</td><td>${pill(a.status)}</td><td><button class="btn secondary master-action" data-setup="${esc(a.id)}">${a.status==='PENDING_SETUP'?'Complete Setup':'View / Edit'}</button>${['ACTIVE','INACTIVE'].includes(a.status)?` <button class="btn secondary master-action" data-dispose="${esc(a.id)}">Dispose</button>`:''}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">No fixed assets match this filter.</td></tr>';$$('[data-setup]').forEach(b=>b.onclick=()=>openSetup(b.dataset.setup));$$('[data-dispose]').forEach(b=>b.onclick=()=>openDispose(b.dataset.dispose))}
function renderRuns(){$('#depRunRows').innerHTML=(state.depreciationRuns||[]).map(r=>`<tr><td><strong>${esc(r.run_number)}</strong></td><td>${esc(r.period_end)}</td><td>${(r.lines||[]).length}</td><td>${money(r.total_depreciation)}</td><td>${pill(r.status)}</td><td>${r.status==='DRAFT'?`<button class="btn green master-action" data-post-run="${esc(r.id)}">Post</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No depreciation runs yet.</td></tr>';$$('[data-post-run]').forEach(b=>b.onclick=()=>postRun(b.dataset.postRun))}
function renderCca(){const year=Number($('#ccaYear')?.value||new Date().getFullYear()),rows=(state.ccaWorkingPapers||[]).filter(x=>Number(x.tax_year)===year);$('#ccaRows').innerHTML=rows.map(w=>`<tr><td><strong>Class ${esc(w.cca_class?.class_code||'')}</strong></td><td>${pct(w.prescribed_rate)}</td><td>${money(w.opening_ucc)}</td><td>${money(w.additions)}</td><td>${money(w.disposition_reduction)}</td><td>${money(w.pre_cca_ucc)}</td><td>${money(w.rate_reference_amount)}</td><td><strong>${money(w.cca_claimed)}</strong></td><td>${money(w.closing_ucc)}</td><td>${(w.review_flags||[]).length?(w.review_flags||[]).map(x=>`<span class="pill amber">${esc(x.replaceAll('_',' '))}</span>`).join(' '):pill(w.status)}</td><td><button class="btn secondary master-action" data-edit-cca="${esc(w.id)}">Review</button></td></tr>`).join('')||'<tr><td colspan="11" class="empty">Generate the selected tax year to prepare CCA/UCC continuity.</td></tr>';$$('[data-edit-cca]').forEach(b=>b.onclick=()=>openCcaEdit(b.dataset.editCca))}
function fillSetupPolicy(f,a){f.elements.responsible_party_id.innerHTML=partyOptions(a?.responsible_party_id||'');f.elements.cca_class_id.innerHTML=ccaOptions(a?.cca_class_id||'');}
function openSetup(id){const a=state.assets.find(x=>x.id===id);if(!a)return;selectedAsset=a;const f=$('#setupForm');f.reset();f.elements.asset_id.value=a.id;f.elements.name.value=a.name||'';f.elements.category.value=a.category||'';f.elements.serial_number.value=a.serial_number||'';f.elements.location_text.value=a.location_text||'';fillSetupPolicy(f,a);f.elements.available_for_use_date.value=a.available_for_use_date||a.purchase_date||'';f.elements.depreciation_method.value=a.depreciation_method||'STRAIGHT_LINE';f.elements.depreciation_start_date.value=a.depreciation_start_date||a.available_for_use_date||'';f.elements.book_useful_life_months.value=a.book_useful_life_months||'';f.elements.residual_value.value=a.residual_value??0;f.elements.tax_capital_cost.value=a.tax_capital_cost??a.capital_cost;f.elements.tax_opening_ucc.value=a.tax_opening_ucc??0;f.elements.tax_opening_year.value=a.tax_opening_year||'';f.elements.active.value=String(a.status!=='INACTIVE');f.elements.document_reference.value=a.document_reference||'';f.elements.description.value=a.description||'';f.elements.notes.value=a.notes||'';$('#setupTitle').textContent=assetName(a);$('#setupSource').textContent=`${sourceLabel(a)} · Capital cost ${money(a.capital_cost)} · source cost is locked`;toggleDepFields(f);open('setupModal')}
function toggleDepFields(f){const none=f.elements.depreciation_method.value==='NONE';f.elements.depreciation_start_date.disabled=none;f.elements.book_useful_life_months.disabled=none;}
function resetOpening(){const f=$('#openingForm');f.reset();f.elements.responsible_party_id.innerHTML=partyOptions();f.elements.supplier_party_id.innerHTML=partyOptions();f.elements.cca_class_id.innerHTML=ccaOptions();f.elements.purchase_date.value=localToday();f.elements.available_for_use_date.value=localToday();f.elements.depreciation_start_date.value=localToday();f.elements.depreciation_method.value='STRAIGHT_LINE';f.elements.opening_accumulated_depreciation.value='0';f.elements.residual_value.value='0';f.elements.tax_opening_ucc.value='0';f.elements.tax_opening_year.value=String(new Date().getFullYear());toggleDepFields(f)}
function openDispose(id){const a=state.assets.find(x=>x.id===id);if(!a)return;selectedAsset=a;const f=$('#disposeForm');f.reset();f.elements.asset_id.value=a.id;f.elements.disposal_date.value=localToday();f.elements.proceeds.value='0';f.elements.financial_account_id.innerHTML=financialOptions();f.elements.tax_proceeds.value='0';$('#disposeTitle').textContent=`Dispose ${assetName(a)}`;$('#disposeInfo').textContent=`Current book NBV ${money(a.net_book_value)} · accumulated depreciation ${money(a.book_accumulated_depreciation)}`;open('disposeModal')}
function openCcaEdit(id){const w=state.ccaWorkingPapers.find(x=>x.id===id);if(!w)return;selectedCca=w;const f=$('#ccaEditForm');f.reset();f.elements.working_paper_id.value=w.id;f.elements.cca_claimed.value=w.cca_claimed??0;f.elements.notes.value=w.notes||'';f.elements.mark_reviewed.checked=w.status==='REVIEWED';$('#ccaEditTitle').textContent=`Class ${w.cca_class?.class_code||''} · ${w.tax_year}`;open('ccaEditModal')}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});state=j.data;render();status('Saved.');return j}
async function postRun(id){if(!confirm('Post this book depreciation run? Posted depreciation is immutable.'))return;try{await post('POST_DEPRECIATION_RUN',{run_id:id})}catch(e){status(e.message,true);alert(e.message)}}
async function load(){try{status('Loading fixed assets…');const j=await api();state=j.data;const year=$('#ccaYear');if(year&&!year.value)year.value=String(new Date().getFullYear());render();status('')}catch(e){status(e.message,true);alert(e.message)}}

$$('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#assetSearch').oninput=renderAssets;$('#assetStatus').onchange=renderAssets;$('#ccaYear').onchange=renderCca;$('#openingAssetBtn').onclick=()=>{resetOpening();open('openingModal')};$('#depreciationBtn').onclick=()=>{const f=$('#depreciationForm');f.reset();f.elements.period_end.value=localToday();open('depreciationModal')};$('#ccaBtn').onclick=()=>$('#ccaYear').focus();$('#generateCcaBtn').onclick=async()=>{try{await post('GENERATE_CCA',{tax_year:Number($('#ccaYear').value)})}catch(e){status(e.message,true);alert(e.message)}};
$('#setupForm').elements.depreciation_method.onchange=e=>toggleDepFields(e.target.form);$('#openingForm').elements.depreciation_method.onchange=e=>toggleDepFields(e.target.form);
$('#setupForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_SETUP',{asset_id:f.elements.asset_id.value,name:f.elements.name.value,description:f.elements.description.value,category:f.elements.category.value,serial_number:f.elements.serial_number.value,location_text:f.elements.location_text.value,responsible_party_id:f.elements.responsible_party_id.value||null,available_for_use_date:f.elements.available_for_use_date.value||null,depreciation_start_date:f.elements.depreciation_start_date.value||null,depreciation_method:f.elements.depreciation_method.value,book_useful_life_months:f.elements.book_useful_life_months.value||null,residual_value:f.elements.residual_value.value,cca_class_id:f.elements.cca_class_id.value||null,tax_capital_cost:f.elements.tax_capital_cost.value,tax_opening_ucc:f.elements.tax_opening_ucc.value,tax_opening_year:f.elements.tax_opening_year.value||null,document_reference:f.elements.document_reference.value,notes:f.elements.notes.value,active:f.elements.active.value==='true'});close('setupModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#openingForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{if(!confirm('Create opening asset and enqueue the opening journal?'))return;await post('CREATE_OPENING_ASSET',{name:f.elements.name.value,description:f.elements.description.value,category:f.elements.category.value,serial_number:f.elements.serial_number.value,location_text:f.elements.location_text.value,responsible_party_id:f.elements.responsible_party_id.value||null,supplier_party_id:f.elements.supplier_party_id.value||null,purchase_date:f.elements.purchase_date.value,available_for_use_date:f.elements.available_for_use_date.value||null,depreciation_start_date:f.elements.depreciation_start_date.value||null,depreciation_method:f.elements.depreciation_method.value,book_useful_life_months:f.elements.book_useful_life_months.value||null,capital_cost:f.elements.capital_cost.value,opening_accumulated_depreciation:f.elements.opening_accumulated_depreciation.value,residual_value:f.elements.residual_value.value,cca_class_id:f.elements.cca_class_id.value||null,tax_capital_cost:f.elements.tax_capital_cost.value,tax_opening_ucc:f.elements.tax_opening_ucc.value,tax_opening_year:f.elements.tax_opening_year.value||null,reference:f.elements.reference.value,document_reference:f.elements.document_reference.value,notes:f.elements.notes.value});close('openingModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#depreciationForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('CREATE_DEPRECIATION_RUN',{period_end:f.elements.period_end.value});close('depreciationModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#disposeForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,proceeds=Number(f.elements.proceeds.value||0);try{if(proceeds>0&&!f.elements.financial_account_id.value)throw Error('Select a financial account for positive disposal proceeds.');if(!confirm('Post this fixed-asset disposal? The disposal becomes immutable.'))return;await post('DISPOSE_ASSET',{asset_id:f.elements.asset_id.value,disposal_date:f.elements.disposal_date.value,proceeds:f.elements.proceeds.value,financial_account_id:f.elements.financial_account_id.value||null,tax_proceeds:f.elements.tax_proceeds.value,reference:f.elements.reference.value,notes:f.elements.notes.value});close('disposeModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#ccaEditForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_CCA',{working_paper_id:f.elements.working_paper_id.value,cca_claimed:f.elements.cca_claimed.value,notes:f.elements.notes.value,mark_reviewed:f.elements.mark_reviewed.checked});close('ccaEditModal')}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
