(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let state={};
function pill(s){const x=String(s||'').toUpperCase(),c=['HEALTHY','POSTED','PASS'].includes(x)?'green':['ATTENTION','REVIEW','PENDING','PROCESSING','RETRY','ERROR'].includes(x)?'amber':['BLOCKED','BLOCKER','DEAD_LETTER'].includes(x)?'wine':'blue';return `<span class="pill ${c}">${esc(x||'—')}</span>`}
function status(msg,bad=false){const el=$('#integrationStatus');el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-integration',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Integration backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Integration request failed.');return j}
function render(){const h=state.health||{},q=h.queue||{},e=state.engine||{};$('#integrationState').innerHTML=pill(h.status||'UNKNOWN');$('#financialContracts').textContent=String(h.financial_contracts||0);$('#missingEvents').textContent=String(h.missing_events||0);$('#deadLetters').textContent=String(q.dead_letter||0);$('#postedNoJournal').textContent=String(h.posted_without_journal||0);$('#engineSummary').innerHTML=`${pill(e.status||'UNKNOWN')} · Pending ${Number(q.pending||0)} · Processing ${Number(q.processing||0)} · Retrying ${Number(q.retrying||0)} · Posted ${Number(q.posted||0)} · Ignored ${Number(q.ignored||0)}`;renderExceptions();renderContracts();renderQueue();renderDomain()}
function renderExceptions(){const rows=state.exceptions||[];$('#exceptionCount').textContent=`${rows.length} exception(s)`;$('#exceptionRows').innerHTML=rows.map(x=>`<tr><td>${pill(x.severity)}</td><td><strong>${esc(x.issue_code)}</strong></td><td>${esc(x.event_type||'—')}<br><span class="small">${esc(x.event_key||'')}</span></td><td>${esc(x.source_table||'—')}<br><span class="small">${esc(x.source_record_id||'')}</span></td><td>${pill(x.outbox_status||'—')}</td><td>${x.journal_entry_id?`<span class="small mono">${esc(x.journal_entry_id)}</span>`:'—'}</td><td>${esc(x.details||'—')}</td><td>${x.issue_code==='DEAD_LETTER'&&x.event_key?`<button class="btn secondary master-action" data-requeue="${esc(x.event_key)}">Requeue</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No integration exceptions.</td></tr>';document.querySelectorAll('[data-requeue]').forEach(b=>b.onclick=()=>requeue(b.dataset.requeue))}
function renderContracts(){const rows=state.contracts||[];$('#contractCount').textContent=`${rows.length} active contracts`;$('#contractRows').innerHTML=rows.map(c=>`<tr><td>${Number(c.priority||0)}</td><td><strong>${esc(c.event_type)}</strong></td><td>${esc(c.domain)}</td><td>${esc(c.source_table)}</td><td>${c.route==='FINANCIAL_OUTBOX'?'<span class="pill blue">STEP 17</span>':'<span class="pill green">DOMAIN ONLY</span>'}</td><td>${esc(c.producer_kind)}<br><span class="small mono">${esc(c.producer_name)}</span></td><td>${esc(c.posting_mode)}</td><td>${esc(c.dependency_event_type||'—')}</td></tr>`).join('')}
function renderQueue(){const rows=state.recent||[];$('#queueCount').textContent=`${rows.length} recent`;$('#queueRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.updated_at?new Date(r.updated_at).toLocaleString():'—')}</td><td><strong>${esc(r.event_type)}</strong><br><span class="small mono">${esc(r.event_key)}</span></td><td>${esc(r.source_reference||r.source_record_id||'—')}</td><td>${pill(r.status)}</td><td>${Number(r.attempts||0)}</td><td>${r.cal_journal_entry_id?'<span class="pill green">LINKED</span>':'—'}</td><td class="small ${r.last_error?'danger':''}">${esc(r.last_error||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No durable events yet.</td></tr>'}
function renderDomain(){const rows=state.domainEvents||[];$('#domainCount').textContent=`${rows.length} recent`;$('#domainRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.occurred_at?new Date(r.occurred_at).toLocaleString():'—')}</td><td><strong>${esc(r.event_type)}</strong></td><td>${esc(r.source_table)}<br><span class="small">${esc(r.source_record_id||'')}</span></td><td>${esc(r.source_reference||'—')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No STEP 18.11 compliance domain events yet. New compliance actions will appear here.</td></tr>'}
async function load(){try{status('Loading integration health…');const j=await api();state=j.data||{};render();status('')}catch(e){status(e.message,true);alert(e.message)}}
async function action(name,payload={}){status('Running…');const j=await api({method:'POST',body:JSON.stringify({action:name,payload})});state=j.data||state;render();status('Completed.');return j}
async function requeue(key){if(!confirm(`Requeue dead-letter event?\n${key}\n\nThis does not bypass source documents or period locks.`))return;try{await action('REQUEUE_DEAD_LETTER',{event_key:key})}catch(e){status(e.message,true);alert(e.message)}}
$('#reconcileBtn').onclick=async()=>{if(!confirm('Reconcile source facts against STEP 17 durable events?\n\nThis recovery scan is idempotent and enqueues missing events only. It does not post journals directly.'))return;try{const j=await action('RECONCILE',{limit:300});alert(`Reconciliation scan completed.\nQueued/checked: ${j.result?.scan?.queued??0}\nErrors: ${(j.result?.scan?.errors||[]).length}`)}catch(e){status(e.message,true);alert(e.message)}};
$('#workerBtn').onclick=async()=>{if(!confirm('Run the STEP 17 worker once for currently claimable events?'))return;try{const j=await action('RUN_WORKER',{limit:100}),w=j.result?.worker||{};alert(`Worker completed.\nClaimed: ${w.claimed||0}\nPosted: ${w.posted||0}\nIgnored: ${w.ignored||0}\nRetried: ${w.retried||0}\nDead letter: ${w.dead_letter||0}`)}catch(e){status(e.message,true);alert(e.message)}};
load();})();
