(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const num=n=>new Intl.NumberFormat('en-CA',{maximumFractionDigits:4}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const newOperationKey=()=>globalThis.crypto?.randomUUID?.()||`op-${Date.now()}-${Math.random().toString(16).slice(2)}`;
let state={items:[],locations:[],movements:[],counts:[],suppliers:[],metrics:{},accounts:[]},editingCountId=null,movementOperationKey=null,transferOperationKey=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-inventory',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Inventory backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Inventory request failed.');return j}
function status(msg,bad=false){const el=$('#inventoryStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function partyName(p){return p?.display_name||p?.legal_name||p?.party_number||'Supplier'}
function itemName(i){return i?`${i.sku} · ${i.name}`:'Inventory item'}
function locName(l){return l?`${l.code} · ${l.name}`:'Location'}
function pill(s){const x=String(s||'').toUpperCase(),c=x==='POSTED'||x==='ACTIVE'?'green':x==='DRAFT'?'amber':x==='INACTIVE'||x==='VOID'?'wine':'blue';return `<span class="pill ${c}">${esc(x)}</span>`}
function itemOptions(selected=''){return '<option value="">Select inventory item</option>'+state.items.filter(x=>x.active).map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(itemName(x))}</option>`).join('')}
function locationOptions(selected=''){return '<option value="">Select location</option>'+state.locations.filter(x=>x.active).map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(locName(x))}</option>`).join('')}
function supplierOptions(selected=''){return '<option value="">No preferred supplier</option>'+state.suppliers.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(partyName(x))}</option>`).join('')}
function fillSelects(){document.querySelectorAll('select[name=item_id]').forEach(s=>{const v=s.value;s.innerHTML=itemOptions(v)});document.querySelectorAll('select[name=location_id]').forEach(s=>{const v=s.value;s.innerHTML=locationOptions(v)});document.querySelectorAll('select[name=from_location_id],select[name=to_location_id]').forEach(s=>{const v=s.value;s.innerHTML=locationOptions(v)});const sp=$('#itemForm select[name=preferred_supplier_party_id]');if(sp){const v=sp.value;sp.innerHTML=supplierOptions(v)}}
function render(){const m=state.metrics||{};$('#invSubledger').textContent=money(m.subledgerValue);$('#invGL').textContent=money(m.glValue);$('#invDifference').textContent=money(m.difference);$('#invLowStock').textContent=String(m.lowStock||0);const diff=Math.abs(Number(m.difference||0)),int=$('#invIntegrity');int.textContent=diff<=0.02?'BALANCED':'REVIEW REQUIRED';int.className=diff<=0.02?'ok':'danger';renderItems();renderLocations();renderMovements();renderCounts();fillSelects()}
function renderItems(){const q=String($('#itemSearch')?.value||'').toLowerCase(),f=$('#itemStatus')?.value||'ACTIVE';let rows=state.items.filter(i=>{if(f==='ACTIVE'&&!i.active)return false;if(f==='LOW'&&!i.low_stock)return false;return !q||`${i.sku} ${i.name} ${i.category||''}`.toLowerCase().includes(q)});$('#inventoryRows').innerHTML=rows.map(i=>`<tr><td><strong>${esc(i.sku)}</strong></td><td>${esc(i.name)}${i.category?`<br><span class="small">${esc(i.category)}</span>`:''}</td><td>${esc(i.unit_of_measure)}</td><td>${num(i.on_hand)}</td><td>${money(i.average_unit_cost)}</td><td><strong>${money(i.inventory_value)}</strong></td><td>${num(i.reorder_point)}</td><td>${i.low_stock?'<span class="pill amber">LOW</span>':pill(i.active?'ACTIVE':'INACTIVE')}</td><td><button class="btn secondary master-action" data-view-item="${esc(i.id)}">View</button> <button class="btn secondary master-action" data-edit-item="${esc(i.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No inventory items match this filter.</td></tr>';$$('[data-view-item]').forEach(b=>b.onclick=()=>showItem(b.dataset.viewItem));$$('[data-edit-item]').forEach(b=>b.onclick=()=>editItem(b.dataset.editItem))}
function renderLocations(){$('#locationRows').innerHTML=state.locations.map(l=>`<tr><td><strong>${esc(l.code)}</strong></td><td>${esc(l.name)}</td><td>${esc(l.location_type)}</td><td>${pill(l.active?'ACTIVE':'INACTIVE')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No inventory locations.</td></tr>'}
function renderMovements(){const rows=state.movements||[];$('#movementCount').textContent=`${rows.length} recent`;$('#movementRows').innerHTML=rows.map(m=>`<tr><td>${esc(m.movement_date)}</td><td>${esc(m.movement_number)}</td><td>${esc(m.movement_type)}</td><td>${esc(itemName(m.item))}</td><td>${esc(locName(m.location))}</td><td class="${Number(m.quantity_delta)<0?'danger':'ok'}"><strong>${Number(m.quantity_delta)>=0?'+':''}${num(m.quantity_delta)}</strong></td><td>${money(m.unit_cost)}</td><td class="${Number(m.value_delta)<0?'danger':'ok'}">${Number(m.value_delta)>=0?'+':''}${money(m.value_delta)}</td><td>${esc(m.reference||'—')}</td><td>${m.financial_event_type?'<span class="pill blue">STEP 17</span>':'<span class="pill green">SOURCE / NO GL</span>'}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No inventory movements yet.</td></tr>'}
function countVariance(c){return (c.lines||[]).reduce((n,l)=>n+Number(l.variance_value||0),0)}
function renderCounts(){$('#countRows').innerHTML=state.counts.map(c=>`<tr><td><strong>${esc(c.count_number)}</strong></td><td>${esc(locName(c.location))}</td><td>${esc(c.count_date)}</td><td class="${countVariance(c)<0?'danger':'ok'}">${money(countVariance(c))}</td><td>${pill(c.status)}</td><td>${c.status==='DRAFT'?`<button class="btn secondary master-action" data-open-count="${esc(c.id)}">Count</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No physical counts yet.</td></tr>';$$('[data-open-count]').forEach(b=>b.onclick=()=>editCount(b.dataset.openCount))}
function showItem(id){const i=state.items.find(x=>x.id===id);if(!i)return;$('#itemDetailTitle').textContent=itemName(i);$('#itemDetailSub').textContent=`${i.valuation_method} · Reorder ${num(i.reorder_point)} ${i.unit_of_measure}`;$('#itemDetailBody').innerHTML=`<div class="grid kpis inventory-detail-kpis"><div class="card kpi"><div class="label">On Hand</div><div class="value">${num(i.on_hand)}</div></div><div class="card kpi"><div class="label">Avg Cost</div><div class="value">${money(i.average_unit_cost)}</div></div><div class="card kpi"><div class="label">Value</div><div class="value">${money(i.inventory_value)}</div></div><div class="card kpi"><div class="label">Manufacturing</div><div class="value" style="font-size:18px">DISABLED</div></div></div><h4>Balances by Location</h4><div class="table-wrap"><table><thead><tr><th>Location</th><th>Qty</th><th>Avg Cost</th><th>Value</th></tr></thead><tbody>${(i.balances||[]).map(b=>`<tr><td>${esc(locName(b.location))}</td><td>${num(b.quantity_on_hand)}</td><td>${money(b.average_unit_cost)}</td><td>${money(b.inventory_value)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No stock balances yet.</td></tr>'}</tbody></table></div>`;open('itemDetailModal')}
function resetItem(i=null){const f=$('#itemForm');f.reset();f.elements.id.value=i?.id||'';f.elements.sku.value=i?.sku||'';f.elements.name.value=i?.name||'';f.elements.category.value=i?.category||'';f.elements.unit_of_measure.value=i?.unit_of_measure||'EA';f.elements.reorder_point.value=i?.reorder_point??0;f.elements.active.value=String(i?.active!==false);f.elements.description.value=i?.description||'';f.elements.preferred_supplier_party_id.innerHTML=supplierOptions(i?.preferred_supplier_party_id||'');$('#itemModalTitle').textContent=i?'Edit Inventory Item':'New Inventory Item'}
function editItem(id){const i=state.items.find(x=>x.id===id);resetItem(i);open('itemModal')}
function resetLocation(l=null){const f=$('#locationForm');f.reset();f.elements.id.value=l?.id||'';f.elements.code.value=l?.code||'';f.elements.name.value=l?.name||'';f.elements.location_type.value=l?.location_type||'WAREHOUSE';f.elements.active.value=String(l?.active!==false);f.elements.address.value=l?.address||'';$('#locationModalTitle').textContent=l?'Edit Inventory Location':'New Inventory Location'}
function openMovement(action){movementOperationKey=newOperationKey();const f=$('#movementForm');f.reset();fillSelects();f.elements.action.value=action;f.elements.movement_date.value=today();const titles={OPENING:'Opening Inventory Balance',ISSUE:'Issue Inventory',ADJUSTMENT_GAIN:'Inventory Adjustment Gain',ADJUSTMENT_LOSS:'Inventory Adjustment Loss'},helps={OPENING:'Use only before the first movement for an item/location. Posts Dr Inventory / Cr Equity.',ISSUE:'Reduces inventory at current moving-average cost and posts COGS.',ADJUSTMENT_GAIN:'Controlled increase. Posts Dr Inventory / Cr Inventory Adjustments.',ADJUSTMENT_LOSS:'Controlled decrease. Posts Dr Inventory Adjustments / Cr Inventory.'};$('#movementModalTitle').textContent=titles[action]||'Inventory Movement';$('#movementHelp').textContent=helps[action]||'';const cost=$('[data-unit-cost]');cost.style.display=['OPENING','ADJUSTMENT_GAIN'].includes(action)?'':'none';if(action==='ADJUSTMENT_LOSS')f.elements.reason.required=true;else f.elements.reason.required=['ADJUSTMENT_GAIN'].includes(action);open('movementModal')}
function openTransfer(){transferOperationKey=newOperationKey();const f=$('#transferForm');f.reset();fillSelects();f.elements.transfer_date.value=today();open('transferModal')}
function newCount(){editingCountId=null;const f=$('#countForm');f.reset();fillSelects();f.elements.count_date.value=today();$('#countCreate').hidden=false;$('#countEditor').hidden=true;$('#countModalTitle').textContent='New Physical Count';open('countModal')}
function editCount(id){const c=state.counts.find(x=>x.id===id);if(!c)return;editingCountId=id;$('#countCreate').hidden=true;$('#countEditor').hidden=false;$('#countModalTitle').textContent=`${c.count_number} · ${locName(c.location)}`;$('#countInfo').textContent=`System quantities are refreshed when each counted quantity is saved. Post only after every active item has been counted.`;$('#countLineRows').innerHTML=(c.lines||[]).map(l=>`<tr><td>${esc(l.item?.sku||'')}</td><td>${esc(l.item?.name||'')}</td><td>${num(l.system_quantity)}</td><td><input data-count-item="${esc(l.item_id)}" type="number" min="0" step="0.0001" value="${l.counted_quantity??''}"></td><td>${l.variance_quantity==null?'—':num(l.variance_quantity)}</td><td>${money(l.unit_cost)}</td><td>${l.variance_value==null?'—':money(l.variance_value)}</td></tr>`).join('');$$('[data-count-item]').forEach(inp=>inp.onchange=()=>saveCountLine(inp.dataset.countItem,inp.value));open('countModal')}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});state=j.data;render();status('Saved.');return j}
async function saveCountLine(itemId,value){try{await post('SAVE_COUNT_LINE',{count_id:editingCountId,item_id:itemId,counted_quantity:value});editCount(editingCountId)}catch(e){status(e.message,true);alert(e.message)}}
async function load(){try{status('Loading inventory…');const j=await api();state=j.data;render();status('')}catch(e){status(e.message,true);alert(e.message)}}

$$('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#newItemBtn').onclick=()=>{resetItem();open('itemModal')};$('#newLocationBtn').onclick=()=>{resetLocation();open('locationModal')};$('#openingBtn').onclick=()=>openMovement('OPENING');$('#issueBtn').onclick=()=>openMovement('ISSUE');$('#transferBtn').onclick=openTransfer;$('#adjustBtn').onclick=()=>{const gain=confirm('OK = Adjustment GAIN\nCancel = Adjustment LOSS');openMovement(gain?'ADJUSTMENT_GAIN':'ADJUSTMENT_LOSS')};$('#countBtn').onclick=newCount;$('#itemSearch').oninput=renderItems;$('#itemStatus').onchange=renderItems;
$('#itemForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_ITEM',{id:f.elements.id.value||null,sku:f.elements.sku.value,name:f.elements.name.value,description:f.elements.description.value,category:f.elements.category.value,unit_of_measure:f.elements.unit_of_measure.value,preferred_supplier_party_id:f.elements.preferred_supplier_party_id.value||null,reorder_point:f.elements.reorder_point.value,active:f.elements.active.value==='true'});close('itemModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#locationForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_LOCATION',{id:f.elements.id.value||null,code:f.elements.code.value,name:f.elements.name.value,location_type:f.elements.location_type.value,address:f.elements.address.value,active:f.elements.active.value==='true'});close('locationModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#movementForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,action=f.elements.action.value;try{if(!confirm(`Post ${action.replaceAll('_',' ')}? Inventory movements are immutable.`))return;await post(action,{item_id:f.elements.item_id.value,location_id:f.elements.location_id.value,movement_date:f.elements.movement_date.value,quantity:f.elements.quantity.value,unit_cost:f.elements.unit_cost.value,reference:f.elements.reference.value,reason:f.elements.reason.value,project_reference:f.elements.project_reference.value,operation_key:movementOperationKey});movementOperationKey=null;close('movementModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#transferForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('TRANSFER',{item_id:f.elements.item_id.value,from_location_id:f.elements.from_location_id.value,to_location_id:f.elements.to_location_id.value,transfer_date:f.elements.transfer_date.value,quantity:f.elements.quantity.value,reference:f.elements.reference.value,reason:f.elements.reason.value,operation_key:transferOperationKey});transferOperationKey=null;close('transferModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#countForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{const j=await post('CREATE_COUNT',{location_id:f.elements.location_id.value,count_date:f.elements.count_date.value,reference:f.elements.reference.value,notes:f.elements.notes.value});editingCountId=j.result?.id;editCount(editingCountId)}catch(err){status(err.message,true);alert(err.message)}};
$('#postCountBtn').onclick=async()=>{if(!editingCountId||!confirm('Post this physical count? Variance adjustments will become immutable and accounting events will be created.'))return;try{await post('POST_COUNT',{count_id:editingCountId});close('countModal');editingCountId=null}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
