(function(){
const ENDPOINT=((window.LAC_CONFIG&&window.LAC_CONFIG.apiBase)||'/.netlify/functions')+'/cal-master-data';
const ROLE_LIST=['CUSTOMER','OPERATIONAL_PROVIDER','SUPPLIER','EMPLOYEE','CONTRACTOR','OTHER'];
let state={parties:[],accounts:[],taxCodes:[],financialAccounts:[],counts:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const truth=v=>v===true||String(v).toLowerCase()==='true';
const setText=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};
const status=(msg,bad=false)=>{const e=document.getElementById('masterStatus');if(e){e.textContent=msg||'';e.className='small master-status '+(bad?'danger':'ok')}};
const open=id=>document.getElementById(id)?.classList.add('open');
const close=id=>document.getElementById(id)?.classList.remove('open');
async function api(method='GET',body){
  const r=await fetch(ENDPOINT,{method,credentials:'same-origin',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
  const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{j={error:'CAL master-data endpoint returned an invalid response.'}}
  if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.');}
  if(!r.ok)throw Error(j.error||'Unable to load financial master data.');
  return j;
}
function activeRoles(p){return (p.roles||[]).filter(r=>r.active).map(r=>r.role)}
function rolePills(p){return activeRoles(p).map(r=>`<span class="pill ${r==='SUPPLIER'?'amber':r==='OPERATIONAL_PROVIDER'?'green':r==='CUSTOMER'?'blue':'wine'}">${esc(r.replaceAll('_',' '))}</span>`).join(' ')||'<span class="master-muted">—</span>'}
function renderCounts(){setText('mdPartyCount',state.counts.parties||0);setText('mdSupplierCount',state.counts.suppliers||0);setText('mdProviderCount',state.counts.operationalProviders||0);setText('mdFinancialCount',state.counts.financialAccounts||0)}
function renderParties(){
  const body=document.getElementById('partyRows');if(!body)return;
  const q=String(document.getElementById('partySearch')?.value||'').trim().toLowerCase();const rf=String(document.getElementById('partyRoleFilter')?.value||'');
  const rows=(state.parties||[]).filter(p=>{const hay=[p.party_number,p.legal_name,p.display_name,p.email,p.phone].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!rf||activeRoles(p).includes(rf))});
  body.innerHTML=rows.map(p=>`<tr><td>${esc(p.party_number)}</td><td><strong>${esc(p.legal_name)}</strong>${p.display_name&&p.display_name!==p.legal_name?`<br><span class="small">${esc(p.display_name)}</span>`:''}</td><td>${rolePills(p)}</td><td>${esc(p.email||p.phone||'—')}</td><td><div class="master-source"><span class="pill ${p.managed_by==='PLEASE'?'blue':'green'}">${esc(p.managed_by)}</span>${p.source_table?`<span class="small">${esc(p.source_table)}</span>`:''}</div></td><td><span class="pill ${p.active?'green':'wine'}">${p.active?'ACTIVE':'INACTIVE'}</span></td><td><button class="btn secondary master-action" data-edit-party="${esc(p.id)}">${p.managed_by==='PLEASE'?'Roles':'Edit'}</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No business partners match this filter.</td></tr>';
}
function renderFinancial(){const b=document.getElementById('financialRows');if(!b)return;b.innerHTML=(state.financialAccounts||[]).map(f=>`<tr><td><strong>${esc(f.name)}</strong>${f.is_primary?' <span class="pill blue">PRIMARY</span>':''}</td><td>${esc(f.financial_type)}</td><td>${esc(f.institution_name||'—')}</td><td>${esc(f.account_last4||'—')}</td><td>${f.gl_account?`${esc(f.gl_account.code)} · ${esc(f.gl_account.name)}`:'—'}</td><td>${esc(f.currency)}</td><td><span class="pill ${f.active?'green':'wine'}">${f.active?'ACTIVE':'INACTIVE'}</span></td><td><button class="btn secondary master-action" data-edit-financial="${esc(f.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No financial accounts configured.</td></tr>'}
function renderGL(){const b=document.getElementById('glRows');if(!b)return;b.innerHTML=(state.accounts||[]).map(a=>`<tr><td>${esc(a.code)}</td><td>${esc(a.name)}</td><td>${esc(a.account_type)}</td><td>${a.system_managed?'<span class="pill blue">SYSTEM</span>':'<span class="pill green">CUSTOM</span>'} ${a.active?'':'<span class="pill wine">INACTIVE</span>'}</td><td><button class="btn secondary master-action" data-edit-account="${esc(a.id)}">${a.system_managed?'Review':'Edit'}</button></td></tr>`).join('')}
function renderTax(){const b=document.getElementById('taxRows');if(!b)return;b.innerHTML=(state.taxCodes||[]).map(t=>{const rate=Number(t.federal_rate||0)+Number(t.provincial_rate||0);return`<tr><td>${esc(t.code)}${t.system_managed?' <span class="pill blue">SYSTEM</span>':''}</td><td>${esc(t.province||'—')} · ${esc(t.tax_kind)}</td><td>${rate.toFixed(3).replace(/\.000$/,'')}%</td><td>${esc(t.effective_from)}${t.effective_to?' → '+esc(t.effective_to):''}</td><td><span class="pill ${t.active?'green':'wine'}">${t.active?'ACTIVE':'INACTIVE'}</span></td><td>${t.system_managed?'<span class="small">Protected</span>':`<button class="btn secondary master-action" data-edit-tax="${esc(t.id)}">Edit</button>`}</td></tr>`}).join('')}
function populateGLSelects(){
  const accounts=state.accounts||[];
  const financial=document.querySelector('#financialForm [name="gl_account_id"]');if(financial)financial.innerHTML='<option value="">Select GL account</option>'+accounts.filter(a=>a.active).map(a=>`<option value="${esc(a.id)}">${esc(a.code)} · ${esc(a.name)} (${esc(a.account_type)})</option>`).join('');
  const parent=document.querySelector('#accountForm [name="parent_id"]');if(parent)parent.innerHTML='<option value="">None</option>'+accounts.filter(a=>a.active).map(a=>`<option value="${esc(a.id)}">${esc(a.code)} · ${esc(a.name)}</option>`).join('');
}
function render(){renderCounts();renderParties();renderFinancial();renderGL();renderTax();populateGLSelects()}
async function load(){status('Loading Financial Master Data…');const j=await api();state=j.data||state;render();status('STEP 18.1 master data loaded. Operational PLEASE identities remain protected.')}
function buildRoleChecks(selected=[]){const c=document.getElementById('partyRoleChecks');if(!c)return;c.innerHTML=ROLE_LIST.map(r=>`<label class="role-check"><input type="checkbox" value="${r}" ${selected.includes(r)?'checked':''}> ${esc(r.replaceAll('_',' '))}</label>`).join('')}
function resetParty(){const f=document.getElementById('partyForm');f?.reset();if(f){f.elements.id.value='';f.elements.default_currency.value='CAD';f.elements.payment_terms_days.value='0';f.elements.active.value='true';if(f.elements.country)f.elements.country.value='Canada';Array.from(f.elements).forEach(e=>{if(e.name&&!['id'].includes(e.name))e.disabled=false})}buildRoleChecks(['SUPPLIER']);setText('partyModalTitle','New Business Partner');setText('partySourceNote','Create a CAL-managed supplier or other financial party.')}
function editParty(id){const p=state.parties.find(x=>x.id===id);if(!p)return;const f=document.getElementById('partyForm');resetParty();f.elements.id.value=p.id;for(const k of ['party_type','legal_name','display_name','email','phone','business_number','tax_number','default_currency','payment_terms_days','notes'])if(f.elements[k])f.elements[k].value=p[k]??'';const a=p.address||{};for(const [k,v] of Object.entries({address_line1:a.line1||'',address_line2:a.line2||'',city:a.city||'',address_province:a.province||'',postal_code:a.postal_code||'',country:a.country||'Canada'}))if(f.elements[k])f.elements[k].value=v;f.elements.active.value=String(p.active!==false);buildRoleChecks(activeRoles(p));setText('partyModalTitle',p.managed_by==='PLEASE'?'Business Partner Roles':'Edit Business Partner');setText('partySourceNote',p.managed_by==='PLEASE'?'Identity is managed by PLEASE Operations. CAL may maintain financial roles, tax IDs, payment terms and accounting notes without editing the operational identity.':'CAL-managed financial identity.');if(p.managed_by==='PLEASE')for(const k of ['party_type','legal_name','display_name','email','phone','address_line1','address_line2','city','address_province','postal_code','country','active'])if(f.elements[k])f.elements[k].disabled=true;open('partyModal')}
function resetFinancial(){const f=document.getElementById('financialForm');f?.reset();if(f){f.elements.id.value='';f.elements.currency.value='CAD';f.elements.is_primary.value='false';f.elements.active.value='true'}populateGLSelects()}
function editFinancial(id){const x=state.financialAccounts.find(v=>v.id===id);if(!x)return;const f=document.getElementById('financialForm');resetFinancial();for(const k of ['id','name','financial_type','institution_name','account_last4','currency','gl_account_id'])if(f.elements[k])f.elements[k].value=x[k]??'';f.elements.is_primary.value=String(!!x.is_primary);f.elements.active.value=String(x.active!==false);open('financialModal')}
function resetAccount(){const f=document.getElementById('accountForm');f?.reset();if(f){for(const k of ['code','account_type','active'])if(f.elements[k])f.elements[k].disabled=false;f.elements.id.value='';f.elements.allow_manual_posting.value='true';f.elements.active.value='true'}populateGLSelects()}
function resetTax(){const f=document.getElementById('taxForm');f?.reset();if(f){f.elements.id.value='';f.elements.federal_rate.value='0';f.elements.provincial_rate.value='0';f.elements.recoverable_default.value='true';f.elements.active.value='true';f.elements.effective_from.value=new Date().toISOString().slice(0,10)}}
function editAccount(id){const a=state.accounts.find(x=>x.id===id);if(!a)return;const f=document.getElementById('accountForm');resetAccount();for(const k of ['id','code','name','account_type','account_subtype','parent_id'])if(f.elements[k])f.elements[k].value=a[k]??'';f.elements.allow_manual_posting.value=String(a.allow_manual_posting!==false);f.elements.active.value=String(a.active!==false);for(const k of ['code','account_type','active'])if(f.elements[k])f.elements[k].disabled=!!a.system_managed;open('accountModal')}
function editTax(id){const t=state.taxCodes.find(x=>x.id===id);if(!t||t.system_managed)return;const f=document.getElementById('taxForm');resetTax();for(const k of ['id','code','name','tax_kind','province','federal_rate','provincial_rate','effective_from','effective_to'])if(f.elements[k])f.elements[k].value=t[k]??'';f.elements.recoverable_default.value=String(t.recoverable_default!==false);f.elements.active.value=String(t.active!==false);open('taxModal')}
function formValue(f,name){return f.elements[name]?.value??''}
async function submitParty(e){e.preventDefault();const f=e.currentTarget;const roles=Array.from(document.querySelectorAll('#partyRoleChecks input:checked')).map(x=>x.value);const payload={id:formValue(f,'id'),party_type:formValue(f,'party_type'),legal_name:formValue(f,'legal_name'),display_name:formValue(f,'display_name'),email:formValue(f,'email'),phone:formValue(f,'phone'),address_line1:formValue(f,'address_line1'),address_line2:formValue(f,'address_line2'),city:formValue(f,'city'),address_province:formValue(f,'address_province'),postal_code:formValue(f,'postal_code'),country:formValue(f,'country'),business_number:formValue(f,'business_number'),tax_number:formValue(f,'tax_number'),default_currency:formValue(f,'default_currency'),payment_terms_days:Number(formValue(f,'payment_terms_days')||0),notes:formValue(f,'notes'),active:formValue(f,'active')!=='false',roles};await save('SAVE_PARTY',payload,'Business partner saved.');close('partyModal')}
async function submitFinancial(e){e.preventDefault();const f=e.currentTarget;const payload={id:formValue(f,'id'),name:formValue(f,'name'),financial_type:formValue(f,'financial_type'),institution_name:formValue(f,'institution_name'),account_last4:formValue(f,'account_last4'),currency:formValue(f,'currency'),gl_account_id:formValue(f,'gl_account_id'),is_primary:formValue(f,'is_primary')==='true',active:formValue(f,'active')!=='false'};await save('SAVE_FINANCIAL_ACCOUNT',payload,'Financial account saved.');close('financialModal')}
async function submitAccount(e){e.preventDefault();const f=e.currentTarget;const payload={id:formValue(f,'id'),code:formValue(f,'code'),name:formValue(f,'name'),account_type:formValue(f,'account_type'),account_subtype:formValue(f,'account_subtype'),parent_id:formValue(f,'parent_id'),allow_manual_posting:formValue(f,'allow_manual_posting')==='true',active:formValue(f,'active')!=='false'};await save('SAVE_GL_ACCOUNT',payload,'GL account saved.');close('accountModal')}
async function submitTax(e){e.preventDefault();const f=e.currentTarget;const payload={id:formValue(f,'id'),code:formValue(f,'code'),name:formValue(f,'name'),tax_kind:formValue(f,'tax_kind'),province:formValue(f,'province'),federal_rate:Number(formValue(f,'federal_rate')||0),provincial_rate:Number(formValue(f,'provincial_rate')||0),recoverable_default:formValue(f,'recoverable_default')==='true',effective_from:formValue(f,'effective_from'),effective_to:formValue(f,'effective_to'),active:formValue(f,'active')!=='false'};await save('SAVE_TAX_CODE',payload,'Tax code saved.');close('taxModal')}
async function save(action,payload,msg){status('Saving…');try{const j=await api('POST',{action,payload});state=j.data||state;render();status(msg)}catch(e){status(e.message||'Unable to save master data.',true);alert(e.message||'Unable to save master data.');throw e}}
function bind(){
  buildRoleChecks(['SUPPLIER']);resetTax();
  document.getElementById('partySearch')?.addEventListener('input',renderParties);document.getElementById('partyRoleFilter')?.addEventListener('change',renderParties);
  document.getElementById('newPartyBtn')?.addEventListener('click',resetParty);document.getElementById('newFinancialBtn')?.addEventListener('click',resetFinancial);document.getElementById('addFinancialBtn')?.addEventListener('click',resetFinancial);document.getElementById('addAccountBtn')?.addEventListener('click',resetAccount);document.getElementById('addTaxBtn')?.addEventListener('click',resetTax);
  document.getElementById('partyForm')?.addEventListener('submit',e=>submitParty(e).catch(()=>{}));document.getElementById('financialForm')?.addEventListener('submit',e=>submitFinancial(e).catch(()=>{}));document.getElementById('accountForm')?.addEventListener('submit',e=>submitAccount(e).catch(()=>{}));document.getElementById('taxForm')?.addEventListener('submit',e=>submitTax(e).catch(()=>{}));
  document.addEventListener('click',e=>{const p=e.target.closest('[data-edit-party]');if(p)editParty(p.dataset.editParty);const f=e.target.closest('[data-edit-financial]');if(f)editFinancial(f.dataset.editFinancial);const ga=e.target.closest('[data-edit-account]');if(ga)editAccount(ga.dataset.editAccount);const tx=e.target.closest('[data-edit-tax]');if(tx)editTax(tx.dataset.editTax);const o=e.target.closest('[data-open]');if(o)open(o.dataset.open);const c=e.target.closest('[data-close]');if(c)close(c.dataset.close)});
}
document.addEventListener('DOMContentLoaded',()=>{bind();load().catch(e=>{console.error('master-data',e);status(e.message||'Unable to load master data.',true)})});
})();
