(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const pct=n=>`${(Number(n||0)*100).toFixed(3).replace(/\.000$/,'').replace(/0+$/,'').replace(/\.$/,'')}%`;
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={employees:[],employeeCandidates:[],runs:[],remittances:[],t4:[],parameters:[],settings:{},financialAccounts:[],metrics:{}},selectedRun=null,selectedLine=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-payroll',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Payroll backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Payroll request failed.');return j}
function status(msg,bad=false){const el=$('#payrollStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function partyName(p){return p?.display_name||p?.legal_name||p?.party_number||'Employee'}
function employeeName(e){return partyName(e?.party)||e?.employee_number||'Employee'}
function pill(s){const x=String(s||'').toUpperCase(),c=['POSTED','PAID','ACTIVE','REVIEWED'].includes(x)?'green':['DRAFT','REVIEW','ON_LEAVE'].includes(x)?'amber':['VOID','TERMINATED','INACTIVE'].includes(x)?'wine':'blue';return `<span class="pill ${c}">${esc(x)}</span>`}
function paramFor(date=localToday()){return [...(state.parameters||[])].filter(p=>p.province==='AB'&&p.effective_from<=date&&(!p.effective_to||p.effective_to>=date)).sort((a,b)=>String(b.effective_from).localeCompare(String(a.effective_from)))[0]||null}
function financialOptions(selected=''){return '<option value="">Select financial account</option>'+state.financialAccounts.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(f.name)} · ${esc(f.financial_type)}</option>`).join('')}
function employeeCandidateOptions(selected=''){return '<option value="">Select EMPLOYEE Business Partner</option>'+state.employeeCandidates.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.party_number||'')} · ${esc(partyName(p))}</option>`).join('')}
function render(){const m=state.metrics||{};$('#activeEmployees').textContent=String(m.activeEmployees||0);$('#payrollPayable').textContent=money(m.payrollPayable);$('#sourcePayable').textContent=money(m.sourceDeductionsPayable);$('#ytdGross').textContent=money(m.ytdGross);$('#remitDue').textContent=m.nextRemittanceDue?`Next CRA remittance guidance: ${m.nextRemittanceDue}`:'Current calendar year';renderRates();renderEmployees();renderRuns();renderRemittances();renderT4();}
function renderRates(){const p=paramFor();$('#rateVersion').textContent=p?`${p.engine_version} · effective ${p.effective_from}${p.effective_to?' → '+p.effective_to:''} · ${p.source_reference}`:'No effective payroll parameters';$('#rateCpp').textContent=p?`${pct(p.cpp_rate)} · max ${money(p.cpp_max_contribution)}`:'—';$('#rateCpp2').textContent=p?`${pct(p.cpp2_rate)} · max ${money(p.cpp2_max_contribution)}`:'—';$('#rateEi').textContent=p?`${pct(p.ei_rate)} · max ${money(p.ei_max_employee)}`:'—';$('#rateEiEr').textContent=p?`${pct(p.ei_employer_rate)} · max ${money(p.ei_max_employer)}`:'—';$('#rateYmpe').textContent=p?`${money(p.ympe)} / ${money(p.yampe)}`:'—';$('#remitterType').textContent=state.settings?.remitter_type||'REGULAR'}
function renderEmployees(){$('#employeeRows').innerHTML=(state.employees||[]).map(e=>`<tr><td><strong>${esc(e.employee_number)}</strong><br>${esc(employeeName(e))}${e.party?.email?`<br><span class="small">${esc(e.party.email)}</span>`:''}</td><td>${esc(e.employment_type)}</td><td>${esc(e.pay_frequency)} · ${esc(e.pay_periods_per_year)}</td><td>${e.employment_type==='SALARY'?money(e.annual_salary)+' / yr':money(e.hourly_rate)+' / hr'}</td><td>${money(e.federal_td1_claim)}</td><td>${money(e.provincial_td1_claim)}</td><td>${e.sin_on_file?`On file · ***${esc(e.sin_last4||'')}`:'Not verified'}</td><td>${pill(e.status)}</td><td><button class="btn secondary master-action" data-edit-employee="${esc(e.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No payroll employees yet. Add the EMPLOYEE role in Financial Master Data first.</td></tr>';$$('[data-edit-employee]').forEach(b=>b.onclick=()=>openEmployee(b.dataset.editEmployee))}
function renderRuns(){$('#runRows').innerHTML=(state.runs||[]).map(r=>{const deductions=Number(r.employee_cpp||0)+Number(r.employee_cpp2||0)+Number(r.employee_ei||0)+Number(r.income_tax||0)+Number(r.other_deductions||0),er=Number(r.employer_cpp||0)+Number(r.employer_cpp2||0)+Number(r.employer_ei||0);return `<tr><td><strong>${esc(r.run_number)}</strong><br><span class="small">${esc(r.pay_frequency)}</span></td><td>${esc(r.period_start)} → ${esc(r.period_end)}</td><td>${esc(r.payment_date)}</td><td>${money(r.gross_pay)}</td><td>${money(deductions)}</td><td><strong>${money(r.net_pay)}</strong></td><td>${money(er)}</td><td>${pill(r.status)}</td><td><button class="btn secondary master-action" data-view-run="${esc(r.id)}">View</button></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">No pay runs yet.</td></tr>';$$('[data-view-run]').forEach(b=>b.onclick=()=>openRun(b.dataset.viewRun))}
function renderRemittances(){$('#remittanceRows').innerHTML=(state.remittances||[]).map(r=>`<tr><td><strong>${esc(r.remittance_number)}</strong></td><td>${esc(r.period_end)}</td><td>${esc(r.remittance_date)}</td><td>${money(Number(r.employee_cpp||0)+Number(r.employer_cpp||0)+Number(r.employee_cpp2||0)+Number(r.employer_cpp2||0))}</td><td>${money(Number(r.employee_ei||0)+Number(r.employer_ei||0))}</td><td>${money(r.income_tax)}</td><td><strong>${money(r.total_remittance)}</strong></td><td>${pill(r.status)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No source-deduction remittances recorded.</td></tr>'}
function renderT4(){const year=Number($('#t4Year')?.value||new Date().getFullYear()),rows=(state.t4||[]).filter(x=>Number(x.tax_year)===year);$('#t4Rows').innerHTML=rows.map(w=>{const e=state.employees.find(x=>x.id===w.employee_id);return `<tr><td><strong>${esc(employeeName(e))}</strong><br><span class="small">SIN ***${esc(w.sin_last4||'—')}</span></td><td>${money(w.box14_employment_income)}</td><td>${money(w.box16_cpp)}</td><td>${money(w.box16a_cpp2)}</td><td>${money(w.box18_ei)}</td><td>${money(w.box22_income_tax)}</td><td>${money(w.box24_ei_insurable_earnings)}</td><td>${money(w.box26_cpp_pensionable_earnings)}</td><td>${pill(w.status)}</td><td><button class="btn secondary master-action" data-t4="${esc(w.id)}">Review</button></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">Generate the selected tax year to prepare T4 working papers.</td></tr>';$$('[data-t4]').forEach(b=>b.onclick=()=>openT4(b.dataset.t4))}
function resetEmployee(e=null){const f=$('#employeeForm');f.reset();f.elements.id.value=e?.id||'';f.elements.party_id.innerHTML=employeeCandidateOptions(e?.party_id||'');f.elements.party_id.disabled=!!e;f.elements.status.value=e?.status||'ACTIVE';f.elements.employment_type.value=e?.employment_type||'HOURLY';f.elements.pay_frequency.value=e?.pay_frequency||'BIWEEKLY';f.elements.pay_periods_per_year.value=e?.pay_periods_per_year||26;f.elements.hire_date.value=e?.hire_date||localToday();f.elements.hourly_rate.value=e?.hourly_rate||'';f.elements.annual_salary.value=e?.annual_salary||'';f.elements.overtime_multiplier.value=e?.overtime_multiplier||1.5;f.elements.termination_date.value=e?.termination_date||'';f.elements.federal_td1_claim.value=e?.federal_td1_claim??16452;f.elements.provincial_td1_claim.value=e?.provincial_td1_claim??22769;f.elements.additional_tax_per_period.value=e?.additional_tax_per_period||0;f.elements.cpp_months.value=e?.cpp_months??12;f.elements.sin_last4.value=e?.sin_last4||'';f.elements.sin_secure_document_reference.value=e?.sin_secure_document_reference||'';f.elements.federal_td1_document_reference.value=e?.federal_td1_document_reference||'';f.elements.provincial_td1_document_reference.value=e?.provincial_td1_document_reference||'';f.elements.sin_on_file.checked=!!e?.sin_on_file;f.elements.cpp_exempt.checked=!!e?.cpp_exempt;f.elements.ei_exempt.checked=!!e?.ei_exempt;f.elements.notes.value=e?.notes||'';$('#employeeTitle').textContent=e?`Edit ${e.employee_number}`:'Payroll Employee'}
function openEmployee(id=null){const e=id?state.employees.find(x=>x.id===id):null;resetEmployee(e);open('employeeModal')}
function openRun(id){const r=state.runs.find(x=>x.id===id);if(!r)return;selectedRun=r;$('#runTitle').textContent=`${r.run_number} · ${r.status}`;$('#runSub').textContent=`${r.period_start} → ${r.period_end} · Pay date ${r.payment_date} · ${r.engine_version||'No calculation version'}`;$('#runGross').textContent=money(r.gross_pay);$('#runTax').textContent=money(r.income_tax);$('#runStat').textContent=money(Number(r.employee_cpp||0)+Number(r.employee_cpp2||0)+Number(r.employee_ei||0));$('#runNet').textContent=money(r.net_pay);$('#runLineRows').innerHTML=(r.lines||[]).map(l=>`<tr><td>${esc(employeeName(l.employee))}</td><td>${money(l.gross_pay)}</td><td>${money(l.employee_cpp)}</td><td>${money(l.employee_cpp2)}</td><td>${money(l.employee_ei)}</td><td>${money(l.income_tax)}${l.tax_override!=null?'<br><span class="pill amber">OVERRIDE</span>':''}</td><td>${money(l.other_deductions)}</td><td><strong>${money(l.net_pay)}</strong></td><td><span class="small">${esc(l.calculation_version)}</span></td><td>${['DRAFT','REVIEW'].includes(r.status)?`<button class="btn secondary master-action" data-edit-line="${esc(l.id)}">Edit</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No employee lines.</td></tr>';$$('[data-edit-line]').forEach(b=>b.onclick=()=>openLine(b.dataset.editLine));renderRunActions(r);open('runModal')}
function renderRunActions(r){const a=$('#runActions');let html='';if(r.status==='DRAFT')html='<button class="btn secondary" data-run-status="REVIEW">Send to Review</button>';if(r.status==='REVIEW')html='<button class="btn secondary" data-run-status="DRAFT">Back to Draft</button><button class="btn green" data-run-status="APPROVED">Approve</button>';if(r.status==='APPROVED')html='<button class="btn secondary" data-run-status="REVIEW">Back to Review</button><button class="btn green" id="postRunBtn">Post Payroll</button>';if(r.status==='POSTED')html='<button class="btn green" id="payRunBtn">Record Payroll Payment</button>';if(r.status==='PAID')html='<span class="pill green">PAID · IMMUTABLE</span>';a.innerHTML=html;$$('[data-run-status]').forEach(b=>b.onclick=()=>changeRunStatus(b.dataset.runStatus));$('#postRunBtn')?.addEventListener('click',postRun);$('#payRunBtn')?.addEventListener('click',()=>openPay(r))}
function openLine(id){const l=selectedRun?.lines?.find(x=>x.id===id);if(!l)return;selectedLine=l;const f=$('#lineForm');f.reset();f.elements.line_id.value=l.id;for(const n of ['regular_hours','overtime_hours','other_regular_earnings','taxable_benefits','tax_deductible_deductions','other_deductions'])f.elements[n].value=l[n]??0;for(const n of ['pensionable_earnings_override','insurable_earnings_override','taxable_earnings_override'])f.elements[n].value='';f.elements.tax_override.value=l.tax_override??'';f.elements.tax_override_reason.value=l.tax_override_reason||'';$('#lineTitle').textContent=`${employeeName(l.employee)} · ${selectedRun.run_number}`;open('lineModal')}
function openPay(r){const f=$('#payForm');f.reset();f.elements.run_id.value=r.id;f.elements.financial_account_id.innerHTML=financialOptions(state.settings?.default_payment_financial_account_id||'');f.elements.payment_date.value=r.payment_date||localToday();$('#payInfo').textContent=`${r.run_number} · Net payroll ${money(r.net_pay)}`;open('payModal')}
function openSettings(){const f=$('#settingsForm');f.reset();f.elements.remitter_type.value=state.settings?.remitter_type||'REGULAR';f.elements.payroll_program_account_reference.value=state.settings?.payroll_program_account_reference||'';f.elements.default_payment_financial_account_id.innerHTML=financialOptions(state.settings?.default_payment_financial_account_id||'');f.elements.notes.value=state.settings?.notes||'';open('settingsModal')}
async function refreshRemitPreview(){const f=$('#remitForm'),end=f.elements.period_end.value;if(!end){$('#remitPreview').textContent='Choose a period end to calculate the unpaid source deductions.';return}try{const r=await fetch(`/.netlify/functions/cal-payroll?remittance_period_end=${encodeURIComponent(end)}`,{credentials:'same-origin'}),t=await r.text(),out=JSON.parse(t||'{}');if(!r.ok)throw Error(out.error||'Unable to calculate remittance.');const s=out.suggestion||{},cpp=Number(s.employee_cpp||0)+Number(s.employer_cpp||0)+Number(s.employee_cpp2||0)+Number(s.employer_cpp2||0),ei=Number(s.employee_ei||0)+Number(s.employer_ei||0),tax=Number(s.income_tax||0);$('#remitPreview').innerHTML=`CPP/CPP2 <strong>${money(cpp)}</strong> · EI <strong>${money(ei)}</strong> · Income tax <strong>${money(tax)}</strong> · Total <strong>${money(cpp+ei+tax)}</strong>`}catch(e){$('#remitPreview').textContent=e.message}}
function openRemit(){const f=$('#remitForm');f.reset();f.elements.period_end.value=localToday();f.elements.remittance_date.value=localToday();f.elements.financial_account_id.innerHTML=financialOptions(state.settings?.default_payment_financial_account_id||'');open('remitModal');refreshRemitPreview()}
function openT4(id){const w=state.t4.find(x=>x.id===id);if(!w)return;const e=state.employees.find(x=>x.id===w.employee_id),f=$('#t4Form');f.reset();f.elements.id.value=w.id;f.elements.notes.value=w.notes||'';f.elements.reviewed.checked=w.status==='REVIEWED';$('#t4Title').textContent=`T4 Working Paper · ${employeeName(e)} · ${w.tax_year}`;$('#t4Detail').innerHTML=`Box 14 <strong>${money(w.box14_employment_income)}</strong> · Box 16 <strong>${money(w.box16_cpp)}</strong> · Box 16A <strong>${money(w.box16a_cpp2)}</strong> · Box 18 <strong>${money(w.box18_ei)}</strong> · Box 22 <strong>${money(w.box22_income_tax)}</strong><br><span class="small">Preparation/review only. Confirm complete employee identity and filing data outside this CAL working paper.</span>`;open('t4Modal')}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});state=j.data;render();status('Saved.');return j}
async function changeRunStatus(to){if(!selectedRun)return;try{if(to==='APPROVED'&&!confirm('Approve this payroll run for posting? Review all employees and deductions first.'))return;await post('SET_RUN_STATUS',{run_id:selectedRun.id,status:to});selectedRun=state.runs.find(x=>x.id===selectedRun.id);openRun(selectedRun.id)}catch(e){status(e.message,true);alert(e.message)}}
async function postRun(){if(!selectedRun)return;if(!confirm('Post this approved payroll run? Payroll accounting becomes immutable and STEP 17 will create the journal.'))return;try{await post('POST_RUN',{run_id:selectedRun.id});selectedRun=state.runs.find(x=>x.id===selectedRun.id);openRun(selectedRun.id)}catch(e){status(e.message,true);alert(e.message)}}
async function load(){try{status('Loading payroll…');const j=await api();state=j.data||state;const y=$('#t4Year'),cy=new Date().getFullYear();y.innerHTML=[cy,cy-1,cy-2].map(v=>`<option value="${v}">${v}</option>`).join('');render();status('')}catch(e){status(e.message,true);alert(e.message)}}
$$('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#settingsBtn').onclick=openSettings;$('#employeeBtn').onclick=()=>openEmployee();$('#runBtn').onclick=()=>{const f=$('#runCreateForm');f.reset();f.elements.payment_date.value=localToday();open('runCreateModal')};$('#remitBtn').onclick=openRemit;$('#t4Year').onchange=renderT4;$('#generateT4Btn').onclick=async()=>{try{await post('GENERATE_T4',{tax_year:Number($('#t4Year').value)})}catch(e){status(e.message,true);alert(e.message)}};
$('#employeeForm').elements.employment_type.onchange=e=>{const f=e.target.form,salary=e.target.value==='SALARY';f.elements.hourly_rate.closest('div').style.opacity=salary?.5:1;f.elements.annual_salary.closest('div').style.opacity=salary?1:.5};
$('#employeeForm').elements.pay_frequency.onchange=e=>{const map={WEEKLY:52,BIWEEKLY:26,SEMIMONTHLY:24,MONTHLY:12};e.target.form.elements.pay_periods_per_year.value=map[e.target.value]||26};
$('#employeeForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_EMPLOYEE',{id:f.elements.id.value||null,party_id:f.elements.party_id.value,status:f.elements.status.value,employment_type:f.elements.employment_type.value,pay_frequency:f.elements.pay_frequency.value,pay_periods_per_year:f.elements.pay_periods_per_year.value,hire_date:f.elements.hire_date.value,hourly_rate:f.elements.hourly_rate.value,annual_salary:f.elements.annual_salary.value,overtime_multiplier:f.elements.overtime_multiplier.value,termination_date:f.elements.termination_date.value,federal_td1_claim:f.elements.federal_td1_claim.value,provincial_td1_claim:f.elements.provincial_td1_claim.value,additional_tax_per_period:f.elements.additional_tax_per_period.value,cpp_months:f.elements.cpp_months.value,sin_last4:f.elements.sin_last4.value,sin_secure_document_reference:f.elements.sin_secure_document_reference.value,federal_td1_document_reference:f.elements.federal_td1_document_reference.value,provincial_td1_document_reference:f.elements.provincial_td1_document_reference.value,sin_on_file:f.elements.sin_on_file.checked,cpp_exempt:f.elements.cpp_exempt.checked,ei_exempt:f.elements.ei_exempt.checked,notes:f.elements.notes.value});close('employeeModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#runCreateForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{const j=await post('CREATE_RUN',{pay_frequency:f.elements.pay_frequency.value,period_start:f.elements.period_start.value,period_end:f.elements.period_end.value,payment_date:f.elements.payment_date.value,notes:f.elements.notes.value});close('runCreateModal');if(j.result?.id)openRun(j.result.id)}catch(err){status(err.message,true);alert(err.message)}};
$('#lineForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{const payload={line_id:f.elements.line_id.value};for(const n of ['regular_hours','overtime_hours','other_regular_earnings','taxable_benefits','tax_deductible_deductions','other_deductions','pensionable_earnings_override','insurable_earnings_override','taxable_earnings_override','tax_override'])payload[n]=f.elements[n].value;payload.tax_override_reason=f.elements.tax_override_reason.value;await post('RECALCULATE_LINE',payload);close('lineModal');selectedRun=state.runs.find(x=>x.id===selectedRun.id);openRun(selectedRun.id)}catch(err){status(err.message,true);alert(err.message)}};
$('#payForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{if(!confirm('Record this payroll payment? This will clear Payroll Payable through STEP 17.'))return;await post('PAY_RUN',{run_id:f.elements.run_id.value,financial_account_id:f.elements.financial_account_id.value,payment_date:f.elements.payment_date.value,reference:f.elements.reference.value});close('payModal');close('runModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_SETTINGS',{remitter_type:f.elements.remitter_type.value,payroll_program_account_reference:f.elements.payroll_program_account_reference.value,default_payment_financial_account_id:f.elements.default_payment_financial_account_id.value||null,notes:f.elements.notes.value});close('settingsModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#remitForm').elements.period_end.onchange=refreshRemitPreview;
$('#remitForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{if(!confirm('Record source-deduction remittance as paid? Confirm the payment actually occurred.'))return;await post('RECORD_REMITTANCE',{period_end:f.elements.period_end.value,remittance_date:f.elements.remittance_date.value,financial_account_id:f.elements.financial_account_id.value,reference:f.elements.reference.value});close('remitModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#t4Form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_T4',{id:f.elements.id.value,notes:f.elements.notes.value,reviewed:f.elements.reviewed.checked});close('t4Modal')}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
