(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0));
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={periods:[],selectedPeriod:null,controls:[],adjustments:[],actions:[],snapshots:[],accounts:[],engineHealth:{},summary:{}},selectedPeriodId=null,lineSeq=0;
async function request(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Period Close backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Period Close request failed.');return j}
function status(msg,bad=false){const el=$('#periodCloseStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function pill(s){const x=String(s||'').toUpperCase(),c=x==='PASS'||x==='READY'||x==='CLOSED'||x==='POSTED'?'green':x==='OVERRIDDEN'||x==='REVIEW'||x==='IN_REVIEW'||x==='REOPENED'?'amber':x==='BLOCKER'?'wine':'blue';return `<span class="pill ${c}">${esc(x||'—')}</span>`}
function selected(){return state.selectedPeriod||null}
async function load(periodId=null){status('Loading period-close controls…');let url='/.netlify/functions/cal-period-close';if(periodId)url+=`?period_id=${encodeURIComponent(periodId)}`;const j=await request(url);state=j.data||state;selectedPeriodId=state.selectedPeriod?.id||null;render();status('')}
function render(){renderPeriods();renderWorkspace();renderChecklist();renderAdjustments();renderHistory()}
function renderPeriods(){const s=$('#periodSelect');const current=state.selectedPeriod?.id||selectedPeriodId||'';s.innerHTML='<option value="">No period prepared</option>'+state.periods.map(p=>`<option value="${esc(p.id)}" ${p.id===current?'selected':''}>${esc(p.period_start)} → ${esc(p.period_end)} · ${esc(p.status)} · v${Number(p.close_version||0)}</option>`).join('')}
function renderWorkspace(){const p=selected(),sum=state.summary||{},health=state.engineHealth||{};$('#periodEmpty').hidden=!!p;$('#periodWorkspace').hidden=!p;if(!p)return;$('#closeState').innerHTML=pill(p.close_state||p.status);$('#periodRange').textContent=`${p.period_start} → ${p.period_end}`;$('#blockerCount').textContent=String(sum.blockers||0);$('#reviewCount').textContent=String(sum.reviews||0);$('#closeVersion').textContent=String(p.close_version||0);$('#engineStatus').textContent=`Engine ${health.status||'UNKNOWN'}`;const closed=p.status==='CLOSED';$('#refreshBtn').hidden=closed;$('#adjustmentBtn').hidden=closed;$('#closeBtn').hidden=closed;$('#reopenBtn').hidden=!closed;$('#closeBtn').disabled=!sum.ready;$('#closeBtn').title=sum.ready?'Ready to close':'Resolve blockers and review items first';}
function renderChecklist(){const rows=state.controls||[];const sum=state.summary||{};$('#checklistSummary').textContent=rows.length?`${rows.length} controls · ${sum.blockers||0} blockers · ${sum.reviews||0} reviews · ${sum.overrides||0} signed off`:'';$('#checklistRows').innerHTML=rows.map(c=>`<tr><td>${esc(c.category)}</td><td><strong>${esc(c.label)}</strong><br><span class="small">${esc(c.control_code)}</span></td><td>${pill(c.requirement_level)}</td><td>${pill(c.status)}</td><td class="period-close-evidence">${esc(c.details||'—')}${c.status==='OVERRIDDEN'?`<br><span class="small"><strong>Sign-off:</strong> ${esc(c.override_reason||'')}</span>`:''}</td><td>${c.status==='REVIEW'&&c.requirement_level==='REVIEW'?`<button class="btn secondary master-action" data-override="${esc(c.control_code)}">Sign Off</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Prepare or refresh a period to generate the checklist.</td></tr>';$$('[data-override]').forEach(b=>b.onclick=()=>openOverride(b.dataset.override))}
function lineTotals(lines){let d=0,c=0;for(const x of lines||[]){d+=Number(x.debit||0);c+=Number(x.credit||0)}return{debit:Math.round(d*100)/100,credit:Math.round(c*100)/100}}
function renderAdjustments(){const rows=state.adjustments||[];$('#adjustmentCount').textContent=rows.length?`${rows.length} adjustment source event(s)`:'';$('#adjustmentRows').innerHTML=rows.map(a=>{const t=lineTotals(a.lines_json),evt=a.accounting_event||{},isReversal=!!a.reversal_of;return `<tr><td><strong>${esc(a.adjustment_number)}</strong></td><td>${esc(a.entry_date)}</td><td>${esc(a.memo)}${a.reason?`<br><span class="small">${esc(a.reason)}</span>`:''}</td><td>${money(t.debit)}</td><td>${money(t.credit)}</td><td>${isReversal?'<span class="pill amber">REVERSAL</span>':'<span class="pill blue">ADJUSTMENT</span>'}</td><td>${pill(evt.status||'PENDING')}${evt.last_error?`<br><span class="small danger">${esc(evt.last_error)}</span>`:''}</td><td>${!isReversal&&evt.status==='POSTED'&&!rows.some(x=>x.reversal_of===a.id)?`<button class="btn secondary master-action" data-reverse="${esc(a.id)}">Reverse</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No period adjustments.</td></tr>';$$('[data-reverse]').forEach(b=>b.onclick=()=>openReversal(b.dataset.reverse))}
function renderHistory(){const rows=state.actions||[];$('#snapshotCount').textContent=`${(state.snapshots||[]).length} close snapshot(s)`;$('#actionRows').innerHTML=rows.map(a=>`<tr><td>${esc(new Date(a.occurred_at).toLocaleString())}</td><td>${pill(a.action_type)}</td><td>${esc(a.actor_id||'System')}</td><td>${esc(a.reason||'—')}${a.metadata&&Object.keys(a.metadata).length?`<br><span class="small">${esc(JSON.stringify(a.metadata))}</span>`:''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No close actions yet.</td></tr>'}
async function post(action,payload){status('Saving…');const j=await request('/.netlify/functions/cal-period-close',{method:'POST',body:JSON.stringify({action,payload})});state=j.data||state;selectedPeriodId=state.selectedPeriod?.id||selectedPeriodId;render();status('Saved.');return j}
function monthBounds(){const d=new Date(),y=d.getFullYear(),m=d.getMonth();const end=new Date(y,m+1,0);const fmt=x=>`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;return{start:`${y}-${String(m+1).padStart(2,'0')}-01`,end:fmt(end)}}
function openOverride(code){const c=state.controls.find(x=>x.control_code===code);if(!c)return;const f=$('#overrideForm');f.reset();f.elements.control_code.value=code;$('#overrideControlName').textContent=`${c.label} · ${c.details||''}`;open('overrideModal')}
function accountOptions(selected=''){return '<option value="">Select GL account</option>'+state.accounts.map(a=>`<option value="${esc(a.code)}" ${a.code===selected?'selected':''}>${esc(a.code)} · ${esc(a.name)} · ${esc(a.account_type)}</option>`).join('')}
function addLine(line={}){lineSeq++;const tr=document.createElement('tr');tr.dataset.line=String(lineSeq);tr.innerHTML=`<td><select data-code required>${accountOptions(line.code||'')}</select></td><td><input data-debit type="number" min="0" step="0.01" value="${line.debit||''}"></td><td><input data-credit type="number" min="0" step="0.01" value="${line.credit||''}"></td><td><input data-description value="${esc(line.description||'')}"></td><td><button class="btn secondary master-action" type="button" data-remove-line>×</button></td>`;$('#adjustmentLineRows').appendChild(tr);tr.querySelector('[data-remove-line]').onclick=()=>{if($$('#adjustmentLineRows tr').length>2){tr.remove();updateAdjustmentTotals()}};tr.querySelectorAll('input').forEach(x=>x.addEventListener('input',updateAdjustmentTotals));updateAdjustmentTotals()}
function currentLines(){return $$('#adjustmentLineRows tr').map(tr=>({code:tr.querySelector('[data-code]').value,debit:Number(tr.querySelector('[data-debit]').value||0),credit:Number(tr.querySelector('[data-credit]').value||0),description:tr.querySelector('[data-description]').value.trim()}))}
function updateAdjustmentTotals(){const t=lineTotals(currentLines()),diff=Math.round((t.debit-t.credit)*100)/100;$('#adjustDebit').textContent=money(t.debit);$('#adjustCredit').textContent=money(t.credit);$('#adjustDiff').textContent=money(diff);$('#adjustDiff').className=Math.abs(diff)<.005?'ok':'danger'}
function openAdjustment(){const p=selected();if(!p)return;const f=$('#adjustmentForm');f.reset();f.elements.entry_date.value=p.period_end;$('#adjustmentLineRows').innerHTML='';addLine();addLine();open('adjustmentModal')}
function openReversal(id){const a=state.adjustments.find(x=>x.id===id);if(!a)return;const f=$('#reversalForm');f.reset();f.elements.adjustment_id.value=id;const d=new Date(`${selected().period_end}T12:00:00`);d.setDate(d.getDate()+1);f.elements.reversal_date.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;$('#reversalTarget').textContent=`${a.adjustment_number} · ${a.memo}`;open('reversalModal')}

$$('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#periodSelect').onchange=e=>load(e.target.value||null).catch(err=>{status(err.message,true);alert(err.message)});
$('#prepareBtn').onclick=()=>{const f=$('#prepareForm'),b=monthBounds();f.reset();f.elements.period_start.value=b.start;f.elements.period_end.value=Math.min(b.end,localToday());open('prepareModal')};
$('#refreshBtn').onclick=()=>post('REFRESH',{period_id:selected().id}).catch(err=>{status(err.message,true);alert(err.message)});
$('#adjustmentBtn').onclick=openAdjustment;$('#addAdjustmentLine').onclick=()=>addLine();$('#closeBtn').onclick=()=>{if(!state.summary?.ready)return;$('#closePeriodForm').reset();open('closePeriodModal')};$('#reopenBtn').onclick=()=>{$('#reopenForm').reset();open('reopenModal')};
$('#prepareForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('PREPARE',{period_start:f.elements.period_start.value,period_end:f.elements.period_end.value});close('prepareModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#overrideForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('OVERRIDE_CONTROL',{period_id:selected().id,control_code:f.elements.control_code.value,reason:f.elements.reason.value});close('overrideModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#adjustmentForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,lines=currentLines(),t=lineTotals(lines);try{if(lines.length<2)throw Error('At least two journal lines are required.');if(lines.some(x=>!x.code))throw Error('Select an account on every line.');if(Math.abs(t.debit-t.credit)>.004||t.debit<=0)throw Error('Adjusting entry must balance and have a positive total.');if(!confirm('Post this period-close adjustment through STEP 17? The source event becomes immutable.'))return;await post('POST_ADJUSTMENT',{period_id:selected().id,entry_date:f.elements.entry_date.value,memo:f.elements.memo.value,reason:f.elements.reason.value,lines});close('adjustmentModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#reversalForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('REVERSE_ADJUSTMENT',{period_id:selected().id,adjustment_id:f.elements.adjustment_id.value,reversal_date:f.elements.reversal_date.value,reason:f.elements.reason.value});close('reversalModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#closePeriodForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('CLOSE_PERIOD',{period_id:selected().id,notes:f.elements.notes.value,confirmation:f.elements.confirmation.value});close('closePeriodModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#reopenForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('REOPEN_PERIOD',{period_id:selected().id,reason:f.elements.reason.value,confirmation:f.elements.confirmation.value});close('reopenModal')}catch(err){status(err.message,true);alert(err.message)}};
load().catch(e=>{status(e.message,true);alert(e.message)});
})();
