(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0)),today=()=>new Date().toISOString().slice(0,10);
let state={bills:[],suppliers:[],accounts:[],taxCodes:[],financialAccounts:[],inventoryItems:[],inventoryLocations:[],counts:{},aging:{}};
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-purchases',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Purchases backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Purchases / A/P request failed.');return j;}
function status(msg,bad=false){const el=$('#purchaseStatus');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}
function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function option(value,label){return `<option value="${esc(value)}">${esc(label)}</option>`}
function setData(d){state=d||state;render();fillSelects();}
function roleSupplierName(p){return p?.display_name||p?.legal_name||p?.party_number||'Supplier'}
function pill(s){const c=s==='PAID'?'green':s==='VOID'?'wine':['POSTED','PARTIAL'].includes(s)?'blue':['SUBMITTED','APPROVED'].includes(s)?'amber':'blue';return `<span class="pill ${c}">${esc(s)}</span>`}
function workflowButtons(b){const a=[`<button class="btn secondary master-action" data-view="${b.id}">View</button>`];if(b.status==='DRAFT')a.push(`<button class="btn secondary master-action" data-edit="${b.id}">Edit</button><button class="btn green master-action" data-act="SUBMIT" data-id="${b.id}">Submit</button><button class="btn wine master-action" data-act="VOID" data-id="${b.id}">Void</button>`);if(b.status==='SUBMITTED')a.push(`<button class="btn secondary master-action" data-act="RETURN_TO_DRAFT" data-id="${b.id}">Return</button><button class="btn green master-action" data-act="APPROVE" data-id="${b.id}">Approve</button>`);if(b.status==='APPROVED')a.push(`<button class="btn secondary master-action" data-act="RETURN_TO_DRAFT" data-id="${b.id}">Return</button><button class="btn orange master-action" data-act="POST" data-id="${b.id}">Post to A/P</button>`);if(['POSTED','PARTIAL'].includes(b.status)&&Number(b.balance_due)>0)a.push(`<button class="btn green master-action" data-pay="${b.id}">Pay</button>`);return `<div class="actions ap-row-actions">${a.join('')}</div>`}
function render(){
  $('#apOpen').textContent=money(state.counts.openAP);$('#apOpenCount').textContent=`${state.counts.openBills||0} open bills`;$('#apOverdue').textContent=money(state.counts.overdueAP);$('#apApproval').textContent=state.counts.awaitingApproval||0;$('#apSuppliers').textContent=state.counts.suppliers||0;
  const order=['CURRENT','1-30','31-60','61-90','90+'];$('#apAging').innerHTML=order.map(k=>`<div><span>${esc(k)}</span><strong>${money(state.aging?.[k]||0)}</strong></div>`).join('');
  const q=String($('#billSearch')?.value||'').toLowerCase(),st=$('#billStatus')?.value||'';const rows=(state.bills||[]).filter(b=>(!st||b.status===st)&&(!q||[b.bill_number,b.supplier_invoice_number,roleSupplierName(b.supplier)].some(x=>String(x||'').toLowerCase().includes(q))));
  $('#billRows').innerHTML=rows.map(b=>`<tr><td><strong>${esc(b.bill_number)}</strong></td><td>${esc(roleSupplierName(b.supplier))}</td><td>${esc(b.supplier_invoice_number||'—')}</td><td>${esc(b.bill_date)}</td><td>${esc(b.due_date||'—')}${['1-30','31-60','61-90','90+'].includes(b.aging_bucket)?'<br><span class="danger small">Overdue</span>':''}</td><td class="money">${money(b.total)}</td><td class="money">${money(b.amount_paid)}</td><td class="money"><strong>${money(b.balance_due)}</strong></td><td>${pill(b.status)}</td><td>${workflowButtons(b)}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No supplier bills match this filter.</td></tr>';
  bindRows();
}
function fillSelects(){const supplier=$('#billForm select[name=supplier_party_id]'),fin=$('#paymentForm select[name=financial_account_id]');if(supplier)supplier.innerHTML='<option value="">Select supplier</option>'+state.suppliers.map(p=>option(p.id,`${p.party_number} · ${roleSupplierName(p)}`)).join('');if(fin)fin.innerHTML='<option value="">Select financial account</option>'+state.financialAccounts.map(f=>option(f.id,`${f.name} · ${f.gl_account?.code||''} ${f.gl_account?.name||''}`)).join('');}
function accountOptions(selected=''){return '<option value="">GL account</option>'+state.accounts.map(a=>`<option value="${esc(a.id)}" ${a.id===selected?'selected':''} data-code="${esc(a.code)}">${esc(a.code+' · '+a.name)}</option>`).join('')}
function inventoryItemOptions(selected=''){return '<option value="">— Not inventory —</option>'+state.inventoryItems.map(i=>`<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.sku+' · '+i.name)}</option>`).join('')}
function inventoryLocationOptions(selected=''){return '<option value="">— Location —</option>'+state.inventoryLocations.map(l=>`<option value="${esc(l.id)}" ${l.id===selected?'selected':''}>${esc(l.code+' · '+l.name)}</option>`).join('')}
function toggleInventory(tr){const acct=tr.querySelector('[data-k=posting_account_id]'),isInv=acct.options[acct.selectedIndex]?.dataset.code==='1600';const item=tr.querySelector('[data-k=inventory_item_id]'),loc=tr.querySelector('[data-k=inventory_location_id]');item.disabled=loc.disabled=!isInv;item.required=loc.required=isInv;if(!isInv){item.value='';loc.value=''}}
function taxOptions(selected=''){return '<option value="">No tax</option>'+state.taxCodes.map(t=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.code+' · '+(Number(t.federal_rate||0)+Number(t.provincial_rate||0))+'%')}</option>`).join('')}
function addLine(line={}){const tr=document.createElement('tr');tr.className='ap-line';tr.innerHTML=`<td><input data-k="description" value="${esc(line.description||'')}" placeholder="Purchase description"></td><td><input data-k="quantity" type="number" min="0.0001" step="0.0001" value="${esc(line.quantity||1)}"></td><td><input data-k="unit_price" type="number" min="0" step="0.01" value="${esc(line.unit_price||0)}"></td><td><select data-k="posting_account_id">${accountOptions(line.posting_account_id||'')}</select></td><td><select data-k="inventory_item_id">${inventoryItemOptions(line.inventory_item_id||'')}</select></td><td><select data-k="inventory_location_id">${inventoryLocationOptions(line.inventory_location_id||'')}</select></td><td><select data-k="tax_code_id">${taxOptions(line.tax_code_id||'')}</select></td><td class="money" data-sub>$0.00</td><td class="money" data-tax>$0.00</td><td class="money" data-total>$0.00</td><td><button type="button" class="btn secondary master-action" data-remove>×</button></td>`;$('#billLineRows').appendChild(tr);tr.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',()=>{if(x.dataset.k==='posting_account_id')toggleInventory(tr);calc()}));tr.querySelector('[data-remove]').onclick=()=>{if(document.querySelectorAll('.ap-line').length>1)tr.remove();calc()};toggleInventory(tr);calc();}
function taxFor(id){return state.taxCodes.find(x=>x.id===id)}function calc(){let sub=0,tax=0;document.querySelectorAll('.ap-line').forEach(tr=>{const q=Number(tr.querySelector('[data-k=quantity]').value||0),p=Number(tr.querySelector('[data-k=unit_price]').value||0),s=Math.round(q*p*100)/100,tc=taxFor(tr.querySelector('[data-k=tax_code_id]').value),rate=tc?Number(tc.federal_rate||0)+Number(tc.provincial_rate||0):0,t=Math.round(s*rate)/100,total=s+t;sub+=s;tax+=t;tr.querySelector('[data-sub]').textContent=money(s);tr.querySelector('[data-tax]').textContent=money(t);tr.querySelector('[data-total]').textContent=money(total)});$('#billSubtotal').textContent=money(sub);$('#billTax').textContent=money(tax);$('#billTotal').textContent=money(sub+tax)}
function resetBill(b=null){const f=$('#billForm');f.reset();f.elements.id.value=b?.id||'';f.elements.bill_date.value=b?.bill_date||today();f.elements.due_date.value=b?.due_date||'';f.elements.currency.value=b?.currency||'CAD';f.elements.supplier_party_id.value=b?.supplier_party_id||'';f.elements.supplier_invoice_number.value=b?.supplier_invoice_number||'';f.elements.source_reference.value=b?.source_reference||'';f.elements.notes.value=b?.notes||'';$('#billModalTitle').textContent=b?`Edit ${b.bill_number}`:'New Supplier Bill';$('#billLineRows').innerHTML='';(b?.lines?.length?b.lines:[{}]).forEach(addLine);calc();}
function linePayload(){return [...document.querySelectorAll('.ap-line')].map(tr=>({description:tr.querySelector('[data-k=description]').value,quantity:tr.querySelector('[data-k=quantity]').value,unit_price:tr.querySelector('[data-k=unit_price]').value,posting_account_id:tr.querySelector('[data-k=posting_account_id]').value,inventory_item_id:tr.querySelector('[data-k=inventory_item_id]').value,inventory_location_id:tr.querySelector('[data-k=inventory_location_id]').value,tax_code_id:tr.querySelector('[data-k=tax_code_id]').value}))}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});setData(j.data);status('Saved.');return j;}
async function actionBill(id,action){const msg={SUBMIT:'Submit this bill for approval?',APPROVE:'Approve this supplier bill?',POST:'Post this bill to Accounts Payable and the General Ledger?',RETURN_TO_DRAFT:'Return this bill to Draft for editing?',VOID:'Void this unposted supplier bill?'}[action]||'Continue?';if(!confirm(msg))return;try{await post('BILL_ACTION',{id,bill_action:action})}catch(e){status(e.message,true);alert(e.message)}}
function detail(b){$('#detailTitle').textContent=`${b.bill_number} · ${roleSupplierName(b.supplier)}`;$('#detailSub').textContent=`Supplier invoice ${b.supplier_invoice_number||'—'} · ${b.bill_date} · Due ${b.due_date||'—'}`;$('#detailBody').innerHTML=`<div class="grid kpis ap-detail-kpis"><div class="card kpi"><div class="label">Status</div><div class="value ap-detail-status">${pill(b.status)}</div></div><div class="card kpi"><div class="label">Total</div><div class="value">${money(b.total)}</div></div><div class="card kpi"><div class="label">Paid</div><div class="value">${money(b.amount_paid)}</div></div><div class="card kpi"><div class="label">Balance</div><div class="value">${money(b.balance_due)}</div></div></div><h4>Lines</h4><div class="table-wrap"><table><thead><tr><th>Description</th><th>Account</th><th>Inventory</th><th>Subtotal</th><th>Tax</th><th>Recoverable</th><th>Total</th></tr></thead><tbody>${b.lines.map(l=>`<tr><td>${esc(l.description)}</td><td>${esc((l.posting_account?.code||'')+' '+(l.posting_account?.name||''))}</td><td>${l.inventory_item?esc((l.inventory_item.sku||'')+' · '+(l.inventory_item.name||''))+'<br><span class="small">'+esc((l.inventory_location?.code||'')+' · '+(l.inventory_location?.name||''))+'</span>':'—'}</td><td>${money(l.line_subtotal)}</td><td>${money(l.tax_amount)}</td><td>${money(l.recoverable_tax)}</td><td>${money(l.line_total)}</td></tr>`).join('')}</tbody></table></div><h4>Payments</h4><div class="table-wrap"><table><thead><tr><th>Payment</th><th>Date</th><th>Account</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>${b.payments.length?b.payments.map(p=>`<tr><td>${esc(p.payment_number)}</td><td>${esc(p.payment_date)}</td><td>${esc(p.financial_account?.name||'—')}</td><td>${esc(p.method||'—')}</td><td>${esc(p.reference||'—')}</td><td>${money(p.amount)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No supplier payments recorded.</td></tr>'}</tbody></table></div>${b.notes?`<div class="notice" style="margin-top:14px"><strong>Notes:</strong> ${esc(b.notes)}</div>`:''}`;open('detailModal')}
function payment(b){const f=$('#paymentForm');f.reset();f.elements.supplier_bill_id.value=b.id;f.elements.payment_date.value=today();f.elements.amount.value=Number(b.balance_due||0).toFixed(2);$('#paymentContext').textContent=`${b.bill_number} · ${roleSupplierName(b.supplier)} · Outstanding ${money(b.balance_due)}`;fillSelects();open('paymentModal')}
function bindRows(){document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>detail(state.bills.find(b=>b.id===x.dataset.view)));document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>{const b=state.bills.find(b=>b.id===x.dataset.edit);fillSelects();resetBill(b);open('billModal')});document.querySelectorAll('[data-act]').forEach(x=>x.onclick=()=>actionBill(x.dataset.id,x.dataset.act));document.querySelectorAll('[data-pay]').forEach(x=>x.onclick=()=>payment(state.bills.find(b=>b.id===x.dataset.pay)))}
async function load(){try{status('Loading…');const j=await api();setData(j.data);status('')}catch(e){status(e.message,true)}}

document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));$('#newBillBtn').onclick=()=>{fillSelects();resetBill();open('billModal')};$('#addBillLine').onclick=()=>addLine();$('#billSearch').addEventListener('input',render);$('#billStatus').addEventListener('change',render);
$('#billForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_BILL',{id:f.elements.id.value||null,supplier_party_id:f.elements.supplier_party_id.value,supplier_invoice_number:f.elements.supplier_invoice_number.value,bill_date:f.elements.bill_date.value,due_date:f.elements.due_date.value,currency:f.elements.currency.value,source_reference:f.elements.source_reference.value,notes:f.elements.notes.value,lines:linePayload()});close('billModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#paymentForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('RECORD_PAYMENT',{supplier_bill_id:f.elements.supplier_bill_id.value,payment_date:f.elements.payment_date.value,amount:f.elements.amount.value,financial_account_id:f.elements.financial_account_id.value,method:f.elements.method.value,reference:f.elements.reference.value,notes:f.elements.notes.value});close('paymentModal')}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
