(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0)),today=()=>new Date().toISOString().slice(0,10);
let state={company:{},invoices:[],creditNotes:[],refunds:[],customers:[],customerCredits:[],accounts:[],taxCodes:[],financialAccounts:[],counts:{},aging:{}};let printNote=null;
async function api(opt={}){const r=await fetch('/.netlify/functions/cal-receivables',{credentials:'same-origin',headers:{'content-type':'application/json'},...opt}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{throw Error('Accounts Receivable backend returned a non-JSON response. Check Netlify deploy.')}if(r.status===401){location.replace('../admin-login.html');throw Error('PLEASE Admin session required.')}if(!r.ok)throw Error(j.error||'Accounts Receivable request failed.');return j;}
function status(msg,bad=false){const el=$('#arStatusMessage');if(el){el.textContent=msg||'';el.className='small master-status '+(bad?'danger':'ok')}}function open(id){$('#'+id)?.classList.add('open')}function close(id){$('#'+id)?.classList.remove('open')}
function partyName(p){return p?.display_name||p?.legal_name||p?.party_number||'Customer'}function option(value,label){return `<option value="${esc(value)}">${esc(label)}</option>`}
function pill(s){const x=String(s||'').toUpperCase(),c=['PAID','POSTED','COMPLETED','SETTLED','CREDITED'].includes(x)?'green':['VOID','DEAD_LETTER'].includes(x)?'wine':['APPROVED','PARTIAL','PROCESSING'].includes(x)?'blue':'amber';return `<span class="pill ${c}">${esc(x||'—')}</span>`}
function eventPill(e){if(!e)return '<span class="pill amber ar-event">PENDING</span>';return pill(e.status||'PENDING')}
function invoiceName(i){return `${i.invoice_number} · ${i.customer_name}`}
function creditName(n){return `${n.credit_note_number} · ${n.invoice?.invoice_number||''}`}
function setData(d){state=d||state;render();fillCreditInvoiceSelect();fillRefundSelects();}
function workflowButtons(n){let b=[`<button class="btn secondary master-action" data-note-view="${n.id}">View</button>`];if(n.status==='DRAFT')b.push(`<button class="btn secondary master-action" data-note-edit="${n.id}">Edit</button><button class="btn green master-action" data-note-act="SUBMIT" data-id="${n.id}">Submit</button>`);if(n.status==='SUBMITTED')b.push(`<button class="btn green master-action" data-note-act="APPROVE" data-id="${n.id}">Approve</button><button class="btn secondary master-action" data-note-act="RETURN_TO_DRAFT" data-id="${n.id}">Return</button>`);if(n.status==='APPROVED')b.push(`<button class="btn wine master-action" data-note-act="POST" data-id="${n.id}">Post</button><button class="btn secondary master-action" data-note-act="RETURN_TO_DRAFT" data-id="${n.id}">Return</button>`);return `<div class="ar-row-actions">${b.join('')}</div>`}
function render(){
  $('#arOpen').textContent=money(state.counts.openAR||0);$('#arOverdue').textContent=money(state.counts.overdueAR||0);$('#arCredits').textContent=money(state.counts.customerCredits||0);$('#arCreditNotes').textContent=state.counts.postedCreditNotes||0;$('#arPendingNotes').textContent=`${state.counts.pendingCreditNotes||0} awaiting approval / posting`;
  const order=['CURRENT','1-30','31-60','61-90','90+'];$('#arAging').innerHTML=order.map(k=>`<div><span>${esc(k)}</span><strong>${money(state.aging?.[k]||0)}</strong></div>`).join('');
  $('#customerCreditList').innerHTML=(state.customerCredits||[]).length?state.customerCredits.map(a=>`<div class="ar-credit-item"><span>${esc(partyName(a.party))}</span><strong>${money(a.available_credit)}</strong></div>`).join(''):'<div class="empty">No customer credits available for refund.</div>';
  const iq=String($('#invoiceSearch')?.value||'').toLowerCase(),ist=$('#invoiceStatus')?.value||'';const invoices=(state.invoices||[]).filter(i=>(!ist||i.ar_status===ist)&&(!iq||[i.invoice_number,i.customer_name,i.customer_email].some(x=>String(x||'').toLowerCase().includes(iq))));
  $('#arInvoiceRows').innerHTML=invoices.map(i=>`<tr><td><strong>${esc(i.invoice_number)}</strong></td><td>${esc(i.customer_name)}${i.customer_email?`<br><span class="small">${esc(i.customer_email)}</span>`:''}</td><td>${esc(i.invoice_date)}</td><td>${esc(i.due_date||'—')}${i.aging_bucket!=='CURRENT'&&i.aging_bucket!=='CLOSED'&&i.balance_due>0?'<br><span class="danger small">Overdue</span>':''}</td><td class="money">${money(i.total)}</td><td class="money">${money(i.paid)}</td><td class="money">${money(i.credited)}</td><td class="money"><strong>${money(i.balance_due)}</strong></td><td>${pill(i.ar_status)}</td><td><div class="ar-row-actions"><button class="btn secondary master-action" data-invoice-view="${i.id}">View</button>${i.remaining_creditable_total>0.001&&i.status!=='VOID'?`<button class="btn wine master-action" data-new-credit="${i.id}">Credit Note</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="10" class="empty">No invoices match this filter.</td></tr>';
  const cq=String($('#creditSearch')?.value||'').toLowerCase(),cst=$('#creditStatus')?.value||'';const notes=(state.creditNotes||[]).filter(n=>(!cst||n.status===cst)&&(!cq||[n.credit_note_number,n.invoice?.invoice_number,partyName(n.customer)].some(x=>String(x||'').toLowerCase().includes(cq))));
  $('#creditRows').innerHTML=notes.map(n=>`<tr><td><strong>${esc(n.credit_note_number)}</strong></td><td>${esc(n.invoice?.invoice_number||'—')}</td><td>${esc(partyName(n.customer))}</td><td>${esc(n.credit_date)}</td><td class="money">${money(n.subtotal_reduction)}</td><td class="money">${money(n.tax_reduction)}</td><td class="money"><strong>${money(n.total)}</strong></td><td>${pill(n.status)}</td><td>${n.status==='POSTED'?eventPill(n.accounting_event):'<span class="small">Not posted</span>'}</td><td>${workflowButtons(n)}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No Credit Notes yet.</td></tr>';
  $('#refundRows').innerHTML=(state.refunds||[]).map(r=>`<tr><td><strong>${esc(r.refund_number)}</strong></td><td>${esc(partyName(r.customer))}</td><td>${esc(r.refund_date)}</td><td>${esc(r.financial_account?.name||'—')}</td><td>${esc(r.method||'—')}</td><td>${esc(r.reference||'—')}</td><td class="money"><strong>${money(r.amount)}</strong></td><td>${eventPill(r.accounting_event)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No customer refunds recorded.</td></tr>';
  bindRows();
}
function fillCreditInvoiceSelect(selected=''){const sel=$('#creditForm select[name=invoice_id]');if(!sel)return;const rows=(state.invoices||[]).filter(i=>i.remaining_creditable_total>0.001||i.id===selected);sel.innerHTML='<option value="">Select original invoice</option>'+rows.map(i=>`<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(invoiceName(i))} · remaining ${money(i.remaining_creditable_total)}</option>`).join('');}
function fillRefundSelects(){const cs=$('#refundForm select[name=customer_party_id]'),fin=$('#refundForm select[name=financial_account_id]');if(cs)cs.innerHTML='<option value="">Select customer credit</option>'+(state.customerCredits||[]).map(a=>option(a.party.id,`${partyName(a.party)} · ${money(a.available_credit)} available`)).join('');if(fin)fin.innerHTML='<option value="">Select financial account</option>'+(state.financialAccounts||[]).map(f=>option(f.id,`${f.name} · ${f.gl_account?.code||''} ${f.gl_account?.name||''}`)).join('');refreshRefundCreditNotes();}
function revenueOptions(selected=''){return '<option value="">Revenue account</option>'+(state.accounts||[]).map(a=>`<option value="${esc(a.id)}" ${a.id===selected?'selected':''}>${esc(a.code+' · '+a.name)}</option>`).join('')}
function taxOptions(selected=''){return '<option value="">No tax</option>'+(state.taxCodes||[]).map(t=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.code+' · '+(Number(t.federal_rate||0)+Number(t.provincial_rate||0))+'%')}</option>`).join('')}
function defaultRevenue(){return state.accounts?.find(a=>a.code==='4000')?.id||state.accounts?.[0]?.id||''}
function closestTaxCode(invoice){if(!invoice||invoice.remaining_creditable_tax<=0)return '';const sub=Number(invoice.remaining_creditable_subtotal||0),rate=sub>0?Number(invoice.remaining_creditable_tax||0)/sub*100:0;let best=null,delta=Infinity;for(const t of state.taxCodes||[]){const r=Number(t.federal_rate||0)+Number(t.provincial_rate||0),d=Math.abs(r-rate);if(d<delta){best=t;delta=d}}return best?.id||''}
function taxFor(id){return state.taxCodes.find(x=>x.id===id)}
function addCreditLine(line={}){const tr=document.createElement('tr');tr.className='credit-line';tr.innerHTML=`<td><input data-k="description" value="${esc(line.description||'')}" placeholder="Credit description"></td><td><input data-k="quantity" type="number" min="0.0001" step="0.0001" value="${esc(line.quantity||1)}"></td><td><input data-k="unit_price" type="number" min="0" step="0.01" value="${esc(line.unit_price||0)}"></td><td><select data-k="revenue_account_id">${revenueOptions(line.revenue_account_id||defaultRevenue())}</select></td><td><select data-k="tax_code_id">${taxOptions(line.tax_code_id||'')}</select></td><td><input data-k="tax_amount_override" type="number" min="0" step="0.01" value="${line.tax_amount_override==null?'':esc(line.tax_amount_override)}" placeholder="Auto"></td><td class="money" data-sub>$0.00</td><td class="money" data-tax>$0.00</td><td class="money" data-total>$0.00</td><td><button type="button" class="btn secondary master-action" data-remove>×</button></td>`;$('#creditLineRows').appendChild(tr);tr.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calcCredit));tr.querySelector('[data-remove]').onclick=()=>{if(document.querySelectorAll('.credit-line').length>1)tr.remove();calcCredit()};calcCredit();}
function calcCredit(){const adjust=$('#creditForm [name=tax_adjustment_included]').checked;let sub=0,tax=0;document.querySelectorAll('.credit-line').forEach(tr=>{const q=Number(tr.querySelector('[data-k=quantity]').value||0),p=Number(tr.querySelector('[data-k=unit_price]').value||0),s=Math.round(q*p*100)/100,tc=taxFor(tr.querySelector('[data-k=tax_code_id]').value),rate=tc?Number(tc.federal_rate||0)+Number(tc.provincial_rate||0):0,rawOverride=tr.querySelector('[data-k=tax_amount_override]').value,t=adjust?(rawOverride!==''?Number(rawOverride||0):Math.round(s*rate)/100):0,total=Math.round((s+t)*100)/100;sub+=s;tax+=t;tr.querySelector('[data-sub]').textContent=money(s);tr.querySelector('[data-tax]').textContent=money(t);tr.querySelector('[data-total]').textContent=money(total)});$('#creditSubtotal').textContent=money(sub);$('#creditTax').textContent=money(tax);$('#creditTotal').textContent=money(sub+tax);const inv=state.invoices.find(i=>i.id===$('#creditForm [name=invoice_id]').value);$('#creditLimit').textContent=inv?`Remaining creditable: ${money(inv.remaining_creditable_subtotal)} subtotal + ${money(inv.remaining_creditable_tax)} tax = ${money(inv.remaining_creditable_total)}`:'Select an invoice to see remaining creditable amount.';}
function resetCredit(note=null,invoiceId=null){const f=$('#creditForm');f.reset();const target=note?.invoice_id||invoiceId||'';fillCreditInvoiceSelect(target);f.elements.id.value=note?.id||'';f.elements.invoice_id.value=target;f.elements.credit_date.value=note?.credit_date||today();f.elements.reason_code.value=note?.reason_code||'SERVICE_ADJUSTMENT';f.elements.reason.value=note?.reason||'';f.elements.source_reference.value=note?.source_reference||'';f.elements.tax_adjustment_included.checked=note?note.tax_adjustment_included!==false:true;$('#creditModalTitle').textContent=note?`Edit ${note.credit_note_number}`:'New Credit Note';$('#creditLineRows').innerHTML='';(note?.lines?.length?note.lines:[{}]).forEach(addCreditLine);calcCredit();}
function fullRemaining(){const inv=state.invoices.find(i=>i.id===$('#creditForm [name=invoice_id]').value);if(!inv)return alert('Select an invoice first.');$('#creditLineRows').innerHTML='';addCreditLine({description:`Credit adjustment for ${inv.invoice_number}`,quantity:1,unit_price:inv.remaining_creditable_subtotal,revenue_account_id:defaultRevenue(),tax_code_id:closestTaxCode(inv),tax_amount_override:inv.remaining_creditable_tax>0?inv.remaining_creditable_tax:null});calcCredit();}
function linePayload(){return [...document.querySelectorAll('.credit-line')].map(tr=>({description:tr.querySelector('[data-k=description]').value,quantity:tr.querySelector('[data-k=quantity]').value,unit_price:tr.querySelector('[data-k=unit_price]').value,revenue_account_id:tr.querySelector('[data-k=revenue_account_id]').value,tax_code_id:tr.querySelector('[data-k=tax_code_id]').value,tax_amount_override:tr.querySelector('[data-k=tax_amount_override]').value||null}))}
async function post(action,payload){status('Saving…');const j=await api({method:'POST',body:JSON.stringify({action,payload})});setData(j.data);status('Saved.');return j;}
async function noteAction(id,action){const msg={SUBMIT:'Submit this Credit Note for approval?',APPROVE:'Approve this Credit Note?',POST:'Post this Credit Note to the General Ledger and reduce Accounts Receivable?',RETURN_TO_DRAFT:'Return this Credit Note to Draft?',VOID:'Void this unposted Credit Note?'}[action]||'Continue?';if(!confirm(msg))return;try{await post('CREDIT_NOTE_ACTION',{id,credit_action:action})}catch(e){status(e.message,true);alert(e.message)}}
function invoiceDetail(i){const notes=(i.credit_notes||[]).filter(n=>n.status!=='VOID');alert(`${i.invoice_number}\nCustomer: ${i.customer_name}\nTotal: ${money(i.total)}\nPaid: ${money(i.paid)}\nCredit Notes: ${money(i.credited)}\nBalance: ${money(i.balance_due)}\nA/R status: ${i.ar_status}\nCredit Notes: ${notes.map(n=>n.credit_note_number+' '+money(n.total)).join(', ')||'None'}`)}
function noteDetail(n){printNote=n;const inv=n.invoice||{},cust=n.customer||{};$('#creditDetailTitle').textContent=n.credit_note_number;$('#creditDetailSub').textContent=`Original invoice ${inv.invoice_number||'—'} · ${n.credit_date} · ${partyName(cust)}`;$('#creditDetailBody').innerHTML=`<div class="ar-document"><div class="doc-grid"><div class="doc-box"><strong>Customer</strong><br>${esc(partyName(cust))}<br>${esc(cust.email||'')}</div><div class="doc-box"><strong>Reason</strong><br>${esc(n.reason_code)}<br>${esc(n.reason)}</div><div class="doc-box"><strong>Original invoice</strong><br>${esc(inv.invoice_number||'—')}<br>${esc(inv.invoice_date||'')}</div><div class="doc-box"><strong>Status</strong><br>${pill(n.status)}<br>Accounting: ${n.status==='POSTED'?eventPill(n.accounting_event):'Not posted'}</div></div><div class="table-wrap"><table><thead><tr><th>Description</th><th>Revenue Account</th><th>Tax Code</th><th>Subtotal</th><th>Tax</th><th>Total</th></tr></thead><tbody>${(n.lines||[]).map(l=>`<tr><td>${esc(l.description)}</td><td>${esc((l.revenue_account?.code||'')+' '+(l.revenue_account?.name||''))}</td><td>${esc(l.tax_code?.code||'—')}</td><td>${money(l.line_subtotal)}</td><td>${money(l.line_tax)}</td><td>${money(l.line_total)}</td></tr>`).join('')}</tbody></table></div><div class="doc-total">Credit Note Total: ${money(n.total)}</div></div>`;open('creditDetailModal')}
function printCredit(){const n=printNote;if(!n)return;const c=state.company||{},inv=n.invoice||{},cust=n.customer||{},w=window.open('','_blank','width=900,height=900');if(!w)return alert('Allow pop-ups to print the Credit Note.');const rows=(n.lines||[]).map(l=>{const rate=l.tax_code?Number(l.tax_code.federal_rate||0)+Number(l.tax_code.provincial_rate||0):0;return `<tr><td>${esc(l.description)}</td><td>${money(l.line_subtotal)}</td><td>${esc(l.tax_code?.code||'No tax')}${rate?` · ${rate}%`:''}</td><td>${money(l.line_tax)}</td><td>${money(l.line_total)}</td></tr>`}).join('');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(n.credit_note_number)}</title><style>body{font-family:Arial,sans-serif;color:#222;padding:38px}h1{color:#173f5f}.top{display:flex;justify-content:space-between;gap:30px}.box{margin:18px 0;padding:14px;border:1px solid #ccc}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ccc;padding:9px;text-align:left}.total{text-align:right;font-size:20px;font-weight:bold;margin-top:18px}.muted{color:#666;font-size:12px}</style></head><body><div class="top"><div><h1>CREDIT NOTE</h1><strong>${esc(c.legal_name||c.operating_name||'PLEASE Services')}</strong><br>Business Number: ${esc(c.business_number||'—')}<br>GST/HST/QST account: ${esc(c.sales_tax_account_number||'—')}</div><div><strong>${esc(n.credit_note_number)}</strong><br>Issue date: ${esc(n.credit_date)}<br>Original invoice: ${esc(inv.invoice_number||'—')}<br>Original invoice date: ${esc(inv.invoice_date||'—')}</div></div><div class="box"><strong>Customer</strong><br>${esc(partyName(cust))}<br>${esc(cust.email||'')}</div><div class="box"><strong>Reason for adjustment/refund/credit</strong><br>${esc(n.reason_code)} — ${esc(n.reason)}<br><span class="muted">Sales-tax adjustment included: ${n.tax_adjustment_included!==false?'Yes':'No'}</span></div><table><thead><tr><th>Description</th><th>Consideration Reduction</th><th>Tax / Rate</th><th>Tax Reduction</th><th>Total Credit</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Subtotal credit ${money(n.subtotal_reduction)}<br>Tax credit ${money(n.tax_reduction)}<br>Total credit ${money(n.total)}</div><p class="muted">This document is a Credit Note linked to the original invoice identified above. Accounting records are retained in CAL with immutable event/journal traceability after posting.</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function refreshRefundCreditNotes(){const f=$('#refundForm'),partyId=f?.elements.customer_party_id.value||'',sel=f?.elements.credit_note_id;if(!sel)return;const notes=(state.creditNotes||[]).filter(n=>n.status==='POSTED'&&(!partyId||n.customer_party_id===partyId));sel.innerHTML='<option value="">No specific Credit Note / overall credit</option>'+notes.map(n=>option(n.id,`${n.credit_note_number} · ${n.invoice?.invoice_number||''} · ${money(n.total)}`)).join('');const a=(state.customerCredits||[]).find(x=>x.party?.id===partyId);$('#refundAvailable').textContent=`Available customer credit: ${money(a?.available_credit||0)}`;if(a&&Number(f.elements.amount.value||0)<=0)f.elements.amount.value=Number(a.available_credit).toFixed(2)}
function openRefund(partyId=''){fillRefundSelects();const f=$('#refundForm');f.reset();f.elements.refund_date.value=today();if(partyId)f.elements.customer_party_id.value=partyId;refreshRefundCreditNotes();open('refundModal')}
function bindRows(){document.querySelectorAll('[data-new-credit]').forEach(x=>x.onclick=()=>{resetCredit(null,x.dataset.newCredit);open('creditModal')});document.querySelectorAll('[data-invoice-view]').forEach(x=>x.onclick=()=>invoiceDetail(state.invoices.find(i=>i.id===x.dataset.invoiceView)));document.querySelectorAll('[data-note-view]').forEach(x=>x.onclick=()=>noteDetail(state.creditNotes.find(n=>n.id===x.dataset.noteView)));document.querySelectorAll('[data-note-edit]').forEach(x=>x.onclick=()=>{const n=state.creditNotes.find(z=>z.id===x.dataset.noteEdit);resetCredit(n);open('creditModal')});document.querySelectorAll('[data-note-act]').forEach(x=>x.onclick=()=>noteAction(x.dataset.id,x.dataset.noteAct))}
async function load(){try{status('Loading…');const j=await api();setData(j.data);status('')}catch(e){status(e.message,true)}}

document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$('#newCreditBtn').onclick=()=>{resetCredit();open('creditModal')};$('#newRefundBtn').onclick=()=>{if(!(state.customerCredits||[]).length)return alert('No customer currently has refundable credit. Post a Credit Note that creates a customer credit first.');openRefund()};$('#addCreditLine').onclick=()=>addCreditLine();$('#fullCreditBtn').onclick=fullRemaining;$('#creditForm [name=invoice_id]').addEventListener('change',calcCredit);$('#creditForm [name=tax_adjustment_included]').addEventListener('change',calcCredit);$('#invoiceSearch').addEventListener('input',render);$('#invoiceStatus').addEventListener('change',render);$('#creditSearch').addEventListener('input',render);$('#creditStatus').addEventListener('change',render);$('#refundForm [name=customer_party_id]').addEventListener('change',refreshRefundCreditNotes);$('#printCreditBtn').onclick=printCredit;
$('#creditForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('SAVE_CREDIT_NOTE',{id:f.elements.id.value||null,invoice_id:f.elements.invoice_id.value,credit_date:f.elements.credit_date.value,reason_code:f.elements.reason_code.value,reason:f.elements.reason.value,tax_adjustment_included:f.elements.tax_adjustment_included.checked,source_reference:f.elements.source_reference.value,lines:linePayload()});close('creditModal')}catch(err){status(err.message,true);alert(err.message)}};
$('#refundForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await post('RECORD_REFUND',{customer_party_id:f.elements.customer_party_id.value,credit_note_id:f.elements.credit_note_id.value||null,refund_date:f.elements.refund_date.value,amount:f.elements.amount.value,financial_account_id:f.elements.financial_account_id.value,method:f.elements.method.value,reference:f.elements.reference.value,notes:f.elements.notes.value});close('refundModal')}catch(err){status(err.message,true);alert(err.message)}};
load();
})();
