-- STEP 18.7 verification — read-only checks.
with checks as (
select 1 n,'fixed_asset_table' check_name,case when to_regclass('public.accounting_fixed_assets') is not null then 'PASS' else 'FAIL' end status,'Fixed asset register exists' detail
union all select 2,'depreciation_tables',case when to_regclass('public.accounting_fixed_asset_depreciation_runs') is not null and to_regclass('public.accounting_fixed_asset_depreciation_lines') is not null then 'PASS' else 'FAIL' end,'Book depreciation run + line tables exist'
union all select 3,'cca_tables',case when to_regclass('public.accounting_cca_classes') is not null and to_regclass('public.accounting_cca_working_papers') is not null then 'PASS' else 'FAIL' end,'CCA class master and UCC working paper exist'
union all select 4,'fixed_asset_accounts',case when (select count(*) from public.accounting_accounts where code in ('1500','1510','4050','6200','6300') and active=true)=5 then 'PASS' else 'FAIL' end,'Gross asset, accumulated depreciation, depreciation expense and disposal gain/loss accounts active'
union all select 5,'cca_seed',case when (select count(*) from public.accounting_cca_classes where class_code in ('8','10','10.1','12','16','50','54','55','56') and active=true)>=9 then 'PASS' else 'FAIL' end,'Common CRA CCA classes seeded as reference metadata'
union all select 6,'book_tax_separation',case when exists(select 1 from information_schema.columns where table_schema='public' and table_name='accounting_fixed_assets' and column_name='depreciation_method') and exists(select 1 from information_schema.columns where table_schema='public' and table_name='accounting_fixed_assets' and column_name='cca_class_id') then 'PASS' else 'FAIL' end,'Book depreciation and tax CCA fields are separate'
union all select 7,'source_bill_link',case when exists(select 1 from information_schema.columns where table_schema='public' and table_name='accounting_supplier_bill_lines' and column_name='fixed_asset_id') then 'PASS' else 'FAIL' end,'Supplier bill lines can link to Fixed Asset register'
union all select 8,'source_expense_link',case when exists(select 1 from information_schema.columns where table_schema='public' and table_name='accounting_expense_claim_lines' and column_name='fixed_asset_id') then 'PASS' else 'FAIL' end,'Advanced expense lines can link to Fixed Asset register'
union all select 9,'source_register_function',case when to_regprocedure('public.accounting_fixed_asset_source_register(text,text,text,text,text,text,date,uuid,numeric,numeric,text,text)') is not null then 'PASS' else 'FAIL' end,'Source-backed capitalization intake function exists'
union all select 10,'setup_function',case when to_regprocedure('public.accounting_save_fixed_asset_setup(uuid,text,text,text,text,text,uuid,date,date,text,integer,numeric,uuid,numeric,numeric,integer,text,text,boolean,text)') is not null then 'PASS' else 'FAIL' end,'Asset setup function exists'
union all select 11,'opening_function',case when to_regprocedure('public.accounting_create_opening_fixed_asset(text,text,text,text,text,uuid,uuid,date,date,date,text,integer,numeric,numeric,numeric,uuid,numeric,numeric,integer,text,text,text,text)') is not null then 'PASS' else 'FAIL' end,'Opening asset function exists'
union all select 12,'depreciation_functions',case when to_regprocedure('public.accounting_create_fixed_asset_depreciation_run(date,text)') is not null and to_regprocedure('public.accounting_post_fixed_asset_depreciation_run(uuid,text)') is not null then 'PASS' else 'FAIL' end,'Draft/review/post book depreciation functions exist'
union all select 13,'disposal_function',case when to_regprocedure('public.accounting_dispose_fixed_asset(uuid,date,numeric,uuid,text,text,numeric,text)') is not null then 'PASS' else 'FAIL' end,'Controlled disposal function exists'
union all select 14,'cca_functions',case when to_regprocedure('public.accounting_generate_cca_working_paper(integer,text)') is not null and to_regprocedure('public.accounting_save_cca_claim(uuid,numeric,text,boolean,text)') is not null then 'PASS' else 'FAIL' end,'CCA working-paper generation/review functions exist'
union all select 15,'posting_rules',case when (select count(*) from public.accounting_posting_rules where source_system='PLEASE' and event_type in ('FIXED_ASSET_OPENING_POSTED','FIXED_ASSET_DEPRECIATION_POSTED','FIXED_ASSET_DISPOSAL_POSTED') and enabled=true)=3 then 'PASS' else 'FAIL' end,'STEP 17 posting rules enabled'
union all select 16,'supplier_trigger',case when exists(select 1 from pg_trigger where tgname='trg_step18_7_supplier_bill_fixed_asset' and not tgisinternal) then 'PASS' else 'FAIL' end,'Posted supplier capital purchases create asset intake'
union all select 17,'expense_trigger',case when exists(select 1 from pg_trigger where tgname='trg_step18_7_expense_fixed_asset' and not tgisinternal) then 'PASS' else 'FAIL' end,'Posted FIXED_ASSET expenses create asset intake'
union all select 18,'rls_fixed_assets',case when (select relrowsecurity from pg_class where oid='public.accounting_fixed_assets'::regclass) then 'PASS' else 'FAIL' end,'Fixed Asset register protected by RLS'
union all select 19,'posted_dep_immutability',case when exists(select 1 from pg_trigger where tgname='trg_protect_fixed_asset_dep_run' and not tgisinternal) and exists(select 1 from pg_trigger where tgname='trg_protect_fixed_asset_dep_line' and not tgisinternal) then 'PASS' else 'FAIL' end,'Posted depreciation evidence is immutable'
union all select 20,'gl_control_functions',case when to_regprocedure('public.accounting_fixed_asset_gross_gl_balance(date)') is not null and to_regprocedure('public.accounting_fixed_asset_accum_gl_balance(date)') is not null and to_regprocedure('public.accounting_fixed_asset_gross_subledger_value()') is not null and to_regprocedure('public.accounting_fixed_asset_accum_subledger_value(date)') is not null then 'PASS' else 'FAIL' end,'Fixed asset subledger-to-GL controls exist'
union all select 21,'gross_control',case when abs(public.accounting_fixed_asset_gross_gl_balance(current_date)-public.accounting_fixed_asset_gross_subledger_value())<=0.02 then 'PASS' else 'REVIEW' end,format('GL 1500=%s / subledger=%s',public.accounting_fixed_asset_gross_gl_balance(current_date),public.accounting_fixed_asset_gross_subledger_value())
union all select 22,'accumulated_control',case when abs(public.accounting_fixed_asset_accum_gl_balance(current_date)-public.accounting_fixed_asset_accum_subledger_value(current_date))<=0.02 then 'PASS' else 'REVIEW' end,format('GL 1510=%s / subledger=%s',public.accounting_fixed_asset_accum_gl_balance(current_date),public.accounting_fixed_asset_accum_subledger_value(current_date))
union all select 23,'no_disposed_without_date',case when not exists(select 1 from public.accounting_fixed_assets where status='DISPOSED' and disposal_date is null) then 'PASS' else 'FAIL' end,'Disposed assets have disposal date evidence'
union all select 24,'source_asset_duplicates',case when not exists(select source_table,source_line_id from public.accounting_fixed_assets where source_line_id is not null group by source_table,source_line_id having count(*)>1) then 'PASS' else 'FAIL' end,'Source capitalization intake is unique/idempotent'
)
select n,check_name,status,detail from checks order by n;
